import { useEffect, useMemo, useRef, useState, type CSSProperties } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Activity, ArrowDown, ChevronDown, ChevronUp, Dna, Layers, Plus, RotateCcw, Search, Trash2, X, ZoomIn, ZoomOut } from 'lucide-react';
import { api, number, params } from '../api';
import './alphagenome-expression.css';
import { HelpButton } from './HelpGuide';

type Track = {track_id:string; modality:string; name:string; assay_title:string; biosample_name:string|null; biosample_type:string|null; ontology_curie:string|null; gtex_tissue:string|null; strand:string|null; histone_mark:string|null; data_source:string|null; display_unit:string};
type Tile = {tile_id:string; window_start_0based:number; window_end_0based:number; chromosome:string};
type Gene = {ensembl_gene_id:string; gene_symbol:string; gene_start_1based:number; gene_end_1based_inclusive:number; gene_strand:string; tiles:Tile[]};
type Catalog = {available:boolean; genes:Gene[]; tracks:Track[]; snapshot:string; levels:number[]; missing_modalities:string[]};
type Junction = {rank:number; chromosome:string; start_0based:number; end_0based:number; strand:string; value:number};
type Signal = {kind:'signal'; mean:(number|null)[]; maximum:(number|null)[]; bin_width:number};
type Contacts = {kind:'contacts'; size:number; values:(number|null)[]; bin_width:number};
type Junctions = {kind:'junctions'; items:Junction[]; retention:string};
type TrackData = (Signal|Contacts|Junctions)&{start:number;end:number;chromosome:string};
type View = [number,number];
const modes:Record<string,{label:string;color:string;group:string;help:string}> = {
 rna_seq:{label:'RNA-seq',color:'#2563eb',group:'Expression',help:'RNA abundance along the genome.'},
 cage:{label:'CAGE',color:'#0891b2',group:'Transcription',help:'Transcription start-site activity.'},
 procap:{label:'PRO-cap',color:'#0d9488',group:'Transcription',help:'Nascent transcription initiation.'},
 atac:{label:'ATAC',color:'#f97316',group:'Chromatin',help:'Chromatin accessibility.'},
 chip_histone:{label:'Histone ChIP',color:'#9333ea',group:'Chromatin',help:'Histone-mark enrichment over control.'},
 splice_sites:{label:'Splice sites',color:'#db2777',group:'Splicing',help:'Donor or acceptor site probability.'},
 splice_site_usage:{label:'Splice usage',color:'#e11d48',group:'Splicing',help:'Fraction of transcripts using a splice site.'},
 splice_junctions:{label:'Splice junctions',color:'#7c3aed',group:'Splicing',help:'Spliced-read signal connecting donor and acceptor sites.'},
 contact_maps:{label:'Contact map',color:'#ca8a04',group:'3D genome',help:'Contact enrichment relative to genomic-distance expectation.'},
};
const modalityUnits:Record<string,string>={rna_seq:'Normalized read signal',cage:'Normalized read signal',procap:'Normalized read signal',atac:'Normalized insertion signal',chip_histone:'Fold-change over control',splice_sites:'Probability',splice_site_usage:'Fraction',splice_junctions:'Normalized junction signal',contact_maps:'Log-fold over distance-based expectation'};
function AlphaGenomeGuide({snapshot}:{snapshot?:string}){
 return <><div className="help-sections"><section><h3>Start here</h3><p>Add tracks → choose a modality and tissue/cell context → inspect the shared genomic window. Tracks can be added, reordered or removed without a count limit.</p></section><section><h3>What is shown?</h3><p>Reference-sequence predictions, separate from measured Expression, QTL associations and alternate-allele scores in the Variant Browser. Every track retains its assay, strand and scale; these values are not TPM or clinical classifications.</p></section></div><h3>Modalities</h3><div className="help-modality-grid">{Object.entries(modes).map(([id,m])=><section key={id} style={colorStyle(m.color)}><h3>{m.label}</h3><p>{m.help}</p><small>{modalityUnits[id]}</small></section>)}</div><div className="help-sources"><a href="https://www.alphagenomedocs.com/exploring_model_metadata.html" target="_blank" rel="noreferrer">Official modality & unit definitions ↗</a></div><details><summary>Display resolution & coverage</summary><p>This snapshot stores signal means and maxima at 256, 1,024 or 4,096 bins per model window. Zooming cannot restore individual bases. Contacts use a 128 × 128 matrix; junctions retain up to 200 positive connections per track/window. Overlapping windows must not be summed.</p><p>Axes are independent between tracks. Contact colors are centered on zero: blue is below distance-based expectation, orange above it; the original signed value is retained. Display coordinates are 1-based. DNase and transcription-factor ChIP tracks are absent from this snapshot.</p>{snapshot&&<p>Snapshot: {snapshot.slice(0,10)}</p>}</details><details><summary>Context matching</summary><p>Expression links match normalized source labels, not samples or cohorts. Protein–gene associations are checked against current HGNC identity. Missing predictions do not mean absent biological activity.</p></details></>;
}
const normalized=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const contextName=(t:Track)=>t.biosample_name||'Unspecified biosample';
const sceneKey=(t:Track)=>t.ontology_curie||'unspecified';
const details=(t:Track)=>[t.assay_title,t.histone_mark,t.strand&&t.strand!=='.'?`${t.strand} strand`:null].filter(Boolean).join(' · ');
const colorStyle=(color:string)=>({'--ag-color':color} as CSSProperties);
const location=(start:number,end:number)=>`${Math.floor(start+1).toLocaleString()}–${Math.ceil(end).toLocaleString()}`;
const finite=(values:(number|null)[])=>values.filter((v):v is number=>v!==null&&Number.isFinite(v));
const num=(value:number|null)=>value===null?'Unavailable':number(value,5);

function SignalPlot({data,view,color,stat}:{data:Signal&{start:number;end:number};view:View;color:string;stat:'mean'|'maximum'}){
 const [hover,setHover]=useState<number|null>(null);
 const values=data[stat], total=values.length, first=Math.floor(view[0]*total), last=Math.min(total,Math.ceil(view[1]*total));
 const shown=values.slice(first,last), good=finite(shown), low=Math.min(0,...good), high=Math.max(0,...good), span=high-low||1;
 const x=(i:number)=>52+((i+.5)/total-view[0])/(view[1]-view[0])*920;
 const y=(v:number)=>112-(v-low)/span*88;
 // Separate missing runs rather than drawing missing values as zero.
 let path='';let previous=false;
 for(let i=first;i<last;i++){const v=values[i];if(v===null){previous=false;continue;}path+=`${previous?'L':'M'}${x(i).toFixed(2)},${y(v).toFixed(2)} `;previous=true;}
 const active=hover===null?null:Math.max(first,Math.min(last-1,hover));
 return <><svg className="agx-signal" viewBox="0 0 1000 146" role="img" tabIndex={0} aria-label={`Predicted ${stat} signal. Use left and right arrows to inspect bins.`}
  onPointerMove={event=>{const bounds=event.currentTarget.getBoundingClientRect();const ratio=Math.max(0,Math.min(1,((event.clientX-bounds.left)/bounds.width*1000-52)/920));setHover(Math.min(last-1,Math.floor((view[0]+ratio*(view[1]-view[0]))*total)));}}
  onPointerLeave={()=>setHover(null)} onFocus={()=>setHover(first)} onKeyDown={event=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();setHover(Math.max(first,Math.min(last-1,(active??first)+(event.key==='ArrowRight'?1:-1))));}}}>
  {[0,.5,1].map(r=><g key={r}><line x1="52" x2="972" y1={24+r*88} y2={24+r*88} stroke="#dce4f2" strokeDasharray={r===1?undefined:'3 5'}/><text x="44" y={28+r*88} textAnchor="end">{number(high-r*(high-low),2)}</text></g>)}
  <path d={path} fill="none" stroke={color} strokeWidth="1.8"/>
  {[0,.5,1].map(r=><text key={r} x={52+r*920} y="138" textAnchor={r===0?'start':r===1?'end':'middle'}>{Math.round(data.start+(view[0]+r*(view[1]-view[0]))*(data.end-data.start)+(r===1?0:1)).toLocaleString()}</text>)}
  {active!==null&&<g><line x1={x(active)} x2={x(active)} y1="18" y2="112" stroke="#0f172a" strokeDasharray="3 3"/>{values[active]!==null&&<circle cx={x(active)} cy={y(values[active]!)} r="4" fill={color} stroke="white" strokeWidth="2"/>}</g>}
 </svg><div className="agx-inspect" aria-live="polite">{active===null?<><Activity size={14}/>Hover / focus to inspect · {data.bin_width.toLocaleString()} bp/bin</>:<><strong>{location(data.start+active*data.bin_width,data.start+(active+1)*data.bin_width)}</strong><span>Mean <b>{num(data.mean[active])}</b></span><span>Maximum <b>{num(data.maximum[active])}</b></span></>}</div>{!good.length&&<p>No finite signal is available in this range.</p>}</>;
}

function ContactPlot({data,view}:{data:Contacts&{start:number;end:number};view:View}){
 const canvas=useRef<HTMLCanvasElement>(null);const [hover,setHover]=useState<[number,number]|null>(null);
 const first=Math.floor(view[0]*data.size),last=Math.ceil(view[1]*data.size),size=last-first;
 const peak=useMemo(()=>Math.max(0,...finite(data.values).map(Math.abs)),[data.values]);
 useEffect(()=>{const ctx=canvas.current?.getContext('2d');if(!ctx)return;const pixels=ctx.createImageData(size,size);
  for(let y=0;y<size;y++)for(let x=0;x<size;x++){const v=data.values[(first+y)*data.size+first+x];const strength=v===null?0:Math.min(1,Math.abs(v)/(peak||1));const target=v!==null&&v<0?[37,99,235]:[234,88,12];const i=(y*size+x)*4;for(let channel=0;channel<3;channel++)pixels.data[i+channel]=v===null?[218,225,235][channel]:Math.round(250+(target[channel]-250)*strength);pixels.data[i+3]=255;}ctx.putImageData(pixels,0,0);
 },[data,first,size,peak]);
 const coord=(i:number)=>location(data.start+i*data.bin_width,data.start+(i+1)*data.bin_width);
 return <div className="agx-contact"><div><canvas ref={canvas} width={size} height={size} role="img" tabIndex={0} aria-label="Predicted contact matrix; arrow keys inspect genomic bins" onFocus={()=>setHover([first,first])} onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const [x,y]=hover??[first,first];setHover([Math.max(first,Math.min(last-1,x+(event.key==='ArrowRight'?1:event.key==='ArrowLeft'?-1:0))),Math.max(first,Math.min(last-1,y+(event.key==='ArrowDown'?1:event.key==='ArrowUp'?-1:0)))]);}}
  onPointerMove={event=>{const r=event.currentTarget.getBoundingClientRect();setHover([Math.min(last-1,first+Math.floor((event.clientX-r.left)/r.width*size)),Math.min(last-1,first+Math.floor((event.clientY-r.top)/r.height*size))]);}} onPointerLeave={()=>setHover(null)}/><p>Both axes · {location(data.start+first*data.bin_width,data.start+last*data.bin_width)}</p></div><div><strong>Relative contact signal</strong><div className="agx-contact-legend"/><p>−{num(peak)} · 0 · +{num(peak)}</p><p>Log-fold over expectation · gray = missing</p><p>{data.size} × {data.size} retained matrix · {number(data.bin_width,0)} bp per cell axis</p>{hover?<div className="agx-inspect">X {coord(hover[0])}<br/>Y {coord(hover[1])}<br/><b>{num(data.values[hover[1]*data.size+hover[0]])}</b></div>:<p>Hover a cell or use the arrow keys to inspect both genomic intervals.</p>}</div></div>;
}

function JunctionPlot({data,view,color,unit}:{data:Junctions&{start:number;end:number};view:View;color:string;unit:string}){
 const start=data.start+view[0]*(data.end-data.start),end=data.start+view[1]*(data.end-data.start);
 const items=data.items.filter(j=>j.start_0based<end&&j.end_0based>start),peak=Math.max(1,...items.map(j=>j.value));
 const x=(v:number)=>40+(Math.max(start,Math.min(end,v))-start)/(end-start)*920;
 return <><svg className="agx-junctions" viewBox="0 0 1000 170" aria-label="Predicted splice junction connections"><line x1="40" x2="960" y1="145" y2="145" stroke="#cbd5e1"/>{items.map(j=><path key={j.rank} d={`M${x(j.start_0based)},145 Q${(x(j.start_0based)+x(j.end_0based))/2},${135-Math.sqrt(j.value/peak)*120} ${x(j.end_0based)},145`} stroke={color} strokeOpacity={.25+.75*j.value/peak} strokeWidth="1.6" fill="none"><title>{location(j.start_0based,j.end_0based)} · {j.strand} · {num(j.value)}</title></path>)}</svg><p className="agx-footnote">{items.length} retained junctions in view</p><details><summary>Inspect junction coordinates and values</summary><div className="agx-junction-table"><table><thead><tr><th>Genomic interval (1-based)</th><th>Strand</th><th>Predicted signal <small>{unit}</small></th></tr></thead><tbody>{items.map(j=><tr key={j.rank}><td>{location(j.start_0based,j.end_0based)}</td><td>{j.strand}</td><td>{num(j.value)}</td></tr>)}</tbody></table></div></details></>;
}

function TrackCard({accession,gene,tile,track,bins,view,onRemove,onMove,index,total}:{accession:string;gene:Gene;tile:Tile;track:Track;bins:number;view:View;onRemove:()=>void;onMove:(delta:number)=>void;index:number;total:number}){
 const ref=useRef<HTMLElement>(null);const [visible,setVisible]=useState(false);const [collapsed,setCollapsed]=useState(false);const [stat,setStat]=useState<'mean'|'maximum'>('mean');
 useEffect(()=>{const observer=new IntersectionObserver(entries=>setVisible(entries.some(e=>e.isIntersecting)),{rootMargin:'500px'});if(ref.current)observer.observe(ref.current);return()=>observer.disconnect();},[]);
 const query=useQuery({queryKey:['expression-alphagenome-track',accession,gene.ensembl_gene_id,tile.tile_id,track.track_id,bins],queryFn:({signal})=>api<TrackData>(`/proteins/${accession}/expression/alphagenome/track?${params({gene:gene.ensembl_gene_id,tile:tile.tile_id,track_id:track.track_id,bins})}`,signal),enabled:visible&&!collapsed,staleTime:300000,gcTime:120000,retry:1});
 const meta=modes[track.modality];
 return <article ref={ref} className="agx-track" style={colorStyle(meta.color)}><header><div className="agx-track-title"><span className="agx-track-kind">{meta.label}</span><strong>{contextName(track)}</strong><span>{details(track)}</span></div><div className="agx-track-actions"><button title="Move track up" aria-label={`Move ${track.track_id} up`} disabled={index===0} onClick={()=>onMove(-1)}><ChevronUp size={16}/></button><button title="Move track down" aria-label={`Move ${track.track_id} down`} disabled={index===total-1} onClick={()=>onMove(1)}><ChevronDown size={16}/></button><button aria-label={`${collapsed?'Expand':'Collapse'} ${track.track_id}`} onClick={()=>setCollapsed(!collapsed)}>{collapsed?<Plus size={16}/>:<ChevronUp size={16}/>}</button><button aria-label={`Remove ${track.track_id}`} onClick={onRemove}><X size={16}/></button></div></header>
 {!collapsed&&<div className="agx-track-body"><div className="agx-track-meta"><span>Predicted · {track.modality==='contact_maps'?'log-fold over distance-based expectation':track.display_unit}{track.data_source?` · ${track.data_source}`:''}</span>{query.data?.kind==='signal'&&<div className="agx-segment" aria-label={`Statistic for ${track.track_id}`}><button aria-pressed={stat==='mean'} onClick={()=>setStat('mean')}>Mean</button><button aria-pressed={stat==='maximum'} onClick={()=>setStat('maximum')}>Maximum</button></div>}</div>
 {query.error?<div className="agx-error" role="alert">{query.error.message}<button onClick={()=>query.refetch()}>Retry track</button></div>:query.data?.kind==='signal'?<SignalPlot data={query.data} view={view} color={meta.color} stat={stat}/>:query.data?.kind==='contacts'?<ContactPlot data={query.data} view={view}/>:query.data?.kind==='junctions'?<JunctionPlot data={query.data} view={view} color={meta.color} unit={track.display_unit}/>:<div className="agx-loading">{visible?'Loading prediction…':'Track loads when scrolled into view.'}</div>}</div>}
 </article>;
}

function Workspace({catalog,accession,expressionContext}:{catalog:Catalog;accession:string;expressionContext:string}){
 const initial=catalog.tracks.find(t=>t.modality==='rna_seq'&&t.gtex_tissue==='Lung')??catalog.tracks.find(t=>t.modality==='rna_seq')??catalog.tracks[0];
 const [geneId,setGeneId]=useState(catalog.genes[0].ensembl_gene_id),[tileId,setTileId]=useState(catalog.genes[0].tiles[0]?.tile_id??'');
 const [selected,setSelected]=useState<string[]>(initial?[initial.track_id]:[]),[mode,setMode]=useState(initial?.modality??'rna_seq'),[scene,setScene]=useState(initial?sceneKey(initial):'all'),[search,setSearch]=useState(''),[library,setLibrary]=useState(false),[bins,setBins]=useState(1024),[view,setView]=useState<View>([0,1]);
 const gene=catalog.genes.find(g=>g.ensembl_gene_id===geneId)!;const tile=gene.tiles.find(t=>t.tile_id===tileId)??gene.tiles[0];
 const tracks=catalog.tracks.filter(t=>t.modality===mode);
 const scenes=[...new Map(tracks.map(t=>[sceneKey(t),{id:sceneKey(t),name:contextName(t),type:t.biosample_type}])).values()].sort((a,b)=>a.name.localeCompare(b.name));
 const matches=catalog.tracks.filter(t=>expressionContext&&[t.gtex_tissue,t.biosample_name].some(name=>name&&normalized(name)===normalized(expressionContext)));
 const available=tracks.filter(t=>(scene==='all'||sceneKey(t)===scene)&&normalized([contextName(t),t.gtex_tissue,details(t),t.ontology_curie].join(' ')).includes(normalized(search)));
 const add=(id:string)=>setSelected(current=>current.includes(id)?current:[...current,id]);
 const chooseMode=(next:string)=>{setMode(next);setSearch('');if(scene!=='all'&&!catalog.tracks.some(t=>t.modality===next&&sceneKey(t)===scene))setScene('all');};
 const focusGene=()=>{const width=tile.window_end_0based-tile.window_start_0based;const pad=Math.max(2048,(gene.gene_end_1based_inclusive-gene.gene_start_1based)*.12);setView([Math.max(0,(gene.gene_start_1based-1-pad-tile.window_start_0based)/width),Math.min(1,(gene.gene_end_1based_inclusive+pad-tile.window_start_0based)/width)]);setBins(4096);};
 const zoom=(factor:number)=>{const span=Math.min(1,Math.max(1/128,(view[1]-view[0])*factor));const left=Math.max(0,Math.min(1-span,(view[0]+view[1]-span)/2));setView([left,left+span]);if(span<.5)setBins(4096);};
 const pan=(direction:number)=>{const span=view[1]-view[0],left=Math.max(0,Math.min(1-span,view[0]+direction*span*.5));setView([left,left+span]);};
 const left=tile.window_start_0based+view[0]*(tile.window_end_0based-tile.window_start_0based),right=tile.window_start_0based+view[1]*(tile.window_end_0based-tile.window_start_0based);
 return <>
 
 {expressionContext&&<div className="agx-context-link"><Activity size={18}/><div><strong>Measured context: {expressionContext}</strong><p>{matches.length?`${matches.length} tracks with the same context label · samples not matched`:'No matching label in this snapshot.'}</p></div>{matches.length>0&&<button onClick={()=>{const match=matches.find(t=>t.modality==='rna_seq')??matches[0];setMode(match.modality);setScene(sceneKey(match));setSearch('');setLibrary(true);}}>Explore this context <ArrowDown size={14}/></button>}</div>}
 <div className="agx-toolbar"><div><label>Gene<select aria-label="AlphaGenome gene" value={geneId} onChange={e=>{const g=catalog.genes.find(g=>g.ensembl_gene_id===e.target.value)!;setGeneId(g.ensembl_gene_id);setTileId(g.tiles[0].tile_id);setView([0,1]);}}>{catalog.genes.map(g=><option key={g.ensembl_gene_id} value={g.ensembl_gene_id}>{g.gene_symbol} · {g.ensembl_gene_id}</option>)}</select></label><label>Model window<select aria-label="AlphaGenome model window" value={tile.tile_id} onChange={e=>{setTileId(e.target.value);setView([0,1]);}}>{gene.tiles.map(t=><option key={t.tile_id} value={t.tile_id}>{t.tile_id} · {location(t.window_start_0based,t.window_end_0based)}</option>)}</select></label></div><button className="agx-primary" aria-expanded={library} onClick={()=>setLibrary(!library)}><Plus size={16}/>Add tracks <span>{selected.length}</span></button></div>
 {library&&<div className="agx-library"><div className="agx-library-heading"><div><h4>Add prediction tracks</h4></div><button aria-label="Close track library" onClick={()=>setLibrary(false)}><X size={18}/></button></div><div className="agx-modalities">{Object.entries(modes).map(([id,m])=>{const count=catalog.tracks.filter(t=>t.modality===id).length;return <button key={id} style={colorStyle(m.color)} aria-pressed={mode===id} onClick={()=>chooseMode(id)} disabled={!count}><small>{m.group}</small><strong>{m.label}</strong><span>{count} tracks</span></button>;})}</div><div className="help-inline"><strong>{modes[mode].label}</strong><HelpButton title="AlphaGenome guide" label="Modality guide"><AlphaGenomeGuide snapshot={catalog.snapshot}/></HelpButton></div><div className="agx-library-filters"><label>Prediction context<select aria-label="AlphaGenome prediction context" value={scene} onChange={e=>setScene(e.target.value)}><option value="all">All available contexts</option>{scenes.map(s=><option key={s.id} value={s.id}>{s.name} · {s.type?.replaceAll('_',' ')||'unspecified'}</option>)}</select></label><label><span><Search size={13}/>Find an assay, mark or context</span><input aria-label="Search AlphaGenome tracks" value={search} onChange={e=>setSearch(e.target.value)} placeholder="e.g. H3K27ac, Lung, + strand"/></label></div><div className="agx-library-results">{available.map(t=><div key={t.track_id} className="agx-candidate"><div><strong>{contextName(t)}</strong><span>{details(t)}</span><small>{[t.ontology_curie,t.gtex_tissue||t.biosample_type?.replaceAll('_',' '),t.track_id].filter(Boolean).join(' · ')}</small></div><button disabled={selected.includes(t.track_id)} onClick={()=>add(t.track_id)} aria-label={`Add ${t.track_id}`}>{selected.includes(t.track_id)?'Added':<><Plus size={14}/>Add</>}</button></div>)}{!available.length&&<p>No track matches these choices. Try another context or clear the search.</p>}</div><p className="agx-footnote">{available.length} matching tracks</p></div>}
 <div className="agx-locus"><div><Dna size={18}/><strong>{tile.chromosome}:{location(left,right)}</strong><span>GRCh38 · {gene.gene_symbol} {gene.gene_strand==='-'?'←':'→'}</span></div><div className="agx-viewport"><button onClick={focusGene}>Gene region</button><button aria-label="Pan genomic window left" disabled={view[0]===0} onClick={()=>pan(-1)}>←</button><button aria-label="Zoom in genomic window" onClick={()=>zoom(.5)} disabled={view[1]-view[0]<=1/128}><ZoomIn size={15}/></button><button aria-label="Zoom out genomic window" onClick={()=>zoom(2)} disabled={view[1]-view[0]>=1}><ZoomOut size={15}/></button><button aria-label="Pan genomic window right" disabled={view[1]===1} onClick={()=>pan(1)}>→</button><button onClick={()=>setView([0,1])}><RotateCcw size={13}/>Full window</button><label>Detail<select aria-label="AlphaGenome display detail" value={bins} onChange={e=>setBins(Number(e.target.value))}>{catalog.levels.map(n=><option key={n} value={n}>{n.toLocaleString()} bins</option>)}</select></label></div></div>
 <div className="agx-gene-strip" aria-label={`${gene.gene_symbol} gene interval within the current window`}><span style={{left:`${Math.max(0,Math.min(100,(gene.gene_start_1based-1-left)/(right-left)*100))}%`,width:`${Math.max(0,(Math.min(right,gene.gene_end_1based_inclusive)-Math.max(left,gene.gene_start_1based-1))/(right-left)*100)}%`}}/></div>
 <p className="agx-footnote">1-based coordinates · {number((tile.window_end_0based-tile.window_start_0based)/bins,0)} bp/bin · downsampled predictions</p>
 <div className="agx-stack-heading"><strong>{selected.length} {selected.length===1?'track':'tracks'} in this view</strong>{selected.length>0&&<button onClick={()=>setSelected([])}><Trash2 size={13}/>Clear tracks</button>}</div>
 <div className="agx-stack">{selected.map((id,index)=>{const t=catalog.tracks.find(t=>t.track_id===id)!;return <TrackCard key={id} accession={accession} gene={gene} tile={tile} track={t} bins={bins} view={view} index={index} total={selected.length} onRemove={()=>setSelected(current=>current.filter(id=>id!==t.track_id))} onMove={delta=>setSelected(current=>{const next=[...current];[next[index],next[index+delta]]=[next[index+delta],next[index]];return next;})}/>;})}{!selected.length&&<div className="agx-empty"><Layers size={26}/><strong>Your prediction view is empty</strong><button className="agx-primary" onClick={()=>setLibrary(true)}>Choose a track</button></div>}</div>
 
 </>;
}

export function AlphaGenomeExpression({accession,expressionContext=''}:{accession:string;expressionContext?:string}){
 const query=useQuery({queryKey:['expression-alphagenome',accession],queryFn:({signal})=>api<Catalog>(`/proteins/${accession}/expression/alphagenome`,signal),staleTime:300000,retry:1});
 const data=query.data;
 return <section id="alphagenome" className="agx" aria-label="AlphaGenome regulatory predictions"><span id="expression-predictions" className="agx-legacy-anchor" aria-hidden="true"/><header className="agx-heading"><div className="agx-heading-icon"><Dna size={24}/></div><div><span className="agx-eyebrow">Sequence-based regulatory predictions</span><h2>AlphaGenome <HelpButton title="AlphaGenome guide" label="Guide"><AlphaGenomeGuide snapshot={data?.snapshot}/></HelpButton></h2><p>Multimodal reference-sequence predictions</p></div><span className="agx-predicted">Predicted</span></header>
 {data&&<div className="agx-stats"><span><b>{data.genes.length}</b> linked {data.genes.length===1?'gene':'genes'}</span><span><b>{new Set(data.tracks.map(t=>t.modality)).size}</b> modalities</span><span><b>{new Set(data.tracks.map(t=>t.ontology_curie).filter(Boolean)).size}</b> biosample IDs</span><span><b>{data.tracks.length}</b> available tracks</span><span>GRCh38 · reference sequence</span></div>}
 {query.error?<div className="agx-error" role="alert">{query.error.message}<button onClick={()=>query.refetch()}>Retry predictions</button></div>:!data?<div className="agx-loading">Loading prediction contexts…</div>:!data.available?<p className="agx-empty">No prediction available for this gene.</p>:<Workspace key={accession} accession={accession} catalog={data} expressionContext={expressionContext}/>}
 </section>;
}
