import { useEffect, useState, type CSSProperties } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, ArrowUpRight, ChevronRight, Search, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { ColumnDef } from '@tanstack/react-table';
import { api, display, number, params, type RecordData } from '../api';
import { DataTable, Disclosure, LinkOut, Pager, Status } from './ui';
import { clinicalTone } from './variant-evidence-model';
import './disease-clinvar.css';
import './disease-clinvar-rcv.css';

interface ConditionSet {condition_set_id:string;condition_names:string[];identifier_groups:string[];variant_count:number;source_record_count:number;origins:string[];evidence_status:string;}
export interface ConditionListData {items:ConditionSet[];totals:{condition_sets:number;variants:number;source_records:number};filtered_condition_sets:number;offset:number;limit:number;next_offset:number|null;source:RecordData;notes:string[];formal_relation_available:boolean;}
interface RcvRecord extends RecordData {rcv_id:string;rcv_version:number;version_basis:string;source_dated:string;condition_members:RecordData[];scv_records:RecordData[];}
interface ConditionVariant extends RecordData {variant_id:string;chromosome:string;position:number;ref:string;alt:string;variation_id:string;allele_id:string;transcript_change:RecordData;canonical_positions:RecordData[];variation_summary:RecordData;rcv_accessions:string[];scv_accessions:Record<string,string[]>;rcv_records:RcvRecord[];condition_link_status:string;clinvar_url:string;}
interface ConditionDetailData {condition_set_id:string;condition_names:string[];identifier_groups:string[];source_version:string;items:ConditionVariant[];total_variants:number;next_offset:number|null;evidence_status:string;notes:string[];}

const EVIDENCE_COLOURS:Record<string,string>={germline:'#6d28d9',somatic:'#0369a1',oncogenicity:'#b45309',source:'#be185d'};
function EvidenceTag({children,kind}:{children:unknown;kind:string}){if(children===null||children===undefined||children===''||children==='-')return null;return kind==='source'?<span className="di-evidence-tag" style={{'--di-tag':EVIDENCE_COLOURS[kind]??'#475569'} as CSSProperties}>{display(children)}</span>:<span className="di-classification"><small>{kind==='germline'?'Germline':kind==='somatic'?'Somatic impact':'Oncogenicity'}</small><span className={`vc-clinical vc-clinical-${clinicalTone(children)}`}>{display(children)}</span></span>;}
function shortIds(ids:string[]){return ids.length>3?`${ids.slice(0,3).join(' · ')} +${ids.length-3}`:ids.join(' · ');}
function asRows(value:unknown){return Array.isArray(value)?value as RecordData[]:[];}
function sourceVersion(status:unknown){return status==='summary_exact_version'?'Summary accession version matched':status==='summary_unversioned_xml_observed'?'Summary accession unversioned · XML version observed':status==='summary_version_mismatch'?'Summary/XML version mismatch':status==='not_listed_in_summary'?'Nested in approved RCV · not listed in summary':display(status);}

function RcvEvidence({row}:{row:ConditionVariant}){
 const rcvs=row.rcv_records??[];
 if(!rcvs.length)return <p className="di-condition-gap">{row.condition_link_status==='awaiting_formal_curated_import'?'Condition-resolved RCV/SCV evidence awaits validated service import.':row.condition_link_status==='summary_no_rcv_accession'?'No RCV accession was supplied by this summary row.':'No RCV passed the current SNV, source-row, VariationID/AlleleID and accession checks.'}</p>;
 return <div className="di-rcv-list">{rcvs.map(rcv=><details className="di-rcv-record" key={`${rcv.rcv_id}.${rcv.rcv_version}`}><summary><strong>{rcv.rcv_id}.{rcv.rcv_version}</strong><span>{asRows(rcv.condition_members).length} source condition members · {asRows(rcv.scv_records).length} SCV submissions</span><ChevronRight size={13}/></summary><div className="di-rcv-body"><div className="di-rcv-meta"><LinkOut href={`https://www.ncbi.nlm.nih.gov/clinvar/${encodeURIComponent(rcv.rcv_id)}/`}>Open RCV source</LinkOut><span>{sourceVersion(rcv.version_basis)}</span><span>XML dated {display(rcv.source_dated)}</span></div><div className="di-rcv-classifications"><strong>RCV full condition-set classification</strong><div><EvidenceTag kind="germline">{rcv.germline_classification}</EvidenceTag>{Boolean(rcv.germline_review_status)&&<span>{display(rcv.germline_review_status)}</span>}</div><div><EvidenceTag kind="somatic">{rcv.somatic_clinical_impact}</EvidenceTag>{Boolean(rcv.somatic_review_status)&&<span>{display(rcv.somatic_review_status)}</span>}</div><div><EvidenceTag kind="oncogenicity">{rcv.oncogenicity_classification}</EvidenceTag>{Boolean(rcv.oncogenicity_review_status)&&<span>{display(rcv.oncogenicity_review_status)}</span>}</div>{rcv.no_classification?<span>{display(rcv.no_classification)}</span>:null}</div><div className="di-rcv-members"><strong>Original TraitSet members · navigation only</strong>{asRows(rcv.condition_members).map(member=><div key={String(member.member_index)}><span>{asRows(member.names_json).map(name=>String(name.value??'')).filter(Boolean).join(' · ')||'Name unavailable'}</span><small>{asRows(member.xrefs_json).map(ref=>`${ref.DB??ref.db??'Source'}:${ref.ID??ref.id??'?'}`).join(' · ')||`Trait ${display(member.trait_id)}`}</small></div>)}</div><div className="di-scv-list"><strong>SCV source submissions</strong>{asRows(rcv.scv_records).map(scv=><div key={`${scv.scv_id}.${scv.scv_version}`}><LinkOut href={`https://www.ncbi.nlm.nih.gov/clinvar/${encodeURIComponent(String(scv.scv_id))}/`}>{String(scv.scv_id)}.{String(scv.scv_version)}</LinkOut><span>{display(scv.submitter)}</span><small>{sourceVersion(scv.summary_version_status)} · {display(scv.date_last_evaluated)}</small><div><EvidenceTag kind="germline">{scv.germline_classification}</EvidenceTag><EvidenceTag kind="somatic">{scv.somatic_clinical_impact}</EvidenceTag><EvidenceTag kind="oncogenicity">{scv.oncogenicity_classification}</EvidenceTag></div>{scv.review_status?<small>SCV review: {display(scv.review_status)}</small>:null}</div>)}{!asRows(rcv.scv_records).length&&<small>No SCV submission is present under this approved RCV.</small>}</div><p>RCV classification belongs to its intact condition set, not independently to each member; SCV judgments remain submitter records.</p></div></details>)}</div>;
}

export function useClinvarConditionSummary(accession:string){
  return useQuery({queryKey:['clinvar-condition-list',accession,'',0,1],queryFn:({signal})=>api<ConditionListData>(`/proteins/${accession}/diseases/clinvar-conditions?${params({limit:1,offset:0})}`,signal)});
}

function ProteinChangeParts({change,transcript=false}:{change:RecordData;transcript?:boolean}){
 const position=transcript?change.aa_position:change.position;
 return <div className="di-protein-parts"><dl><div><dt>REF</dt><dd>{display(change.ref_aa)}</dd></div><div><dt>Position</dt><dd>{display(position)}</dd></div><div><dt>ALT</dt><dd>{display(change.alt_aa)}</dd></div></dl>{transcript&&!position&&Boolean(change.protein_change)&&<span className="di-original-change">Source change: {display(change.protein_change)}</span>}</div>;
}

function ConditionDetail({accession,id}:{accession:string;id:string}){
  const [page,setPage]=useState(0),limit=25;
  const result=useQuery({queryKey:['clinvar-condition-detail',accession,id,page],queryFn:({signal})=>api<ConditionDetailData>(`/proteins/${accession}/diseases/clinvar-conditions/${encodeURIComponent(id)}?${params({limit,offset:page*limit})}`,signal)});
  const data=result.data;
  const columns:ColumnDef<ConditionVariant>[]=[
    {id:'variant',header:'Genomic SNV · GRCh38',cell:({row})=><div className="di-clinvar-variant"><Link to={`/protein/${accession}?variants_search=${encodeURIComponent(row.original.variant_id)}#variants`}><strong>{row.original.chromosome}:{row.original.position}</strong><span>{row.original.ref} → {row.original.alt}</span><ArrowUpRight size={12}/></Link></div>},
    {id:'protein',header:'Protein position',cell:({row})=>row.original.canonical_positions.length?<div>{row.original.canonical_positions.map((position,index)=><ProteinChangeParts key={index} change={position}/>)}<small>Verified current UniProt sequence</small></div>:<div><ProteinChangeParts change={row.original.transcript_change??{}} transcript/><small>Selected transcript only · no verified UniProt position</small></div>},
    {id:'classification',header:'Variation-level summaries',cell:({row})=>{const evidence=row.original.variation_summary;return <div className="di-variation-evidence"><EvidenceTag kind="germline">{evidence.germline_classification}</EvidenceTag><EvidenceTag kind="somatic">{evidence.somatic_clinical_impact}</EvidenceTag><EvidenceTag kind="oncogenicity">{evidence.oncogenicity}</EvidenceTag><small>Not assigned to an individual condition member</small></div>;}},
    {id:'source',header:'ClinVar source record',cell:({row})=><div className="di-source-record"><LinkOut href={row.original.clinvar_url}>Variation {display(row.original.variation_id)}</LinkOut><span>Allele {display(row.original.allele_id)}</span><RcvEvidence row={row.original}/><Disclosure title={`Original summary list · ${row.original.rcv_accessions.length} RCV / ${Object.values(row.original.scv_accessions).flat().length} SCV`}><p>RCV: {shortIds(row.original.rcv_accessions)||'—'}</p>{Object.entries(row.original.scv_accessions).map(([kind,ids])=>ids.length?<p key={kind}>{kind.replaceAll('_',' ')} SCV: {shortIds(ids)}</p>:null)}<small>Unversioned summary accessions are retained separately; RCV/SCV evidence above uses the validated exact-pair relation.</small></Disclosure></div>},
  ];
  return <Status loading={result.isPending} error={result.error}>{data&&<div className="di-condition-detail"><div className="di-condition-scope"><EvidenceTag kind="source">ClinVar summary {data.source_version}</EvidenceTag><span>{number(data.total_variants,0)} linked SNVs</span></div><div className="di-condition-scroll" key={page} role="region" tabIndex={0} aria-label={`ClinVar variants for ${data.condition_names.join(' · ')} · page ${page+1}`}><DataTable items={data.items} columns={columns}/></div><p className="di-condition-window-note">Scroll within this table · {number(data.items.length,0)} SNVs on this page of {number(data.total_variants,0)} linked SNVs</p><Pager page={page} count={data.items.length} next={data.next_offset===null?null:String(data.next_offset)} onPrevious={()=>setPage(current=>Math.max(0,current-1))} onNext={()=>{if(data.next_offset!==null)setPage(current=>current+1);}} onJump={setPage} totalPages={Math.ceil(data.total_variants/limit)} loading={result.isFetching}/><p className="di-condition-note">Summary condition sets remain the browsing groups. RCV labels apply to the full source TraitSet; variation summaries and SCV submissions keep their separate evidence levels.</p></div>}</Status>;
}

function ConditionRow({accession,item}:{accession:string;item:ConditionSet}){
  const [open,setOpen]=useState(false);
  return <details className="di-condition-row" open={open} onToggle={event=>setOpen(event.currentTarget.open)}><summary><span><strong>{item.condition_names.join(' · ')}</strong>{item.identifier_groups.length>0&&<small>{item.identifier_groups.join(' | ')}</small>}</span><span className="di-condition-count"><b>{number(item.variant_count,0)}</b> SNVs</span><ChevronRight size={16}/></summary>{open&&<ConditionDetail accession={accession} id={item.condition_set_id}/>}</details>;
}

export function ClinvarConditionBrowser({accession,onClose}:{accession:string;onClose:()=>void}){
  const [draft,setDraft]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0),limit=12;
  useEffect(()=>{const timer=setTimeout(()=>{setSearch(draft.trim());setPage(0);},250);return()=>clearTimeout(timer);},[draft]);
  const result=useQuery({queryKey:['clinvar-condition-list',accession,search,page,limit],queryFn:({signal})=>api<ConditionListData>(`/proteins/${accession}/diseases/clinvar-conditions?${params({search,limit,offset:page*limit})}`,signal)});
  const data=result.data;
  return <div className="cx-record-area di-clinvar-browser"><div className="cx-record-heading"><div><span>Current SNV scope</span><h3>ClinVar condition sets</h3></div><button className="cx-back" onClick={onClose}><ArrowLeft size={13}/>Back to disease sources</button></div><div className="di-clinvar-intro"><ShieldCheck size={20}/><div><strong>Condition names and identifiers from the current ClinVar summary</strong><p>Multi-condition sets stay intact. Variant-wide classifications, somatic impact and oncogenicity remain separate source fields.</p></div></div><label className="di-condition-search"><Search size={15}/><input value={draft} onChange={event=>setDraft(event.target.value)} placeholder="Search condition name or source identifier" aria-label="Search ClinVar condition sets"/></label><Status loading={result.isPending} error={result.error} empty={!data?.items.length}>{data&&<><div className="di-condition-totals"><span><strong>{number(data.totals.condition_sets,0)}</strong> exact condition sets</span><span><strong>{number(data.totals.variants,0)}</strong> current SNVs</span><span><strong>{number(data.totals.source_records,0)}</strong> summary records</span></div><div className="di-condition-list">{data.items.map(item=><ConditionRow accession={accession} item={item} key={item.condition_set_id}/>)}</div><Pager page={page} count={data.items.length} next={data.next_offset===null?null:String(data.next_offset)} onPrevious={()=>setPage(current=>Math.max(0,current-1))} onNext={()=>{if(data.next_offset!==null)setPage(current=>current+1);}} onJump={setPage} totalPages={Math.ceil(data.filtered_condition_sets/limit)} loading={result.isFetching}/></>}</Status><p className="di-condition-note">{data?.formal_relation_available?'Expanded SNVs show validated RCV condition sets and nested SCV submissions when the exact current source row and VariationID/AlleleID pair agree.':'Available layer: 2026-09-06 variant summary condition sets. Validated RCV/SCV relationships have not yet been imported.'}</p></div>;
}
