import { useEffect, useState, type CSSProperties } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Activity, ArrowRight, BookOpen, Database, Dna, ExternalLink, Fingerprint, HeartPulse, Layers, Search } from 'lucide-react';
import { api } from '../api';
import { Status } from './ui';
import { documentationIntro, documentationSections, sourceDescriptions, apiExamples } from '../data/documentation';
import './database-pages.css';
import { DataOverviewCharts, type OverviewBreakdown } from './DataOverviewCharts';

interface Metric {key:string;label:string;value:number|null;unit:string;basis:string}
type Breakdown=OverviewBreakdown;
interface Section {id:string;title:string;description:string;metrics:Metric[];breakdowns:Breakdown[];notes:string[]}
interface Source {id:string;name:string;group:string;version?:string;url?:string}
interface Statistics {schema_version:number;generated_at:string;versions:{module:string;label:string;service_version:string;upstream_versions:{name:string;version:string}[]}[];sections:Section[];notes:string[];sources?:Source[]}
const colours:Record<string,string>={proteins:'#059669',variants:'#7c3aed',predictors:'#2563eb',diseases:'#e11d48',context:'#0891b2'};
const icons:Record<string,typeof Dna>={proteins:Fingerprint,variants:Dna,predictors:Activity,diseases:HeartPulse,context:Layers};
const count=(value:number|null)=>value===null?'Not available':value.toLocaleString('en-US');
function useStatistics(){return useQuery({queryKey:['catalog-statistics'],queryFn:({signal})=>api<Statistics>('/catalog/statistics',signal)});}
function usePagePosition(title:string){const {pathname,hash}=useLocation();useEffect(()=>{
 document.title=`${title} · memVar`;
 let observer:MutationObserver|undefined;let frame:number|undefined;
 if(!hash)window.scrollTo(0,0);
 else {
  // Dataset sections arrive after the statistics request; restore fragment navigation then.
  const scrollToSection=()=>{const target=document.getElementById(hash.slice(1));if(!target)return false;frame=requestAnimationFrame(()=>target.scrollIntoView({block:'start',behavior:'instant'}));observer?.disconnect();return true;};
  if(!scrollToSection()){observer=new MutationObserver(scrollToSection);observer.observe(document.body,{childList:true,subtree:true});}
 }
 return()=>{observer?.disconnect();if(frame!==undefined)cancelAnimationFrame(frame);document.title='memVar · Human membrane protein variants';};
 },[pathname,title,hash]);}
function PageIntro({documentation=false}:{documentation?:boolean}){return <header className="db-intro"><span className="db-eyebrow"><Database size={15}/> THE MEMVAR DATABASE</span><h1>{documentation?'Documentation':'Data overview'}</h1><p>{documentation?documentationIntro.lead:'Explore the human membrane protein collection, its connected evidence and the sources behind it.'}</p><div className="db-intro-links"><Link className="button primary" to={documentation?'/results':'/search'}>{documentation?'View data coverage':'Explore proteins'}<ArrowRight size={16}/></Link><Link className="button subtle" to={documentation?'/search':'/documentation'}>{documentation?'Find a protein':'Read the documentation'}<BookOpen size={16}/></Link></div></header>;}
function MetricCard({metric,section}:{metric:Metric;section:Section}){const Icon=icons[section.id]??Layers;return <a className="db-metric-card" href={`#${section.id}`} style={{'--db-accent':colours[section.id]??'#0891b2'} as CSSProperties}><span className="db-metric-icon"><Icon size={21}/></span><span className="db-metric-label">{metric.label}</span><strong>{count(metric.value)}</strong><small>{metric.unit}</small><span className="db-metric-link">Explore coverage <ArrowRight size={14}/></span></a>;}
function DatasetSection({section}:{section:Section}){const Icon=icons[section.id]??Layers;return <section className="db-section" id={section.id} style={{'--db-accent':colours[section.id]??'#0891b2'} as CSSProperties}><div className="db-section-title"><span className="db-section-icon"><Icon size={21}/></span><div><h2>{section.title}</h2><p>{section.description}</p></div></div><div className="db-inline-metrics">{section.metrics.map(metric=><div key={metric.key}><strong>{count(metric.value)}</strong><span>{metric.label}</span><small>{metric.unit}</small></div>)}</div><DataOverviewCharts section={section}/><details className="db-methods"><summary>How these numbers are counted</summary><dl>{section.metrics.map(metric=><div key={metric.key}><dt>{metric.label}</dt><dd>{metric.basis}</dd></div>)}</dl>{section.notes.map(note=><p key={note}>{note}</p>)}</details></section>;}
export function ResultsPage(){const query=useStatistics();usePagePosition('Data overview');return <main className="db-page"><PageIntro/><Status loading={query.isPending} error={query.error}>{query.data&&<><div className="db-metric-grid">{query.data.sections.map(section=>section.metrics[0]&&<MetricCard key={section.id} section={section} metric={section.metrics[0]}/>)}</div><div className="db-overview-note"><Database size={17}/><p>Counts describe the current memVar collection. Source coverage and annotation categories can overlap; their totals are not a count of independent proteins or variants.</p><Link to="/documentation#versions">Data versions <ArrowRight size={14}/></Link></div><nav className="db-section-nav" aria-label="Data overview sections">{query.data.sections.map(section=><a href={`#${section.id}`} key={section.id}>{section.title}</a>)}</nav>{query.data.sections.map(section=><DatasetSection section={section} key={section.id}/>)}<section className="db-bottom-note"><h2>Reading the collection</h2>{query.data.notes.map(note=><p key={note}>{note}</p>)}<Link to="/documentation#sources">Explore data sources <ArrowRight size={15}/></Link></section></>}</Status></main>;}
function VersionTable({data}:{data:Statistics}){return <><p>Each data module keeps its own confirmed snapshot. A memVar build identifier is separate from an upstream database release.</p><div className="db-table-wrap"><table><thead><tr><th>Module</th><th>memVar snapshot</th><th>Confirmed upstream versions</th></tr></thead><tbody>{data.versions.map(version=><tr key={version.module}><th>{version.label}</th><td><code>{version.service_version}</code></td><td>{version.upstream_versions.length?version.upstream_versions.map(item=><span className="db-version" key={`${item.name}-${item.version}`}><b>{item.name}</b> {item.version}</span>):'—'}</td></tr>)}</tbody></table></div><p className="db-caption">Only confirmed version labels are shown. A dash means that no upstream release label is published here; it does not imply an empty dataset.</p></>;}
function Sources({data}:{data?:Statistics}){const [term,setTerm]=useState('');const [group,setGroup]=useState('All');const [expanded,setExpanded]=useState(false);const sources=sourceDescriptions.map(source=>({...source,version:data?.sources?.find(item=>item.id===source.id||item.name===source.name)?.version}));const groups=['All',...new Set(sources.map(source=>source.group))];const filtered=sources.filter(source=>(group==='All'||source.group===group)&&`${source.name} ${source.description}`.toLowerCase().includes(term.toLowerCase()));return <><p>Collection-defining resources and supporting annotation sources have different roles. This directory explains the evidence supplied by each resource.</p><div className="db-source-controls"><label><Search size={16}/><input aria-label="Search data sources" placeholder="Search sources or evidence…" value={term} onChange={event=>setTerm(event.target.value)}/></label><select aria-label="Source data type" value={group} onChange={event=>setGroup(event.target.value)}>{groups.map(item=><option key={item}>{item}</option>)}</select><span aria-live="polite">{filtered.length} sources</span></div><div className="db-source-grid">{(expanded?filtered:filtered.slice(0,12)).map(source=><article key={source.id}><span className="db-source-group">{source.group}</span><h3><a href={source.url} target="_blank" rel="noreferrer">{source.name}<ExternalLink size={14}/></a></h3>{source.version&&<span className="db-version">{source.version}</span>}<p>{source.description}</p></article>)}</div>{filtered.length>12&&<button type="button" className="text-button db-show-sources" onClick={()=>setExpanded(!expanded)}>{expanded?'Show fewer sources':`Show all ${filtered.length} sources`}</button>}{!filtered.length&&<p>No sources match these filters.</p>}</>;}
export function DocumentationPage(){const query=useStatistics();usePagePosition('Documentation');return <main className="db-page db-doc-page"><PageIntro documentation/><div className="db-doc-layout"><nav className="db-doc-nav" aria-label="Documentation sections"><a href="#introduction">Introduction</a>{documentationSections.filter(section=>section.id!=='api').map(section=><a key={section.id} href={`#${section.id}`}>{section.title}</a>)}<a href="#sources">Data sources</a><a href="#versions">Data versions</a><a href="#api">Programmatic access</a></nav><div className="db-doc-content"><section id="introduction" className="db-doc-section"><h2>{documentationIntro.title}</h2>{documentationIntro.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}<div className="db-workflow"><span><b>01</b> Find a membrane protein</span><ArrowRight size={18}/><span><b>02</b> Explore its evidence</span><ArrowRight size={18}/><span><b>03</b> Inspect source records</span></div></section>{documentationSections.filter(section=>section.id!=='api').map(section=><section className="db-doc-section" id={section.id} key={section.id}><h2>{section.title}</h2>{section.intro&&<p>{section.intro}</p>}<div className="db-guide-grid">{section.items.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.body}</p>{item.href&&<Link to={item.href}>Explore <ArrowRight size={14}/></Link>}</article>)}</div></section>)}<section id="sources" className="db-doc-section"><h2>Data sources</h2><Sources data={query.data}/></section><section id="versions" className="db-doc-section"><h2>Current data versions</h2><Status loading={query.isPending} error={query.error}>{query.data&&<VersionTable data={query.data}/>}</Status></section><section id="api" className="db-doc-section"><h2>Programmatic access</h2><p>The same read-only API supports the data shown in the browser. Explore request parameters and response schemas in the <a href="/docs" target="_blank" rel="noreferrer">interactive API reference <ExternalLink size={13}/></a>.</p><div className="db-api-list">{apiExamples.map(example=><article key={example.path}><h3>{example.title}</h3><a href={example.path} target="_blank" rel="noreferrer"><code>GET {example.path}</code><ExternalLink size={14}/></a><p>{example.description}</p></article>)}</div></section></div></div></main>;}
