import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useSearchParams, Link } from 'react-router-dom';
import { Activity, ArrowUpRight, Dna, HeartPulse, Network, SlidersHorizontal } from 'lucide-react';
import type { ColumnDef } from '@tanstack/react-table';
import { api, display, label, number, params, type Page, type RecordData } from '../api';
import { Badge, DataTable, DetailFields, Disclosure, Fields, LinkOut, Modal, Pager, Panel, SelectFilter, Status } from './ui';

function useListing<T=RecordData>(accession:string,section:string,keys:string[],defaults:Record<string,string>={}){
 const [search,setSearch]=useSearchParams();const filters=Object.fromEntries(keys.map(key=>[key,search.get(`${section}_${key}`)??defaults[key]??'']));
 const signature=JSON.stringify([accession,filters]);const [state,setState]=useState<{signature:string;cursors:(string|null)[];page:number}>({signature,cursors:[null],page:0});const current=state.signature===signature?state:{signature,cursors:[null],page:0};
 const query=useQuery({queryKey:[section,accession,signature,current.cursors[current.page]],queryFn:({signal})=>api<Page<T>>(`/proteins/${accession}/${section}?${params({...filters,limit:10,cursor:current.cursors[current.page]})}`,signal)});
 const change=(key:string,value:string,clearKeys:string[]=[])=>{setState({signature:'',cursors:[null],page:0});setSearch(previous=>{const next=new URLSearchParams(previous);for(const clearKey of clearKeys)next.delete(`${section}_${clearKey}`);if(value)next.set(`${section}_${key}`,value);else next.delete(`${section}_${key}`);return next;},{replace:true});};
 const next=()=>{if(query.data?.next_cursor)setState({signature,cursors:[...current.cursors.slice(0,current.page+1),query.data.next_cursor],page:current.page+1});};
 const previous=()=>setState({...current,page:Math.max(0,current.page-1)});
 return {query,filters,change,pager:{page:current.page,count:query.data?.items.length??0,next:query.data?.next_cursor,onPrevious:previous,onNext:next,loading:query.isFetching}};
}
function Val({value}:{value:unknown}){return <>{value===null||value===undefined||value===''?<span className="muted">—</span>:display(value)}</>;}
function Prediction({item}:{item:RecordData}){return <span className="prediction"><small>{display(item.tool??item.field)}</small><strong>{typeof item.value==='number'?number(item.value):display(item.value)}</strong></span>;}
function SourceEvidence({sources,hasMore}:{sources:RecordData[];hasMore:boolean}){
 const groups=Array.from(new Set(sources.map(s=>String(s.source))));
 return <>{groups.map(source=>{const records=sources.filter(s=>s.source===source);return <Disclosure key={source} title={`${source} · ${records.length} source record${records.length===1?'':'s'}`}>
 {records.map((record,index)=><div className="annotation" key={index}><p className="small muted">Record {index+1}{record.source_id&&record.source_id!=='.'?` · ${display(record.source_id)}`:''}</p><DetailFields items={record.fields}/><LinkOut href={record.url}>View source record</LinkOut></div>)}
 </Disclosure>;})}{hasMore&&<p className="small muted">The first 100 source records are shown. Additional records can be consulted through the source links.</p>}</>;
}
function DdgConventions({rows}:{rows:RecordData[]}){
 const unique=rows.filter((row,index)=>rows.findIndex(other=>other.model===row.model&&other.effect_convention===row.effect_convention)===index);
 return <>{unique.map((row,index)=><p className="small muted" key={index}><strong>{display(row.model)}:</strong> {display(row.effect_convention??'Sign convention not provided by the source.')}</p>)}</>;
}
function VariantDetail({id,accession,onClose}:{id:string;accession:string;onClose:()=>void}){
 const query=useQuery({queryKey:['variant',id,accession],queryFn:({signal})=>api<RecordData>(`/variants/${encodeURIComponent(id)}?${params({accession})}`,signal)});const d=query.data;const variant=(d?.variant??{}) as RecordData;const frequencies=(d?.frequencies??{}) as RecordData;
 return <Modal title={display(variant.hgvsp??variant.variant_id??id)} onClose={onClose}><Status loading={query.isPending} error={query.error}>{d&&<>
 <Fields items={[{label:'Variant',value:variant.variant_id??id},{label:'Chromosome',value:variant.chromosome},{label:'GRCh38 position',value:variant.position},{label:'Reference / alternate',value:variant.ref&&`${variant.ref} → ${variant.alt}`},{label:'Assembly',value:variant.assembly}]}/>
 {Array.isArray(d.consequences)&&<Disclosure title="Transcript consequences"><DataTable items={d.consequences as RecordData[]} columns={[{id:'transcript',header:'Transcript',cell:({row})=><Val value={row.original.transcript_id??row.original.feature}/>},{id:'protein',header:'Protein change',cell:({row})=><Val value={row.original.hgvsp}/>},{id:'consequence',header:'Consequence',cell:({row})=>label(row.original.consequence)},{id:'selection',header:'Association',cell:({row})=><>{label(row.original.selection_method)}<small>{label(row.original.mapping_status)}</small></>},{id:'details',header:'Source annotation',cell:({row})=><Disclosure title="Details"><Fields items={[{label:'HGVS c.',value:row.original.hgvsc},{label:'Protein identifier',value:row.original.protein_id}]}/><DetailFields items={row.original.fields}/></Disclosure>}]}/></Disclosure>}
 <h3>Computational predictions</h3><p className="small muted">Scores retain their source scales and direction. They are computational evidence; values from different predictors are not directly interchangeable.</p>
 {Array.isArray(d.prediction_groups)&&d.prediction_groups.map((group,index)=>{const g=group as RecordData;return <Disclosure key={index} title={display(g.name)} open={false}><div className="prediction-grid">{Array.isArray(g.items)&&g.items.map((item,i)=>{const p=item as RecordData;return <div className="prediction-detail" key={i}><Prediction item={p}/><small>{display(p.field)}</small><span>{label(p.scope)}{p.transcript_id?` · ${display(p.transcript_id)}`:''}</span>{p.status&&p.status!=='available'?<small className="muted">{label(p.status)}</small>:null}</div>;})}</div></Disclosure>;})}
 <Disclosure title="Population allele frequency"><Fields items={[{label:'Allele frequency',value:frequencies.af===null?'Not available':number(frequencies.af,6)},{label:'Allele count',value:frequencies.ac},{label:'Allele number',value:frequencies.an},{label:'Status',value:label(frequencies.status)},{label:'Source',value:frequencies.source},{label:'Source filters',value:frequencies.filters}]}/>{Array.isArray(frequencies.populations)&&<DataTable items={frequencies.populations as RecordData[]} columns={[{id:'population',header:'Population',cell:({row})=>display(row.original.population??row.original.label??row.original.name)},{accessorKey:'af',header:'AF',cell:({getValue})=>number(getValue(),6)},{accessorKey:'ac',header:'AC',cell:({getValue})=>number(getValue())},{accessorKey:'an',header:'AN',cell:({getValue})=>number(getValue())}]}/>}<p className="small muted">An allele frequency of 0 is distinct from an unavailable measurement.</p></Disclosure>
 {Array.isArray(d.sources)&&<SourceEvidence sources={d.sources as RecordData[]} hasMore={d.sources_has_more===true}/>}
 <Disclosure title="Protein stability (ΔΔG)">{Array.isArray(d.ddg)&&d.ddg.length?<DataTable items={d.ddg as RecordData[]} columns={[{id:'method',header:'Method',cell:({row})=>display(row.original.model)},{id:'value',header:'ΔΔG',cell:({row})=><>{number(row.original.ddg_pred)} <span className="muted small">{row.original.unit?display(row.original.unit):'Unit not provided'}</span></>},{id:'substitution',header:'Substitution',cell:({row})=><>{display(row.original.ref_aa)}{display(row.original.position)}{display(row.original.alt_aa)}</>},{id:'object',header:'Sequence / structure',cell:({row})=><Val value={row.original.sequence_id??row.original.structure_id}/>}]}/>:<p className="muted">No ΔΔG value is available for this variant.</p>}{Array.isArray(d.ddg)&&<DdgConventions rows={d.ddg as RecordData[]}/>}
 {Array.isArray(d.ddg_status)&&d.ddg_status.map((s,i)=><Fields key={i} items={[{label:'Sequence',value:s.sequence_id},{label:'Sequence status',value:label(s.sequence_status)},{label:'Prediction status',value:label(s.prediction_status)}]}/>)}</Disclosure>
 </>}</Status></Modal>;
}
export function Variants({accession}:{accession:string}){
 const {query,filters,change,pager}=useListing(accession,'variants',['source','consequence']);const [selected,setSelected]=useState<string|null>(null);
 const columns:ColumnDef<RecordData>[]=[{id:'variant',header:'Variant',cell:({row})=><button className="text-button" onClick={()=>setSelected(String(row.original.variant_id))}>{display(row.original.hgvsp??row.original.variant_id)}<ArrowUpRight size={13}/></button>},{id:'consequence',header:'Type',cell:({row})=><span className="consequence">{label(row.original.consequence)}</span>},{id:'coordinate',header:'GRCh38',cell:({row})=><div className="small mono">{display(row.original.chromosome)}:{display(row.original.position)}<small>{display(row.original.ref)} → {display(row.original.alt)}</small></div>},{id:'source',header:'Sources',cell:({row})=><div className="badge-list">{(row.original.source_names as string[]??[]).map(s=><Badge key={s}>{s}</Badge>)}</div>},{id:'frequency',header:'Allele frequency',cell:({row})=>{const f=row.original.frequency as RecordData|undefined;return <span title={label(f?.status)}>{number(f?.af,6)}</span>;}},{id:'prediction',header:'Selected predictions',cell:({row})=><div className="prediction-row">{(row.original.predictions as RecordData[]??[]).slice(0,3).map((p,i)=><Prediction item={p} key={i}/>)}</div>}];
 return <Panel id="variants" title="Variant catalog" subtitle="Filter by source and consequence; open a variant for predictions and evidence" color="purple" icon={<Dna/>}><div className="toolbar"><SlidersHorizontal size={17}/><SelectFilter label="Source" value={filters.source} onChange={v=>change('source',v)} options={query.data?.filters?.sources}/><SelectFilter label="Variant type" value={filters.consequence} onChange={v=>change('consequence',v)} options={query.data?.filters?.consequences}/></div><Status loading={query.isPending} error={query.error} empty={!query.data?.items.length}><DataTable items={query.data?.items??[]} columns={columns}/></Status><Pager {...pager}/><p className="scope-note">Coordinates use GRCh38. Transcript annotations retain their association status; a gene relationship alone does not establish a canonical protein match. Open details to compare prediction categories.</p>{selected&&<VariantDetail id={selected} accession={accession} onClose={()=>setSelected(null)}/>}</Panel>;
}
function PpiDetail({id,accession,onClose}:{id:string;accession:string;onClose:()=>void}){
 const query=useQuery({queryKey:['ppi-detail',id,accession],queryFn:({signal})=>api<RecordData>(`/ppi/${encodeURIComponent(id)}?${params({accession})}`,signal)});const d=query.data;
 return <Modal title="Interaction evidence" onClose={onClose}><Status loading={query.isPending} error={query.error}>{d&&<><Fields items={[{label:'Source',value:d.source},{label:'Interaction type',value:d.interaction_type},{label:'Detection method',value:d.detection_method},{label:'Contexts',value:d.contexts},{label:'Coordinate mapping',value:label(d.coordinate_status)}]}/><h3>Participants</h3>{Array.isArray(d.participants)&&d.participants.map((p,i)=><div className="annotation" key={i}><Fields items={[{label:'Participant',value:p.name??p.identifier},{label:'Identifier',value:p.identifier??p.accession},{label:'Object',value:p.object_type},{label:'Organism',value:p.taxon},{label:'Evidence direction',value:d.negative?'Negative interaction evidence':undefined}]}/>{Array.isArray(p.fields)&&p.fields.length>0&&<Disclosure title="Participant roles & source features"><DetailFields items={p.fields}/></Disclosure>}</div>)}<Disclosure title="Source details" open><DetailFields items={d.fields}/></Disclosure>{Array.isArray(d.publications)&&d.publications.length>0&&<><h3>Publications</h3><div className="badge-list">{d.publications.map((p,i)=><LinkOut key={i} href={p.url}>{display(p.id)}</LinkOut>)}</div></>}</>}</Status></Modal>;
}
export function Interactions({accession}:{accession:string}){
 const {query,filters,change,pager}=useListing(accession,'ppi',['source','interaction_type']);const [selected,setSelected]=useState<string|null>(null);
 const columns:ColumnDef<RecordData>[]=[{id:'partners',header:'Partner / participant',cell:({row})=><div>{(row.original.partners as RecordData[]??[]).map((p,i)=><div className="partner" key={i}>{p.accession?p.project_entry?<Link to={`/protein/${p.accession}`}>{display(p.name??p.accession)}</Link>:<LinkOut href={`https://www.uniprot.org/uniprotkb/${p.accession}`}>{display(p.name??p.accession)}</LinkOut>:<strong>{display(p.name??p.identifier)}</strong>}<small>{p.accession?display(p.accession):display(p.object_type)}{p.taxon?` · taxon ${display(p.taxon)}`:''}</small></div>)}</div>},{accessorKey:'interaction_type',header:'Interaction category',cell:({getValue})=>label(getValue())},{accessorKey:'source',header:'Source',cell:({getValue})=><Badge>{display(getValue())}</Badge>},{accessorKey:'detection_method',header:'Method',cell:({getValue})=><Val value={getValue()}/>},{id:'evidence',header:'Evidence',cell:({row})=><>{row.original.negative?<Badge tone="amber">Negative evidence</Badge>:null}{row.original.non_protein_participant?<Badge tone="amber">Non-protein participant</Badge>:null}<button className="text-button" onClick={()=>setSelected(String(row.original.record_id))}>View evidence<ArrowUpRight size={13}/></button></>}];
 return <Panel id="interactions" title="Protein interactions" subtitle="Source-defined interaction categories and participant-level evidence" icon={<Network/>} color="teal"><div className="toolbar"><SlidersHorizontal size={17}/><SelectFilter label="Source" value={filters.source} onChange={v=>change('source',v,['interaction_type'])} options={query.data?.filters?.sources}/><SelectFilter label="Interaction category" value={filters.interaction_type} onChange={v=>change('interaction_type',v)} options={query.data?.filters?.interaction_types}/></div><Status loading={query.isPending} error={query.error} empty={!query.data?.items.length}><DataTable items={query.data?.items??[]} columns={columns}/></Status><Pager {...pager}/><p className="scope-note">Source categories are preserved. Functional associations, physical interactions and experimental records carry different evidence; repeated records are not independent confirmations.</p>{selected&&<PpiDetail id={selected} accession={accession} onClose={()=>setSelected(null)}/>}</Panel>;
}
function RowDetails({row,onClose,title}:{row:RecordData;onClose:()=>void;title:string}){return <Modal title={title} onClose={onClose}><Fields items={[{label:'Source',value:row.source},{label:'Context',value:row.context??row.tissue},{label:'Category',value:row.category??row.qtl_type},{label:'Phenotype / molecular event',value:row.phenotype},{label:'Chromosome',value:row.chromosome},{label:'Position',value:row.position},{label:'Assembly',value:row.assembly},{label:'Measurement',value:row.measurement},{label:'Value',value:row.value},{label:'Unit',value:row.unit},{label:'Effect measure',value:row.effect_type},{label:'Effect',value:row.effect},{label:'P value',value:row.pvalue}]}/><DetailFields items={row.details}/></Modal>;}
export function Expression({accession}:{accession:string}){
 const {query,filters,change,pager}=useListing(accession,'expression',['source','category'],{category:'normal'});const [selected,setSelected]=useState<RecordData|null>(null);
 const columns:ColumnDef<RecordData>[]=[{accessorKey:'context',header:'Tissue / cell context',cell:({getValue})=><strong>{display(getValue())}</strong>},{accessorKey:'category',header:'Category',cell:({getValue})=>label(getValue())},{accessorKey:'measurement',header:'Measurement',cell:({getValue})=>label(getValue())},{id:'value',header:'Value',cell:({row})=><>{typeof row.original.value==='number'?number(row.original.value):<Val value={row.original.value}/>} <span className="muted small">{row.original.unit?display(row.original.unit):''}</span></>},{accessorKey:'source',header:'Source',cell:({getValue})=><Badge>{display(getValue())}</Badge>},{id:'details',header:'Details',cell:({row})=><button className="text-button" onClick={()=>setSelected(row.original)}>View<ArrowUpRight size={13}/></button>}];
 return <Panel id="expression" title="Expression" subtitle="Tissue and cell context, with source-specific measurements" icon={<Activity/>} color="green"><div className="toolbar"><SelectFilter label="Source" value={filters.source} onChange={v=>change('source',v)} options={query.data?.filters?.sources}/><SelectFilter label="Context category" allowAll={false} value={filters.category} onChange={v=>change('category',v,['source'])} options={query.data?.filters?.categories??['normal','cancer','cell_line','single_cell']}/></div><Status loading={query.isPending} error={query.error} empty={!query.data?.items.length}><DataTable items={query.data?.items??[]} columns={columns}/></Status><Pager {...pager}/><p className="scope-note">RNA expression and protein abundance remain separate measurements. Compare values only within the same measurement and unit; gene-level data are not isoform-specific.</p>{selected&&<RowDetails title={display(selected.context)} row={selected} onClose={()=>setSelected(null)}/>}</Panel>;
}
export function Qtl({accession}:{accession:string}){
 const {query,filters,change,pager}=useListing(accession,'qtl',['source','tissue','qtl_type'],{source:'GTEx'});const [selected,setSelected]=useState<RecordData|null>(null);
 const columns:ColumnDef<RecordData>[]=[{accessorKey:'variant',header:'Variant',cell:({getValue})=><span className="mono small">{display(getValue())}</span>},{accessorKey:'tissue',header:'Tissue / context',cell:({getValue})=><Val value={getValue()}/>},{accessorKey:'qtl_type',header:'QTL type',cell:({getValue})=><Badge>{display(getValue())}</Badge>},{accessorKey:'pvalue',header:'P value',cell:({getValue})=>typeof getValue()==='string'?display(getValue()):number(getValue(),5)},{id:'effect',header:'Effect',cell:({row})=><>{number(row.original.effect)}<small>{label(row.original.effect_type)}</small></>},{accessorKey:'assembly',header:'Assembly',cell:({getValue})=><Val value={getValue()}/>},{id:'details',header:'Details',cell:({row})=><button className="text-button" onClick={()=>setSelected(row.original)}>View<ArrowUpRight size={13}/></button>}];
 return <Panel id="qtl" title="Regulatory associations" subtitle="QTL evidence organized by source, tissue and molecular phenotype" icon={<SlidersHorizontal/>} color="amber"><div className="toolbar"><SelectFilter label="Source" allowAll={false} value={filters.source} onChange={v=>change('source',v,['tissue','qtl_type'])} options={query.data?.filters?.sources??['GTEx','eQTLGen','QTLbase']}/><SelectFilter label="Tissue" value={filters.tissue} onChange={v=>change('tissue',v)} options={query.data?.filters?.tissues}/><SelectFilter label="QTL type" value={filters.qtl_type} onChange={v=>change('qtl_type',v)} options={query.data?.filters?.qtl_types}/></div><Status loading={query.isPending} error={query.error} empty={!query.data?.items.length}><DataTable items={query.data?.items??[]} columns={columns}/></Status><Pager {...pager}/><p className="scope-note">QTL evidence is associated at the gene or source phenotype level. It does not imply a protein-level causal effect; assemblies and effect measures retain their source definitions.</p>{selected&&<RowDetails title={display(selected.variant)} row={selected} onClose={()=>setSelected(null)}/>}</Panel>;
}
function DiseaseDetail({id,accession,onClose}:{id:string;accession:string;onClose:()=>void}){
 const [cursors,setCursors]=useState<(string|null)[]>([null]);const [page,setPage]=useState(0);const query=useQuery({queryKey:['disease-detail',id,accession,cursors[page]],queryFn:({signal})=>api<RecordData>(`/diseases/${encodeURIComponent(id)}?${params({accession,cursor:cursors[page],limit:20})}`,signal)});const d=query.data;const disease=(d?.disease??{}) as RecordData;
 return <Modal title={display(disease.name??id)} onClose={onClose}><Status loading={query.isPending} error={query.error}>{d&&<><p>{display(disease.definition)}</p><LinkOut href={disease.source_url}>{display(disease.disease_id??id)}</LinkOut><h3>Gene–disease evidence</h3>{Array.isArray(d.evidence)&&d.evidence.map((e,i)=><div className="annotation" key={i}><Fields items={[{label:'Source',value:e.source},{label:'Classification',value:e.classification},{label:'Inheritance',value:e.inheritance},{label:'Relationship',value:label(e.relationship_status)},{label:'Submitter',value:e.submitter},{label:'References',value:e.references}]}/>{e.report_url?<LinkOut href={e.report_url}>Source report</LinkOut>:null}</div>)}{d.evidence_has_more===true&&<p className="small muted">The first 100 gene–disease source records are shown. Consult the source reports for further assertions.</p>}<h3>Associated phenotypes</h3>{Array.isArray(d.phenotypes)&&d.phenotypes.length?<DataTable items={d.phenotypes as RecordData[]} columns={[{accessorKey:'name',header:'Phenotype',cell:({row})=><LinkOut href={`https://hpo.jax.org/app/browse/term/${row.original.resolved_hpo_id??row.original.hpo_id}`}>{display(row.original.name)}</LinkOut>},{accessorKey:'hpo_id',header:'HPO ID'},{accessorKey:'qualifier',header:'Qualifier',cell:({getValue})=><Val value={getValue()}/>},{accessorKey:'frequency',header:'Frequency',cell:({getValue})=><Val value={getValue()}/>},{id:'evidence',header:'Details',cell:({row})=><Disclosure title="Source evidence"><Fields items={[{label:'Evidence',value:row.original.evidence},{label:'Reference',value:row.original.reference},{label:'Onset',value:row.original.onset},{label:'Sex',value:row.original.sex}]}/></Disclosure>}]} />:<p className="muted">No phenotype record is available.</p>}<Pager page={page} count={Array.isArray(d.phenotypes)?d.phenotypes.length:0} next={d.next_cursor as string|null} onPrevious={()=>setPage(p=>Math.max(0,p-1))} onNext={()=>{if(d.next_cursor){setCursors([...cursors.slice(0,page+1),String(d.next_cursor)]);setPage(page+1);}}}/></>}</Status></Modal>;
}
export function Diseases({accession}:{accession:string}){
 const {query,filters,change,pager}=useListing(accession,'diseases',['source']);const [selected,setSelected]=useState<string|null>(null);
 const columns:ColumnDef<RecordData>[]=[{id:'name',header:'Disease',cell:({row})=><button className="text-button" onClick={()=>setSelected(String(row.original.disease_id))}>{display(row.original.name)}<ArrowUpRight size={13}/></button>},{accessorKey:'source',header:'Source',cell:({getValue})=><Badge>{display(getValue())}</Badge>},{accessorKey:'classification',header:'Evidence classification',cell:({getValue})=><Val value={getValue()}/>},{accessorKey:'inheritance',header:'Inheritance',cell:({getValue})=><Val value={getValue()}/>},{accessorKey:'relationship_status',header:'Relationship',cell:({getValue})=>label(getValue())}];
 return <Panel id="diseases" title="Diseases & phenotypes" subtitle="Gene–disease relationships and source-defined clinical evidence" icon={<HeartPulse/>} color="rose"><div className="toolbar"><SelectFilter label="Source" value={filters.source} onChange={v=>change('source',v)} options={query.data?.filters?.sources}/></div><Status loading={query.isPending} error={query.error} empty={!query.data?.items.length}><DataTable items={query.data?.items??[]} columns={columns}/></Status><Pager {...pager}/>{Boolean(query.data?.gene_dosage?.length)&&<Disclosure title="Gene dosage sensitivity · ClinGen">{query.data?.gene_dosage?.map((d,i)=><div className="annotation" key={i}><Fields items={[{label:'Gene',value:d.gene_symbol},{label:'Haploinsufficiency',value:d.haploinsufficiency},{label:'Triplosensitivity',value:d.triplosensitivity}]}/><LinkOut href={d.report_url}>ClinGen report</LinkOut></div>)}<p className="small muted">Dosage evidence applies to the gene, not to every individual variant.</p></Disclosure>}<p className="scope-note">Gene–disease evidence and disease-associated phenotypes are context. They do not assign a clinical classification to an individual variant.</p>{selected&&<DiseaseDetail id={selected} accession={accession} onClose={()=>setSelected(null)}/>}</Panel>;
}
