import { useEffect, useMemo, useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ExternalLink, Layers, Palette, ScanLine } from 'lucide-react';
import { api } from '../api';
import { HelpButton } from './HelpGuide';
import { Modal } from './ui';
import { Checkbox } from './ui/checkbox';
import { ModeToggleGroup } from './ui/mode-toggle-group';
import { ContentTransition } from '../lib/motion';
import {
  annotationSourceGuide, featureStyle, isMembraneFeature, jsdScoreColor,
  missingAnnotationColor, sequenceLensLabels, sequencePtmPresenceColor, variantCountBins, variantCountColorNote, variantFill, variantTextColor,
  type AnnotationSourceOptions, type Feature, type Score, type Track, type VariantSummary,
} from './sequence-model';
import './full-sequence-atlas.css';

type Coverage = {predictor:{field:string;label:string};sites:{position:number;variant_count:number;scored_variant_count:number}[];note?:string};
const lenses=[
  {id:'variants',name:sequenceLensLabels.variants,description:'Distinct DNA variants with verified canonical positions; counts are not population frequencies.'},
  {id:'predictions',name:'Predictor coverage',description:'Mapped DNA variants with a score from the selected predictor; coverage is not pathogenicity.'},
  {id:'ptm',name:sequenceLensLabels.ptm,description:'PTM type colours; stripes indicate multiple types. Grey means no annotation from the selected sources.'},
  {id:'secondary',name:'Secondary structure',description:'Source-annotated helices, beta strands and turns; grey means no annotation.'},
  {id:'jsd',name:sequenceLensLabels.jsd,description:'Original JSD conservation values, 0–1. Grey is missing, not zero.'},
];
const clinical=[{key:'pathogenic',label:'Pathogenic / likely pathogenic',color:'#ef4444'},{key:'uncertain',label:'VUS',color:'#f59e0b'},{key:'benign',label:'Benign / likely benign',color:'#10b981'},{key:'conflicting',label:'Conflicting',color:'#a855f7'},{key:'other',label:'Other labels',color:'#38bdf8'},{key:'unclassified',label:'Unclassified',color:'#cbd5e1'}] as const;
const predictors=[{field:'AlphaMissense_score',label:'AlphaMissense'},{field:'REVEL_score',label:'REVEL'},{field:'SIFT_score',label:'SIFT'}];
const PTM_MARKER=sequencePtmPresenceColor;
function multiColour(colours:string[],alpha=''){return colours.length===1?colours[0]+alpha:`linear-gradient(135deg,${colours.map((colour,index)=>`${colour}${alpha} ${index/colours.length*100}%,${colour}${alpha} ${(index+1)/colours.length*100}%`).join(',')})`;}

export function FullSequence({accession,sequence,tracks,scores,summary,sourceOptions,selected,searchMatches=[],onSelect}:{accession:string;sequence:string;tracks:Track[];scores:Score[];summary?:VariantSummary;sourceOptions?:AnnotationSourceOptions;selected?:number|null;searchMatches?:number[];onSelect:(position:number,lens:string,predictor:string,ptmSource:string,ptmType:string)=>void}) {
  const [lens,setLens]=useState('variants');
  const [predictor,setPredictor]=useState('AlphaMissense_score');
  const [variantMode,setVariantMode]=useState('count');
  const [selectedPtmSources,setSelectedPtmSources]=useState<string[]|null>(null);
  const [ptmType,setPtmType]=useState('all');
  const [ptmSummaryOpen,setPtmSummaryOpen]=useState(false);
  const [ptmSummaryCloseRequested,setPtmSummaryCloseRequested]=useState(false);
  const [hover,setHover]=useState<number|null>(null);
  const [focusPosition,setFocusPosition]=useState(1);
  const container=useRef<HTMLDivElement>(null);
  const [autoWidth,setAutoWidth]=useState(50);
  const [density,setDensity]=useState(0);
  const rowWidth=density?Math.min(density,autoWidth):autoWidth;
  const matchSet=useMemo(()=>new Set(searchMatches),[searchMatches]);
  const scrollAnchor=useRef<number|null>(null);
  useEffect(()=>{if(scrollAnchor.current==null)return;const target=container.current?.querySelector<HTMLElement>(`[data-residue="${scrollAnchor.current}"]`);const scroller=container.current?.querySelector<HTMLElement>('.atlas-sequence-scroll');if(target&&scroller)scroller.scrollTop+=target.getBoundingClientRect().top-scroller.getBoundingClientRect().top-scroller.clientHeight/2;scrollAnchor.current=null;},[rowWidth]);
  useEffect(()=>{const target=container.current;if(!target)return;const observer=new ResizeObserver(entries=>{const width=entries[0].contentRect.width;setAutoWidth([50,40,30,25,20,10,5].find(columns=>columns*22+66<=width)??5);});observer.observe(target);return()=>observer.disconnect();},[]);
  useEffect(()=>{setSelectedPtmSources(null);setPtmType('all');setPtmSummaryOpen(false);setPtmSummaryCloseRequested(false);setFocusPosition(1);setHover(null);},[accession]);
  const prediction=useQuery<Coverage>({queryKey:['atlas-prediction-coverage',accession,predictor],enabled:lens==='predictions',queryFn:({signal})=>api(`/proteins/${accession}/sequence/prediction-coverage?predictor=${encodeURIComponent(predictor)}`,signal)});
  const scoreMap=useMemo(()=>new Map(scores.map(score=>[score.position,score.value])),[scores]);
  const sites=useMemo(()=>new Map((summary?.canonical_sites??[]).map(site=>[site.position,site])),[summary]);
  const coverage=useMemo(()=>new Map((prediction.data?.sites??[]).map(site=>[site.position,site])),[prediction.data]);
  const allPtmFeatures=useMemo(()=>tracks.find(track=>track.id==='ptm')?.features??[],[tracks]);
  const fallbackSources=useMemo(()=>Array.from(new Set(allPtmFeatures.map(feature=>feature.source??'Unknown'))).sort(),[allPtmFeatures]);
  const ptmSourceOptions=useMemo(()=>sourceOptions?.ptm??fallbackSources.map(source=>({id:source,label:source,source,kind:'source_annotation',available:true,count:allPtmFeatures.filter(feature=>feature.source===source).length})),[sourceOptions,allPtmFeatures,fallbackSources]);
  const availableSources=useMemo(()=>ptmSourceOptions.filter(option=>option.available!==false).map(option=>option.id),[ptmSourceOptions]);
  const activePtmSources=useMemo(()=>selectedPtmSources??availableSources,[selectedPtmSources,availableSources]);
  const ptmFeatures=useMemo(()=>allPtmFeatures.filter(feature=>activePtmSources.includes(feature.source??'Unknown')),[allPtmFeatures,activePtmSources]);
  const ptmTypes=useMemo(()=>{const byType=new Map<string,{name:string;color:string;positions:Set<number>}>();for(const feature of ptmFeatures){const style=featureStyle(feature,'ptm'),entry=byType.get(style.name)??{...style,positions:new Set<number>()};entry.positions.add(feature.start);byType.set(style.name,entry);}return [...byType.values()].sort((a,b)=>b.positions.size-a.positions.size||a.name.localeCompare(b.name));},[ptmFeatures]);
  useEffect(()=>{if(ptmType!=='all'&&!ptmTypes.some(type=>type.name===ptmType))setPtmType('all');},[ptmType,ptmTypes]);
  const ptmStats=useMemo(()=>{const positions=new Set<number>(),positionTypes=new Set<string>(),linkedRecords=new Set<string>();let annotationsWithoutRecordIds=0;const sources=new Map<string,{positions:Set<number>;records:Set<string>}>();for(const feature of ptmFeatures){const source=feature.source??'Unknown',style=featureStyle(feature,'ptm'),sourceStat=sources.get(source)??{positions:new Set<number>(),records:new Set<string>()};positions.add(feature.start);positionTypes.add(`${feature.start}:${style.name}`);sourceStat.positions.add(feature.start);if(feature.record_ids?.length){for(const id of feature.record_ids){const key=`${source}:${id}`;linkedRecords.add(key);sourceStat.records.add(key);}}else annotationsWithoutRecordIds++;sources.set(source,sourceStat);}return {positions:positions.size,positionTypes:positionTypes.size,records:linkedRecords.size,annotationsWithoutRecordIds,sources:[...sources].map(([source,value])=>({source,positions:value.positions.size,records:value.records.size}))};},[ptmFeatures]);
  const index=useMemo(()=>{const values:{ptm:Feature[];domain?:Feature;membrane?:Feature;secondary:Feature[]}[]=Array.from({length:sequence.length},()=>({ptm:[],secondary:[]}));for(const track of tracks)for(const feature of track.features){for(let position=Math.max(1,feature.start);position<=Math.min(sequence.length,feature.end);position++){if(track.id==='ptm'&&activePtmSources.includes(feature.source??'Unknown'))values[position-1].ptm.push(feature);else if(track.id==='domains'&&(/domain/i.test(feature.source_type??'')||feature.source==='Pfam'))values[position-1].domain??=feature;else if(track.id==='membrane'&&isMembraneFeature(feature))values[position-1].membrane??=feature;else if(track.id==='secondary')values[position-1].secondary.push(feature);}}return values;},[tracks,sequence.length,activePtmSources]);
  const tile=(position:number)=>{const info=index[position-1],score=scoreMap.get(position),site=sites.get(position),typeColours=Array.from(new Set(info.ptm.filter(feature=>ptmType==='all'||featureStyle(feature,'ptm').name===ptmType).map(feature=>featureStyle(feature,'ptm').color)));if(lens==='variants'&&summary){if(variantMode==='clinical'&&site?.variant_count){const labels=clinical.filter(category=>(site.clinical_counts?.[category.key]??0)>0);return {background:labels.length?multiColour(labels.map(category=>category.color),'88'):'#e2e8f0',color:'#172a3a'};}const count=site?.variant_count??0;return {background:variantFill(count),color:variantTextColor(count)};}if(lens==='predictions'&&prediction.data){const count=coverage.get(position)?.scored_variant_count??0;return {background:variantFill(count),color:variantTextColor(count)};}if(lens==='ptm'&&typeColours.length)return {background:multiColour(typeColours,'66'),color:'#172a3a'};if(lens==='secondary'&&info.secondary.length)return {background:multiColour(Array.from(new Set(info.secondary.map(feature=>featureStyle(feature,'secondary').color))),'66'),color:'#172a3a'};if(lens==='jsd'&&score!=null)return {background:jsdScoreColor(score),color:score>.915?'#ffffff':'#05010a'};return {background:missingAnnotationColor,color:'#172a3a'};};
  const describe=(position:number)=>{const info=index[position-1],score=scoreMap.get(position),site=sites.get(position),types=Array.from(new Set(info.ptm.map(feature=>featureStyle(feature,'ptm').name))),prefix=`${sequence[position-1]}${position}`;if(lens==='predictions')return `${prefix} · ${predictors.find(item=>item.field===predictor)?.label}: ${prediction.data?`${coverage.get(position)?.scored_variant_count??0} of ${coverage.get(position)?.variant_count??0} mapped variants with scores`:'coverage unavailable'}`;if(lens==='ptm')return `${prefix} · ${types.length?types.join(', '):'No mapped PTM'}${info.ptm.length?` · ${Array.from(new Set(info.ptm.map(feature=>feature.source))).join(', ')}`:''}`;if(lens==='secondary')return `${prefix} · ${info.secondary.length?info.secondary.map(feature=>`${featureStyle(feature,'secondary').name} ${feature.start}–${feature.end}`).join('; '):'No secondary structure annotation'}`;if(lens==='jsd')return `${prefix} · JSD ${score==null?'unavailable':score.toFixed(4)}`;return `${prefix} · ${summary?`${site?.variant_count??0} mapped DNA variants`:'variant summary unavailable'}${variantMode==='clinical'&&site?` · ${clinical.filter(category=>site.clinical_counts?.[category.key]).map(category=>`${category.label}: ${site.clinical_counts?.[category.key]}`).join(', ')}`:''}`;};
  const countLegend=<>{variantCountBins.map(bin=><span key={bin.label}><i style={{background:bin.color,border:bin.minimum===0?'1px solid var(--slate-7)':undefined}}/>{bin.label}</span>)}<span>{lens==='predictions'?'DNA variants with a score':'Mapped DNA variants'} per residue</span></>;
  const toggleSource=(id:string)=>setSelectedPtmSources(current=>{const active=current??availableSources;return active.includes(id)?active.filter(source=>source!==id):[...active,id];});
  const hoveredPtm=hover?Array.from(new Set(index[hover-1].ptm.map(feature=>`${featureStyle(feature,'ptm').name}${feature.source?` (${feature.source})`:''}`))):[];
  const evidenceSource=activePtmSources.length===1?activePtmSources[0]:'all';
  return <div className="full-sequence atlas-v3" ref={container}>
    <div className="atlas-subheading"><ScanLine size={20}/><h3>Full sequence atlas <HelpButton topic="sequence"/></h3><span>{sequence.length.toLocaleString()} residues · {rowWidth} per row</span></div>
    <ModeToggleGroup className="atlas-lenses" aria-label="Atlas visualization mode" value={lens} onValueChange={value=>{setLens(value);setHover(null);}} options={lenses.map(item=>({value:item.id,label:item.name}))}/>
    <ContentTransition transitionKey={`${lens}:${variantMode}:${predictor}`}>
    <div className="atlas-mode-controls">{lens==='variants'&&<label>Colour by <select aria-label="Atlas variant colouring" value={variantMode} onChange={event=>setVariantMode(event.target.value)}><option value="count">Mapped variant count</option><option value="clinical">ClinVar label groups</option></select></label>}{lens==='predictions'&&<label>Predictor <select aria-label="Atlas predictor" value={predictor} onChange={event=>setPredictor(event.target.value)}>{predictors.map(item=><option key={item.field} value={item.field}>{item.label}</option>)}</select></label>}</div>
    {lens==='ptm'&&<div className="atlas-source-entry"><div><strong>PTM sources</strong><span>Source layers · 0 = no mapped record; — = count unavailable.</span></div><div className="atlas-source-options">{ptmSourceOptions.map(option=>{const guide=annotationSourceGuide(option.source,option.kind);return <label key={option.id} title={guide.description}><Checkbox checked={activePtmSources.includes(option.id)} disabled={option.available===false} onCheckedChange={()=>toggleSource(option.id)} aria-label={`Atlas PTM source: ${option.label}`}/><span>{option.label}</span><small>{typeof option.count==='number'?option.count.toLocaleString():'—'}</small></label>;})}</div><HelpButton title="PTM source guide" label="About sources">{ptmSourceOptions.map(option=>{const guide=annotationSourceGuide(option.source,option.kind);return <p key={option.id}><strong>{option.label}</strong> · {guide.description} {guide.url&&<a href={guide.url} target="_blank" rel="noreferrer">Source <ExternalLink size={13}/></a>}</p>;})}</HelpButton></div>}
    <div className="atlas-legend-group"><div className="atlas-legend-heading"><Palette size={15}/><strong>Tile colour</strong><span>{lenses.find(item=>item.id===lens)?.name}</span></div><div className="atlas-colour-key">{lens==='variants'?(variantMode==='count'?countLegend:<>{clinical.map(category=><span key={category.key}><i style={{background:category.color+'88'}}/>{category.label}</span>)}<span><i style={{background:'#fff',border:'1px solid var(--slate-7)'}}/>0 mapped variants</span></>):lens==='predictions'?countLegend:lens==='jsd'?<><span><i className="atlas-gradient"/>JSD 0 → 1</span><span><i style={{background:missingAnnotationColor}}/>No score</span></>:lens==='secondary'?<>{['Helix','Beta strand','Turn / loop'].map(name=><span key={name}><i style={{background:featureStyle({start:1,end:1,label:name},'secondary').color+'66'}}/>{name}</span>)}<span><i style={{background:missingAnnotationColor}}/>No annotation</span></>:<span><i style={{background:missingAnnotationColor}}/>No PTM annotation · type colours below</span>}</div><p className="atlas-mode-description">{lens==='variants'&&variantMode==='clinical'?'Stripes show multiple source label groups, not a combined classification.':lenses.find(item=>item.id===lens)?.description}{(lens==='variants'&&variantMode==='count'||lens==='predictions')&&<> {variantCountColorNote}</>}</p></div>
    </ContentTransition>
    <div className="atlas-overlay-group"><div className="atlas-legend-heading"><Layers size={15}/><strong>Boundaries & markers</strong><span>Independent of tile colour</span></div><div className="atlas-ptm-key" aria-label="PTM legend and summary"><button className="atlas-ptm-summary-trigger" onClick={()=>setPtmSummaryOpen(true)}><i style={{background:PTM_MARKER}}/>PTM summary<small>{ptmStats.positions} mapped sites</small></button>{lens==='ptm'&&<button aria-pressed={ptmType==='all'} onClick={()=>setPtmType('all')}>All PTM types</button>}{lens==='ptm'&&ptmTypes.map(type=><button key={type.name} aria-pressed={ptmType===type.name} onClick={()=>setPtmType(ptmType===type.name?'all':type.name)}><i style={{background:type.color}}/>{type.name}<small>{type.positions.size} sites</small></button>)}</div>
    <div className="atlas-boundary-key"><span><i className="domain-key"/>Domain border</span><span><i className="membrane-key"/>Membrane border</span><span><i className="atlas-ptm-summary-dot"/>PTM site · types in PTM mode</span><span><i className="atlas-selection-key"/>Selected residue</span></div></div>
    {lens==='variants'&&!summary&&<p role="status" className="atlas-explainer">Mapped variant counts are not available yet.</p>}{lens==='predictions'&&prediction.isPending&&<p role="status" className="atlas-explainer">Loading predictor coverage…</p>}{lens==='predictions'&&prediction.isError&&<p role="alert" className="atlas-explainer">Predictor coverage is unavailable. <button className="text-button" onClick={()=>prediction.refetch()}>Retry</button></p>}
    <div className="atlas-reading-controls"><label>Residues per row <select aria-label="Residues per row" value={density} onChange={event=>{scrollAnchor.current=selected??searchMatches[0]??focusPosition;setDensity(Number(event.target.value));}}><option value={0}>Auto · {autoWidth}</option><option value={25}>25 · enlarged</option><option value={50}>50 · compact</option></select></label><span>{searchMatches.length?`${searchMatches.length} search matches · amber outline`:'Arrow keys move between residues · Enter opens evidence'}</span>{selected&&<button className="text-button" onClick={()=>{const target=container.current?.querySelector<HTMLElement>(`[data-residue="${selected}"]`);target?.scrollIntoView({block:'center',behavior:'instant'});target?.focus({preventScroll:true});}}>Find selected {sequence[selected-1]}{selected}</button>}</div>
    <div className="atlas-position-preview" aria-live="polite">{hover?describe(hover):'Residue preview · hover or focus; select to open evidence.'}{lens!=='ptm'&&hoveredPtm.length>0&&<span className="atlas-preview-ptm"><i/>PTM · {hoveredPtm.join('; ')}</span>}</div>
    <div className="atlas-sequence-scroll" role="region" aria-label="Full amino acid sequence" tabIndex={0}><div className="atlas-sequence-rows">{Array.from({length:Math.ceil(sequence.length/rowWidth)},(_,row)=><div className="atlas-sequence-row" key={row}><span className="atlas-row-number">{row*rowWidth+1}</span><div className="atlas-amino-row" style={{gridTemplateColumns:`repeat(${rowWidth},minmax(0,1fr))`}}>{sequence.slice(row*rowWidth,(row+1)*rowWidth).split('').map((aa,indexInRow)=>{const position=row*rowWidth+indexInRow+1,info=index[position-1],types=Array.from(new Map(info.ptm.filter(feature=>ptmType==='all'||lens!=='ptm'||featureStyle(feature,'ptm').name===ptmType).map(feature=>{const style=featureStyle(feature,'ptm');return [style.name,style];})).values()),style=tile(position),markers=lens==='ptm'?types:(info.ptm.length?[{name:'PTM',color:PTM_MARKER}]:[]);return <button key={position} className={`atlas-amino ${selected===position?'selected':''} ${matchSet.has(position)?'search-match':''} ${searchMatches.length&&!matchSet.has(position)&&selected!==position?'search-context':''} ${info.domain?'has-domain':''} ${info.membrane?'has-membrane':''} ${lens==='ptm'&&ptmType!=='all'&&!types.length?'atlas-dimmed':''}`} style={{background:style.background,color:style.color,fontSize:density===25?'clamp(14px,2vw,26px)':undefined}} title={`${describe(position)}${types.length?` · PTM: ${types.map(type=>type.name).join(', ')}`:''}`} aria-label={`Residue ${describe(position)}${matchSet.has(position)?' · search match':''}${lens!=='ptm'&&types.length?` · PTM: ${types.map(type=>type.name).join(', ')}`:''}`} aria-pressed={selected===position} tabIndex={focusPosition===position?0:-1} onMouseEnter={()=>setHover(position)} onMouseLeave={event=>{if(document.activeElement!==event.currentTarget)setHover(null);}} onFocus={()=>{setHover(position);setFocusPosition(position);}} onBlur={()=>setHover(null)} onClick={()=>onSelect(position,lens,predictor,evidenceSource,ptmType)} onKeyDown={event=>{const delta=event.key==='ArrowRight'?1:event.key==='ArrowLeft'?-1:event.key==='ArrowDown'?rowWidth:event.key==='ArrowUp'?-rowWidth:0;const next=event.key==='Home'?(event.ctrlKey?1:row*rowWidth+1):event.key==='End'?(event.ctrlKey?sequence.length:Math.min(sequence.length,(row+1)*rowWidth)):position+delta;if(delta||event.key==='Home'||event.key==='End'){event.preventDefault();container.current?.querySelector<HTMLButtonElement>(`[data-residue="${Math.max(1,Math.min(sequence.length,next))}"]`)?.focus();}}} data-residue={position}><span>{aa}</span>{markers.length>0&&<span className={`atlas-ptm-dots ${lens==='ptm'?'is-typed':'is-summary'}`} aria-hidden="true">{markers.slice(0,markers.length>3?2:3).map(type=><i key={type.name} style={{background:type.color}}/>)}{lens==='ptm'&&markers.length>3&&<b>+</b>}</span>}</button>;})}</div><span className="atlas-row-number end">{Math.min(sequence.length,(row+1)*rowWidth)}</span></div>)}</div></div>
    <p className="atlas-explainer">Atlas filters are independent of the compact tracks. Missing annotations do not establish biological absence.</p>
    {ptmSummaryOpen&&<Modal title="PTM summary" closeRequested={ptmSummaryCloseRequested} onClose={()=>{setPtmSummaryOpen(false);if(ptmSummaryCloseRequested)setLens('ptm');setPtmSummaryCloseRequested(false);}}><div className="atlas-ptm-summary"><p>Counts use the currently checked PTM sources. Multiple sources at one residue contribute once to the mapped-site total.</p><div className="atlas-ptm-metrics"><div><strong>{ptmStats.positions}</strong><span>independent mapped positions</span></div><div><strong>{ptmStats.positionTypes}</strong><span>position × PTM type annotations</span></div><div><strong>{ptmStats.records}</strong><span>linked original source records</span></div></div><h4>By type</h4><div className="atlas-ptm-summary-list">{ptmTypes.map(type=><span key={type.name}><i style={{background:type.color}}/>{type.name}<strong>{type.positions.size}</strong></span>)}</div><h4>By source</h4><div className="atlas-ptm-summary-list">{ptmStats.sources.map(source=><span key={source.source}>{source.source}<small>{source.records} records</small><strong>{source.positions} sites</strong></span>)}</div>{ptmStats.annotationsWithoutRecordIds>0&&<p className="muted small">{ptmStats.annotationsWithoutRecordIds} displayed annotation groups do not expose a source record ID and are not included in the linked-record count.</p>}<button className="button" onClick={()=>setPtmSummaryCloseRequested(true)}>Open PTM type mode</button></div></Modal>}
  </div>;
}
