import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, ArrowUpRight, Database, Layers, Link2, Microscope } from 'lucide-react';
import { api, label, number, params, type RecordData } from '../api';
import { Badge, Disclosure, Fields, LinkOut, Pager, Status } from './ui';
import './membrane-topology.css';

export type TopologySegment={id:string;type:string;start:number;end:number;canonical_start:number|null;canonical_end:number|null;mapped_blocks:number|null;mapping_statuses:string[]|null};
export type TopologyRecord={source_sequence_id:string;record_id:string;source:string;native_id:string;chain_id:string|null;actual_length:number;feature_count:number;mapped_feature_count:number;experimental_regions:number;constraint_regions:number;structure_regions:number;methods:string[];constraint_sources:string[];reported_tm_counts:string[];reliability_values:string[];signal_region_reported:boolean;integrated_segments:TopologySegment[];mapping_note:string};
const sourceName=(source:string)=>source.replace('HTP/3D','HTP · structure benchmark').replace('HTP/experimental','HTP · experimental benchmark').replace('TmAlphaFold/cctop','TmAlphaFold · CCTOP').replace('TmAlphaFold/tmdet','TmAlphaFold · TmDet').replace('PDBTM/pdbtm_all','PDBTM · all chains').replace('PDBTM/pdbtm','PDBTM · subset');
const roles:Record<string,string>={integrated_topology:'Integrated topology',method_prediction:'Method predictions',constraint:'Source constraints',experimental_evidence:'Experimental / structure evidence',structure_region:'Structure regions'};
const segmentNames:Record<string,string>={S:'Signal peptide',Signal:'Signal peptide',O:'Outside',Outside:'Outside',I:'Inside',Inside:'Inside',M:'Membrane',Membrane:'Membrane'};
const segmentTone=(type:string)=>['M','Membrane'].includes(type)?'membrane':['S','Signal'].includes(type)?'signal':['O','Outside'].includes(type)?'outside':['I','Inside'].includes(type)?'inside':'other';
export function HtpPreview({records,onOpen}:{records:TopologyRecord[];onOpen:()=>void}){
 const candidates=records.filter(r=>r.source==='HTP');const record=candidates.find(r=>r.mapped_feature_count>0)??candidates[0];
 return <section className="mtp-htp-preview" aria-label="HTP topology preview"><div className="mov-preview-heading"><strong>HTP</strong><Badge tone="teal">Integrated topology</Badge><button onClick={onOpen}>View evidence<ArrowUpRight size={14}/></button></div><p>Source topology, method predictions and existing constraints.</p>{record?<><dl className="mtp-preview-values"><div><dt>Reported TM segments</dt><dd>{record.reported_tm_counts.join(' / ')||'Not supplied'}</dd></div><div><dt>HTP reliability</dt><dd>{record.reliability_values.join(' / ')||'Not supplied'}</dd></div><div><dt>Signal region</dt><dd>{record.signal_region_reported?'Reported':'Not reported'}</dd></div></dl><div className="mtp-preview-tags"><span>{record.methods.length} method outputs</span><span>{record.constraint_regions} constraint regions</span></div><small>{record.mapped_feature_count?'Source features mapped to canonical':'Source sequence only · not mapped to canonical'}{candidates.length>1?` · ${candidates.length} source records available`:''}. Reliability is the original source score.</small></>:<p className="mtp-empty">No HTP record is linked to this protein in the current collection.</p>}</section>;
}
export function TopologyPortrait({records,onOpen}:{records:TopologyRecord[];onOpen:(source:string)=>void}){
 const available=records.filter(r=>r.integrated_segments.length>0);const [selected,setSelected]=useState('');const record=available.find(r=>r.source_sequence_id===selected)??available.find(r=>r.source==='HTP'&&r.mapped_feature_count>0)??available[0];
 if(!record)return null;
 return <section className="mtp-portrait"><header><div><Layers size={17}/><strong>Topology at a glance</strong><span>Source sequence order · schematic, not to scale</span></div><label>Topology source<select aria-label="Topology portrait source" value={record.source_sequence_id} onChange={e=>setSelected(e.target.value)}>{available.map(r=><option key={r.source_sequence_id} value={r.source_sequence_id}>{sourceName(r.source)} · {r.native_id}{r.chain_id?` / ${r.chain_id}`:''}</option>)}</select></label></header><div className="mtp-architecture">{record.integrated_segments.map((s,i)=><div className={`mtp-architecture-part mtp-part-${segmentTone(s.type)}`} key={s.id}><span className="mtp-order">{i+1}</span><strong>{segmentNames[s.type]??s.type}</strong><span>{s.start}–{s.end}</span>{segmentTone(s.type)==='membrane'&&<i className="mtp-helix" aria-hidden="true"/>}</div>)}</div><footer><span>{record.native_id} · {record.actual_length.toLocaleString()} aa. Inside / outside retain the source’s membrane-side labels.</span><button onClick={()=>onOpen(record.source)}>Source details <ArrowRight size={13}/></button></footer></section>;
}
interface FeatureRow {feature_id:string;role:string;method:string|null;native_type:string;model_id:string|null;start:number|null;end:number|null;coordinate_status:string;source_attributes:RecordData;evidence_status:string;locations:{start:number;end:number;mapping_status:string}[];domains:{model_database:string;model_id:string;side:string;support_raw:string}[];evidence:{type:string|null;subtype:string|null;reference:string|null;value:string|null;structures:{id:string;chains:string[]}[]}[]}
function FeatureEvidence({row}:{row:FeatureRow}){
 const parent=(row.source_attributes.parent_attributes??{}) as RecordData;
 return <><Fields items={[{label:'Source sequence interval',value:row.start==null||row.end==null?'Unresolved':`${row.start}–${row.end}`},{label:'Canonical interval',value:row.locations.length?row.locations.map(l=>`${l.start}–${l.end}`).join(' · '):'Not mapped to the current canonical sequence'},{label:'Source type',value:segmentNames[row.native_type]??row.native_type},{label:'Record role',value:roles[row.role]??label(row.role)},{label:'Method',value:row.method},{label:'Constraint source',value:parent.source},{label:'Source identifier',value:parent.sourceId},{label:'Source coordinate status',value:label(row.coordinate_status)}]}/>{row.evidence.map((e,index)=><article className="mtp-experiment" key={index}><div><Microscope size={16}/><strong>{e.type??'Source evidence'}</strong>{e.subtype&&<Badge>{e.subtype}</Badge>}</div>{e.reference&&<p className="mtp-reference-links">{e.reference.split(/[;,\s]+/).filter(Boolean).map(id=><LinkOut key={id} href={/^\d+$/.test(id)?`https://pubmed.ncbi.nlm.nih.gov/${id}/`:undefined}>{/^\d+$/.test(id)?`PMID:${id}`:id}</LinkOut>)}</p>}{e.structures.map((p,i)=><p key={i}><LinkOut href={/^[a-z0-9]{4}$/i.test(p.id)?`https://www.rcsb.org/structure/${p.id}`:undefined}>PDB {p.id}</LinkOut>{p.chains.length?` · Chain ${p.chains.join(', ')}`:''}</p>)}{e.value&&<p>Source value: {e.value}</p>}</article>)}{row.evidence_status==='unparsed'&&<p className="mtp-note">Source evidence text is present but could not be interpreted for this view.</p>}{row.domains.map((d,index)=><div className="mtp-domain-evidence" key={index}><Badge>{d.model_database}</Badge><strong>{d.model_id}</strong><span>Source side: {d.side}</span><span>Support: {d.support_raw||'Not supplied'}</span></div>)}{!row.evidence.length&&!row.domains.length&&row.role==='experimental_evidence'&&row.evidence_status!=='unparsed'&&<p className="mtp-note">No structured experiment details were supplied with this source region.</p>}</>;
}
function TopologyRecordDetails({record,accession}:{record:TopologyRecord;accession:string}){
 const [role,setRole]=useState(record.integrated_segments.length?'integrated_topology':record.experimental_regions?'experimental_evidence':record.structure_regions?'structure_region':'');const [method,setMethod]=useState('');const [offset,setOffset]=useState(0);
 const query=useQuery({queryKey:['topology-record',accession,record.source_sequence_id,role,method,offset],queryFn:({signal})=>api<{items:FeatureRow[];total:number;has_more:boolean}>(`/proteins/${accession}/overview/membrane/topology?${params({source_sequence_id:record.source_sequence_id,role,method,limit:20,offset})}`,signal)});
 return <div className="mtp-record-details"><div className="mtp-record-summary"><span>{record.native_id}{record.chain_id?` / chain ${record.chain_id}`:''} · {number(record.actual_length,0)} aa</span><span>{record.mapped_feature_count} / {record.feature_count} source features mapped to canonical</span></div>{!!record.reported_tm_counts.length&&<p className="mtp-original-facts"><b>{record.reported_tm_counts.join(' / ')}</b> reported TM segments{record.reliability_values.length>0&&<> · Original reliability <b>{record.reliability_values.join(' / ')}</b></>}</p>}<div className="mtp-role-controls" role="group" aria-label="Topology evidence category">{[{value:'',name:'All source features'},...Object.entries(roles).map(([value,name])=>({value,name}))].map(item=><button key={item.value} aria-pressed={role===item.value} onClick={()=>{setRole(item.value);setMethod('');setOffset(0);}}>{item.name}</button>)}</div>{role==='method_prediction'&&<label className="mtp-method-filter">Prediction method<select value={method} onChange={e=>{setMethod(e.target.value);setOffset(0);}}><option value="">All method outputs</option>{record.methods.map(m=><option value={m} key={m}>{m}</option>)}</select></label>}<p className="mtp-note">Intervals are on the original source sequence. Canonical coordinates are shown only where explicitly mapped. Evidence regions are not a count of independent experiments.</p><Status loading={query.isPending} error={query.error} empty={!query.data?.items.length}>{query.data?.items.map(row=><Disclosure key={row.feature_id} title={<span className="mtp-feature-heading"><Badge tone={row.role==='method_prediction'?'purple':'neutral'}>{roles[row.role]??label(row.role)}</Badge><strong>{segmentNames[row.native_type]??row.native_type}</strong><span>{row.start??'?'}–{row.end??'?'}</span><small>{row.method??''}</small></span>}><FeatureEvidence row={row}/></Disclosure>)}</Status>{query.data&&query.data.total>20&&<Pager page={offset/20} count={query.data.items.length} next={query.data.has_more?'more':null} onPrevious={()=>setOffset(Math.max(0,offset-20))} onNext={()=>setOffset(offset+20)} loading={query.isFetching} onJump={p=>setOffset(p*20)} totalPages={Math.ceil(query.data.total/20)} maxPage={5000}/>}</div>;
}
export function TopologySources({records,accession,initialSource='HTP'}:{records:TopologyRecord[];accession:string;initialSource?:string}){
 const groups=[...new Set(records.map(r=>r.source))];const [source,setSource]=useState(groups.includes(initialSource)?initialSource:groups[0]??'');const candidates=records.filter(r=>r.source===source);const [selected,setSelected]=useState('');const record=candidates.find(r=>r.source_sequence_id===selected)??candidates.find(r=>r.mapped_feature_count>0)??candidates[0];
 if(!records.length)return <p className="mtp-empty">No external topology source is associated with this protein.</p>;
 return <><p className="mtp-note">Explore each source’s conclusion and its supporting records. Benchmark sets and reused constraints are not independent corroboration.</p><div className="mtp-source-tabs" role="group" aria-label="Membrane topology databases">{groups.map(g=><button key={g} onClick={()=>{setSource(g);setSelected('');}} aria-pressed={g===source}><Database size={15}/>{sourceName(g)}<span>{records.filter(r=>r.source===g).length}</span></button>)}</div>{record&&<><div className="mtp-select-record"><label>Source entry / chain<select aria-label="Membrane source record" value={record.source_sequence_id} onChange={e=>setSelected(e.target.value)}>{candidates.map(r=><option key={r.source_sequence_id} value={r.source_sequence_id}>{r.native_id}{r.chain_id?` / ${r.chain_id}`:''} · {r.actual_length} aa{r.mapped_feature_count?' · mapped features':' · identity link only'}</option>)}</select></label><span><Link2 size={14}/>{record.mapping_note}</span></div><TopologyRecordDetails key={record.source_sequence_id} record={record} accession={accession}/></>}</>;
}
export function SourceCoverage({records,onOpen}:{records:TopologyRecord[];onOpen:(source:string)=>void}){
 const groups=[...new Set(records.map(r=>r.source))];
 return <div className="mtp-coverage">{groups.map(source=>{const rows=records.filter(r=>r.source===source);return <button key={source} onClick={()=>onOpen(source)}><Database size={15}/><strong>{sourceName(source)}</strong><span>{rows.length} source {rows.length===1?'entry':'entries'}</span><ArrowUpRight size={13}/></button>;})}</div>;
}
