import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, ArrowUpRight, Database, Layers } from 'lucide-react';
import { api, label, params, type RecordData } from '../api';
import { Badge, LinkOut, Pager, Status } from './ui';
import './membrane-topology.css';
import MembraneTrack from './MembraneTrack';

export type TopologySegment={id:string;type:string;start:number;end:number;canonical_start:number|null;canonical_end:number|null;mapped_blocks:number|null;mapping_statuses:string[]|null};
export type TopologyRecord={source_sequence_id:string;record_id:string;source:string;native_id:string;chain_id:string|null;actual_length:number;feature_count:number;mapped_feature_count:number;experimental_regions:number;constraint_regions:number;structure_regions:number;methods:string[];constraint_sources:string[];reported_tm_counts:string[];reliability_values:string[];signal_region_reported:boolean;integrated_segments:TopologySegment[];mapping_note:string};
const sourceName=(source:string)=>source.replace('HTP/3D','HTP · structure benchmark').replace('HTP/experimental','HTP · experimental benchmark').replace('TmAlphaFold/cctop','TmAlphaFold · CCTOP').replace('TmAlphaFold/tmdet','TmAlphaFold · TmDet').replace('PDBTM/pdbtm_all','PDBTM · all chains').replace('PDBTM/pdbtm','PDBTM · subset');
const roles:Record<string,string>={integrated_topology:'Integrated topology',method_prediction:'Method predictions',constraint:'Source constraints',experimental_evidence:'Experimental / structure evidence',structure_region:'Structure regions'};
const segmentNames:Record<string,string>={S:'Signal peptide',Signal:'Signal peptide',O:'Outside',Outside:'Outside',I:'Inside',Inside:'Inside',M:'Membrane',Membrane:'Membrane'};
const segmentTone=(type:string)=>['M','Membrane'].includes(type)?'membrane':['S','Signal'].includes(type)?'signal':['O','Outside'].includes(type)?'outside':['I','Inside'].includes(type)?'inside':'other';
export function HtpPreview({records,onOpen}:{records:TopologyRecord[];onOpen:()=>void}){
 const candidates=records.filter(r=>r.source==='HTP');const record=candidates.find(r=>r.mapped_feature_count>0)??candidates[0];
 return <section className="mtp-htp-preview" aria-label="HTP topology preview"><div className="mov-preview-heading"><strong>HTP</strong><Badge tone="teal">Integrated topology</Badge><button onClick={onOpen}>View evidence<ArrowUpRight size={14}/></button></div><p>Source topology, method predictions and existing constraints.</p>{record?<><dl className="mtp-preview-values"><div><dt>Reported TM segments</dt><dd>{record.reported_tm_counts.join(' / ')||'Not supplied'}</dd></div><div><dt>HTP reliability</dt><dd>{record.reliability_values.join(' / ')||'Not supplied'}</dd></div><div><dt>Signal region</dt><dd>{record.signal_region_reported?'Reported':'Not reported'}</dd></div></dl><div className="mtp-preview-tags"><span>{record.methods.length} method outputs</span><span>{record.constraint_regions} constraint regions</span></div><small>{record.mapped_feature_count?'Source features mapped to canonical':'Source sequence only · not mapped to canonical'}{candidates.length>1?` · ${candidates.length} source records available`:''}. Reliability is the original source score.</small></>:<p className="mtp-empty">No HTP record is linked to this protein in the current collection.</p>}</section>;
}
export function TopologyPortrait({records,onOpen}:{records:TopologyRecord[];onOpen:(source:string)=>void}){
 const available=records.filter(r=>r.integrated_segments.length>0);const [selected,setSelected]=useState('');const record=available.find(r=>r.source_sequence_id===selected)??available.find(r=>r.source==='HTP'&&r.mapped_feature_count>0)??available[0];
 if(!record)return null;
 return <section className="mtp-portrait"><header><div><Layers size={17}/><strong>Topology at a glance</strong><span>Source sequence order · schematic, not to scale</span></div><label>Topology source<select aria-label="Topology portrait source" value={record.source_sequence_id} onChange={e=>setSelected(e.target.value)}>{available.map(r=><option key={r.source_sequence_id} value={r.source_sequence_id}>{sourceName(r.source)} · {r.native_id}{r.chain_id?` / ${r.chain_id}`:''}</option>)}</select></label></header><div className="mtp-architecture">{record.integrated_segments.map((s,i)=><div className={`mtp-architecture-part mtp-part-${segmentTone(s.type)}`} key={s.id}><span className="mtp-order">{i+1}</span><strong>{segmentNames[s.type]??s.type}</strong><span>{s.start}–{s.end}</span>{segmentTone(s.type)==='membrane'&&<i className="mtp-helix" aria-hidden="true"/>}</div>)}</div><footer><span>{record.native_id} · {record.actual_length.toLocaleString()} aa. Inside / outside retain the source’s membrane-side labels.</span><button onClick={()=>onOpen(record.source)}>Source details <ArrowRight size={13}/></button></footer></section>;
}
interface FeatureRow {feature_id:string;role:string;method:string|null;native_type:string;model_id:string|null;start:number|null;end:number|null;coordinate_status:string;source_attributes:RecordData;evidence_status:string;locations:{start:number;end:number;mapping_status:string}[];domains:{model_database:string;model_id:string;side:string;support_raw:string}[];evidence:{type:string|null;subtype:string|null;reference:string|null;value:string|null;structures:{id:string;chains:string[]}[]}[]}
function FeatureEvidence({row}:{row:FeatureRow}){
 const parent=(row.source_attributes.parent_attributes??{}) as RecordData;
 return <div className="membrane-table-evidence">{parent.source != null && <span>{String(parent.source)}{parent.sourceId != null ? ` · ${String(parent.sourceId)}` : ''}</span>}{row.evidence.map((e,index)=><div key={index}><span>{[e.type,e.subtype,e.value].filter(v=>v!=null&&v!=='').join(' · ')}</span>{e.reference&&<span>{e.reference.split(/[;,\s]+/).filter(Boolean).map(id=><LinkOut key={id} href={/^\d+$/.test(id)?`https://pubmed.ncbi.nlm.nih.gov/${id}/`:undefined}>{/^\d+$/.test(id)?`PMID:${id}`:id}</LinkOut>)}</span>}{e.structures.map((p,i)=><span key={i}><LinkOut href={/^[a-z0-9]{4}$/i.test(p.id)?`https://www.rcsb.org/structure/${p.id}`:undefined}>{p.id.toUpperCase()}</LinkOut>{p.chains.length?` · ${p.chains.join(', ')}`:''}</span>)}</div>)}{row.domains.map((d,index)=><span key={index}>{d.model_database} · {d.model_id}{d.side?` · ${d.side}`:''}{d.support_raw?` · ${d.support_raw}`:''}</span>)}{row.evidence_status==='unparsed'&&<span>See source evidence.</span>}</div>;
}
function TopologyRecordDetails({record,accession}:{record:TopologyRecord;accession:string}){
 const [role,setRole]=useState(record.integrated_segments.length?'integrated_topology':record.experimental_regions?'experimental_evidence':record.structure_regions?'structure_region':'');const [method,setMethod]=useState('');const [offset,setOffset]=useState(0);
 const query=useQuery({queryKey:['topology-record',accession,record.source_sequence_id,role,method,offset],queryFn:({signal})=>api<{items:FeatureRow[];total:number;has_more:boolean}>(`/proteins/${accession}/overview/membrane/topology?${params({source_sequence_id:record.source_sequence_id,role,method,limit:20,offset})}`,signal)});
 const rows=query.data?.items??[];
 const hasEvidence=rows.some(row=>row.evidence.length||row.domains.length||row.evidence_status==='unparsed'||((row.source_attributes.parent_attributes??{}) as RecordData).source!=null);
 const trackIntervals=record.integrated_segments.length ? record.integrated_segments.map(segment=>({id:segment.id,start:segment.start,end:segment.end,name:segmentNames[segment.type]??segment.type})) : rows.filter(row=>row.start!=null&&row.end!=null&&row.coordinate_status==='valid').map(row=>({id:row.feature_id,start:row.start!,end:row.end!,name:segmentNames[row.native_type]??row.native_type,description:row.method??''}));
 return <div className="mtp-record-details">
   <MembraneTrack key={record.source_sequence_id} title={`Source sequence · ${record.native_id}${record.chain_id?` / ${record.chain_id}`:''}`} length={record.actual_length} intervals={trackIntervals}/>
   {!record.integrated_segments.length&&query.data?.has_more&&<p className="mtp-note">Track shows the intervals on this table page.</p>}
   {!!record.reported_tm_counts.length&&<p className="mtp-original-facts"><b>{record.reported_tm_counts.join(' / ')}</b> TM segments{record.reliability_values.length>0&&<> · Reliability <b>{record.reliability_values.join(' / ')}</b></>}</p>}
   <div className="membrane-table-controls"><label>Records<select aria-label="Topology evidence category" value={role} onChange={e=>{setRole(e.target.value);setMethod('');setOffset(0);}}><option value="">All source features</option>{Object.entries(roles).map(([value,name])=><option value={value} key={value}>{name}</option>)}</select></label>{role==='method_prediction'&&<label>Method<select value={method} onChange={e=>{setMethod(e.target.value);setOffset(0);}}><option value="">All methods</option>{record.methods.map(m=><option value={m} key={m}>{m}</option>)}</select></label>}</div>
   <Status loading={query.isPending} error={query.error} empty={!rows.length}><div className="table-wrap membrane-evidence-table"><table className="data-table"><thead><tr><th>Source type</th><th>Interval</th><th>Record role</th>{hasEvidence&&<th>Evidence</th>}</tr></thead><tbody>{rows.map(row=><tr key={row.feature_id}><td>{segmentNames[row.native_type]??row.native_type}</td><td>{row.start??'?'}–{row.end??'?'}{row.coordinate_status!=='valid'&&<small className="membrane-cell-note">Uncertain boundary</small>}</td><td>{roles[row.role]??label(row.role)}{row.method&&<small className="membrane-cell-note">{row.method}</small>}</td>{hasEvidence&&<td><FeatureEvidence row={row}/></td>}</tr>)}</tbody></table></div></Status>
   {query.data&&query.data.total>20&&<Pager page={offset/20} count={rows.length} next={query.data.has_more?'more':null} onPrevious={()=>setOffset(Math.max(0,offset-20))} onNext={()=>setOffset(offset+20)} loading={query.isFetching} onJump={p=>setOffset(p*20)} totalPages={Math.ceil(query.data.total/20)} maxPage={5000}/>}</div>;
}
export function TopologySources({records,accession,initialSource='HTP'}:{records:TopologyRecord[];accession:string;initialSource?:string}){
 const groups=[...new Set(records.map(r=>r.source))];const [source,setSource]=useState(groups.includes(initialSource)?initialSource:groups[0]??'');const candidates=records.filter(r=>r.source===source);const [selected,setSelected]=useState('');const record=candidates.find(r=>r.source_sequence_id===selected)??candidates.find(r=>r.mapped_feature_count>0)??candidates[0];
 if(!records.length)return <p className="mtp-empty">No external topology source is associated with this protein.</p>;
 return <section className="membrane-source-section"><div className="membrane-view-heading"><h3>Topology by source</h3><span>Source sequence numbering</span></div><div className="mtp-source-tabs" role="group" aria-label="Membrane topology databases">{groups.map(g=><button key={g} onClick={()=>{setSource(g);setSelected('');}} aria-pressed={g===source}><Database size={15}/>{sourceName(g)}</button>)}</div>{record&&<>{candidates.length>1&&<div className="membrane-table-controls"><label>Entry / chain<select aria-label="Membrane source record" value={record.source_sequence_id} onChange={e=>setSelected(e.target.value)}>{candidates.map(r=><option key={r.source_sequence_id} value={r.source_sequence_id}>{r.native_id}{r.chain_id?` / ${r.chain_id}`:''} · {r.actual_length} aa</option>)}</select></label></div>}<TopologyRecordDetails key={record.source_sequence_id} record={record} accession={accession}/></>}</section>;
}
export function SourceCoverage({records,onOpen}:{records:TopologyRecord[];onOpen:(source:string)=>void}){
 const groups=[...new Set(records.map(r=>r.source))];
 return <div className="mtp-coverage">{groups.map(source=>{const rows=records.filter(r=>r.source===source);return <button key={source} onClick={()=>onOpen(source)}><Database size={15}/><strong>{sourceName(source)}</strong><span>{rows.length} source {rows.length===1?'entry':'entries'}</span><ArrowUpRight size={13}/></button>;})}</div>;
}
