import { Link, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, Search, Database, Dna, Ruler, SlidersHorizontal } from 'lucide-react';
import { api, params } from '../api';
import { type Protein } from './Overview';
import { Panel, PageJump, Status } from './ui';
import { membraneClasses, ProteinSearchForm, useCatalogSummary } from './HomePage';

function ProteinPages({page,total,onChange}:{page:number;total:number;onChange:(page:number)=>void}){
 const count=Math.ceil(total/30);if(count<=1)return <div className="catalog-pages" role="status">{total.toLocaleString('en-US')} {total===1?'protein entry':'protein entries'}</div>;const start=Math.max(1,Math.min(page-2,count-4));
 const pages=[...new Set([1,count,...Array.from({length:Math.min(5,count)},(_,i)=>start+i)])].sort((a,b)=>a-b);
 return <nav className="catalog-pages" aria-label="Protein result pages"><span>{(page-1)*30+1}–{Math.min(page*30,total)} of {total.toLocaleString('en-US')} proteins</span><div><button disabled={page===1} aria-label="Previous protein page" onClick={()=>onChange(page-1)}>‹</button>{pages.map((p,i)=><span key={p}>{i>0&&p-pages[i-1]>1&&<span className="catalog-ellipsis">…</span>}<button aria-label={`Protein page ${p}`} aria-current={p===page?'page':undefined} onClick={()=>onChange(p)}>{p}</button></span>)}<button disabled={page===count} aria-label="Next protein page" onClick={()=>onChange(page+1)}>›</button></div><PageJump page={page-1} onJump={p=>onChange(p+1)} totalPages={count} maxPage={3333} label="Go to protein page"/></nav>;
}
export default function ProteinSearch(){
 const [search,setSearch]=useSearchParams();const queryText=search.get('query')??'';const category=search.get('membrane_class')??'';const location=search.get('membrane_location')??'';const summary=useCatalogSummary();const locationInfo=summary.data?.locations.find(item=>item.id===location);
 const requested=Number(search.get('page')??1);const page=Number.isSafeInteger(requested)&&requested>0?Math.min(requested,3334):1;
 const categoryInfo=membraneClasses.find(c=>c.key===category);
 const query=useQuery({queryKey:['search',queryText,category,location,page],queryFn:({signal})=>api<{items:Protein[];has_more:boolean;total:number}>(`/proteins?${params({query:queryText,membrane_class:category,membrane_location:location,limit:30,offset:(page-1)*30})}`,signal)});
 function update(values:Record<string,string>){const next=new URLSearchParams(search);for(const [key,value]of Object.entries(values)){if(value)next.set(key,value);else next.delete(key);}setSearch(next);}
 return <main className="search-page catalog-search-page"><div className="page-intro"><Link className="catalog-back" to="/">← Home</Link><h1>{locationInfo?.label??categoryInfo?.label??'Explore membrane proteins'}</h1><p>{location?'Proteins with this exact UniProt entry-level location annotation. Locations may overlap.':categoryInfo?.description??'Search human membrane proteins by gene symbol, protein name or UniProt accession.'}</p></div><ProteinSearchForm key={queryText} initial={queryText} onSearch={value=>update({query:value,page:''})}/><div className="catalog-filters"><div className="catalog-filter-heading"><SlidersHorizontal size={16} aria-hidden="true"/>Filter protein entries</div><label>Membrane class<select value={category} onChange={e=>update({membrane_class:e.target.value,page:''})}><option value="">All classes</option>{membraneClasses.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></label><label>Membrane location<select value={location} onChange={e=>update({membrane_location:e.target.value,page:''})}><option value="">All locations</option>{(summary.data?.locations??[]).map(item=><option key={item.id} value={item.id}>{item.label}{item.id==='SL-0162'?' (unspecified)':''} · {item.count.toLocaleString('en-US')}</option>)}</select></label><p>Primary branches are mutually exclusive; parent and child totals describe the same hierarchy. Each protein appears once.</p></div><Panel id="search-results" title="Protein entries" subtitle={query.data?`${query.data.total.toLocaleString('en-US')} matching entries${queryText?` for “${queryText}”`:''}`:'Select an entry to explore its sequence, variants and evidence'} icon={<Search/>}><Status loading={query.isPending} error={query.error} empty={!query.data?.items.length}><div className="protein-results">{query.data?.items.map(p=><Link key={p.accession} to={`/protein/${p.accession}`}><div><strong>{p.protein_name??p.accession}</strong><span className="protein-result-gene"><Dna size={14} aria-hidden="true"/>{p.gene_names?.join(' · ')||<span title="No gene symbol supplied">—</span>}</span></div><span className="protein-result-meta"><Database size={14} aria-hidden="true"/><span className="sr-only">UniProt </span>{p.accession}</span><span className="protein-result-meta" title={p.length==null?'Sequence length unavailable':'Sequence length'}><Ruler size={14} aria-hidden="true"/>{p.length==null?'—':`${p.length.toLocaleString()} aa`}</span><ArrowRight size={18}/></Link>)}</div></Status>{query.data&&query.data.total>0&&(page>Math.ceil(query.data.total/30)?<button className="button" onClick={()=>update({page:''})}>Return to first page</button>:<ProteinPages page={page} total={query.data.total} onChange={nextPage=>{update({page:String(nextPage)});document.getElementById('search-results')?.scrollIntoView({block:'start'});}}/>)}</Panel></main>;
}
