import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Minus, Plus, RotateCcw, Table2 } from 'lucide-react';
import { featureStyle, type Feature, type Track } from './sequence-model';
import { Modal, PageJump } from './ui';
import { Button } from './ui/button';
import './sequence-refinement.css';

export type Range = [number,number];
export function RangeControls({range,length,onRange}:{range:Range;length:number;onRange:(r:Range)=>void}) {
 const [start,setStart]=useState(String(range[0])),[end,setEnd]=useState(String(range[1])),[error,setError]=useState('');
 useEffect(()=>{setStart(String(range[0]));setEnd(String(range[1]));setError('');},[range[0],range[1]]);
 const move=(factor:number,pan=0)=>{const width=Math.min(length,Math.max(10,Math.round((range[1]-range[0]+1)*factor)));const centre=(range[0]+range[1])/2+pan*(range[1]-range[0]+1);const lo=Math.max(1,Math.min(length-width+1,Math.round(centre-width/2)));onRange([lo,lo+width-1]);};
 return <form className="range-controls" onSubmit={e=>{e.preventDefault();const a=Number(start),b=Number(end);if(!Number.isInteger(a)||!Number.isInteger(b)||a<1||b<a||b>length){setError(`Use positions 1–${length}, with end ≥ start.`);return;}onRange([a,b]);}}><strong>Sequence display window</strong><label>Start<input aria-label="Sequence start" value={start} onChange={e=>setStart(e.target.value)} inputMode="numeric"/></label><label>End<input aria-label="Sequence end" value={end} onChange={e=>setEnd(e.target.value)} inputMode="numeric"/></label><Button variant="outline" size="sm" type="submit">Apply window</Button><div className="range-tools"><Button variant="outline" size="icon-sm" type="button" aria-label="Pan sequence left" onClick={()=>move(1,-.7)} disabled={range[0]===1}><ArrowLeft size={16}/></Button><Button variant="outline" size="icon-sm" type="button" aria-label="Zoom sequence in" onClick={()=>move(.5)} disabled={range[1]-range[0]<10}><Plus size={16}/></Button><Button variant="outline" size="icon-sm" type="button" aria-label="Zoom sequence out" onClick={()=>move(2)} disabled={range[1]-range[0]+1===length}><Minus size={16}/></Button><Button variant="outline" size="icon-sm" type="button" aria-label="Pan sequence right" onClick={()=>move(1,.7)} disabled={range[1]===length}><ArrowRight size={16}/></Button></div><Button className="sequence-reset" variant="outline" size="sm" type="button" title="Show the full sequence; keep residue selection and variant filters" onClick={()=>{setError('');onRange([1,length]);}}><RotateCcw size={15}/>Reset window · full sequence</Button>{error&&<span role="alert">{error}</span>}</form>;
}
export function ResidueAxis({sequence,range,onRange}:{sequence:string;range:Range;onRange:(r:Range)=>void}) {
 const host=useRef<HTMLDivElement>(null),[width,setWidth]=useState(1000);
 useEffect(()=>{const el=host.current;if(!el)return;const observer=new ResizeObserver(entries=>setWidth(Math.max(1,entries[0].contentRect.width)));observer.observe(el);return()=>observer.disconnect();},[]);
 const drag=useRef<number|null>(null);const [brush,setBrush]=useState<Range|null>(null);const span=range[1]-range[0]+1;
 const position=(e:React.PointerEvent<SVGSVGElement>)=>{const box=e.currentTarget.getBoundingClientRect();return Math.max(range[0],Math.min(range[1],range[0]+Math.floor((e.clientX-box.left)/box.width*span)));};
 const showLetters=span<=Math.min(80,Math.floor(width/11));
 const ticks=span<=80?Array.from({length:span},(_,i)=>range[0]+i).filter((p,i)=>i===0||i===span-1||p%10===0):Array.from({length:6},(_,i)=>Math.round(range[0]+i*(span-1)/5));
 return <div className="residue-axis" ref={host}><svg viewBox={`0 0 ${width} ${showLetters?50:32}`} style={{height:showLetters?50:32,touchAction:"none",userSelect:"none"}} preserveAspectRatio="none" role="img" aria-label={`Residue axis ${range[0]}–${range[1]}; drag to select a range`} onPointerDown={e=>{drag.current=position(e);setBrush([drag.current,drag.current]);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current!==null)setBrush([drag.current,position(e)]);}} onPointerUp={e=>{const a=drag.current,b=position(e);drag.current=null;setBrush(null);if(a!==null&&a!==b)onRange([Math.min(a,b),Math.max(a,b)]);}} onPointerCancel={()=>{drag.current=null;setBrush(null);}}>
  {brush&&<rect x={(Math.min(...brush)-range[0])/span*width} y="0" width={(Math.abs(brush[1]-brush[0])+1)/span*width} height="50" fill="#bfdbfe"/>}<line x1="0" x2={width} y1="1" y2="1" stroke="#d5deed"/>{ticks.map((p,i)=><g key={`${p}-${i}`}><line x1={(p-range[0]+.5)/span*width} x2={(p-range[0]+.5)/span*width} y1="1" y2="7" stroke="#8b9bb3"/><text x={(p-range[0]+.5)/span*width} y="20" textAnchor={i===0?'start':i===ticks.length-1?'end':'middle'} fontSize="11" fill="#6b7d98">{p}</text></g>)}{showLetters&&sequence.slice(range[0]-1,range[1]).split('').map((aa,i)=><text key={i} x={(i+.5)/span*width} y="41" textAnchor="middle" fontFamily="monospace" fontSize="13" fontWeight="600" fill="#334155">{aa}</text>)}</svg><small>{showLetters?'Residue letters · ':''}Drag this ruler to zoom · positions shared by all tracks</small></div>;
}
function FeatureList({features,onFeature}:{features:Feature[];onFeature:(f:Feature)=>void}){return <div className="annotation-cluster-list">{features.map((f,i)=><button key={`${f.id}-${i}`} onClick={()=>onFeature(f)}><strong>{f.start===f.end?f.start:`${f.start}–${f.end}`}</strong><span>{f.label??f.source_type}<small>{f.source}</small></span><ArrowRight size={15}/></button>)}</div>;}

export function SecondaryTrack({track,sequence,range,onRange,onFeature}:{track:Track;sequence:string;range:Range;onRange:(r:Range)=>void;onFeature:(f:Feature)=>void}) {
 const [selection,setSelection]=useState<Feature[]|null>(null);const span=range[1]-range[0]+1;const detailed=span<=120;
 const types=['Helix','Beta strand','Turn / loop'];const visible=track.features.filter(f=>f.start<=range[1]&&f.end>=range[0]);
 return <div className="annotation-summary secondary-summary"><header><strong>Secondary structure <small>UniProt</small></strong><span>{detailed?'Original segments':'Regional coverage'} · {visible.length} annotations</span></header><p>{detailed?'Click a segment to inspect the original annotation.':'Zoom in to see segment boundaries. Each colour band shows the fraction of residues covered by that annotation class.'}</p>
 {types.map(type=>{const items=visible.filter(f=>featureStyle(f,'secondary').name===type);const colour=featureStyle({start:1,end:1,label:type},'secondary').color;const bins=Array.from({length:Math.min(50,span)},(_,i)=>({lo:range[0]+Math.floor(i*span/Math.min(50,span)),hi:range[0]+Math.floor((i+1)*span/Math.min(50,span))-1}));return <div className="secondary-band" key={type}><span><i style={{background:colour}}/>{type}<b>{items.length}</b></span><svg viewBox="0 0 1000 23" preserveAspectRatio="none" aria-label={`${type} secondary structure`}>
 {detailed?items.map((f,i)=>{const x=(Math.max(range[0],f.start)-range[0])/span*1000,w=(Math.min(range[1],f.end)-Math.max(range[0],f.start)+1)/span*1000;return <g key={`${f.id}-${i}`} role="button" tabIndex={0} aria-label={`${type} ${f.start}–${f.end}`} onClick={()=>onFeature({...f,group:'secondary'})} onKeyDown={e=>{if(e.key==='Enter'){onFeature({...f,group:'secondary'});}}}><title>{type} {f.start}–{f.end}</title><rect x={x} y="4" width={Math.max(2,w)} height="15" fill={colour} rx="3"/></g>}):bins.map(b=>{const hits=items.filter(f=>f.start<=b.hi&&f.end>=b.lo);const covered=new Set(hits.flatMap(f=>Array.from({length:Math.min(b.hi,f.end)-Math.max(b.lo,f.start)+1},(_,i)=>Math.max(b.lo,f.start)+i))).size;return <g key={b.lo} role={hits.length?'button':undefined} tabIndex={hits.length?0:undefined} aria-label={`${type}, ${b.lo}–${b.hi}: ${covered} covered residues`} onClick={()=>{if(hits.length)setSelection(hits);}} onKeyDown={e=>{if(e.key==='Enter'&&hits.length)setSelection(hits);}}><title>{b.lo}–{b.hi}: {covered}/{b.hi-b.lo+1} residues</title><rect x={(b.lo-range[0])/span*1000} y="4" width={(b.hi-b.lo+1)/span*1000-.5} height="15" fill={covered?colour:'#f1f5f9'} fillOpacity={covered?.15+.85*covered/(b.hi-b.lo+1):1} rx="2"/></g>})}</svg></div>})}<ResidueAxis sequence={sequence} range={range} onRange={onRange}/>{selection&&<Modal title="Secondary structure · source segments" onClose={()=>setSelection(null)}><FeatureList features={selection} onFeature={f=>{setSelection(null);onFeature({...f,group:'secondary'});}}/></Modal>}</div>;
}

export function FunctionSites({track,range,onFeature}:{track?:Track;range:Range;onFeature:(f:Feature)=>void}) {
 if(!track?.features.length)return null;const span=range[1]-range[0]+1;return <div className="functional-subtrack"><span>Functional sites</span><svg viewBox="0 0 1000 26" preserveAspectRatio="none" aria-label="Functional sites aligned with domains">{track.features.filter(f=>f.start<=range[1]&&f.end>=range[0]).map((f,i)=><g key={`${f.id}-${i}`} role="button" tabIndex={0} aria-label={`${f.label??f.source_type} ${f.start}–${f.end}`} onClick={()=>onFeature({...f,group:'function'})} onKeyDown={e=>{if(e.key==='Enter')onFeature({...f,group:'function'});}}><title>{f.label??f.source_type} · {f.start}–{f.end}</title><rect x={(Math.max(range[0],f.start)-range[0])/span*1000} y="10" width={Math.max(5,(Math.min(range[1],f.end)-Math.max(range[0],f.start)+1)/span*1000)} height="6" rx="3" fill="#db2777"/></g>)}</svg></div>;
}

export function PtmExplorer({track,sequence,range,onRange,onFeature,onSelect,source,onSource}:{track:Track;sequence:string;range:Range;onRange:(r:Range)=>void;onFeature:(f:Feature)=>void;onSelect:(p:number)=>void;source:string;onSource:(s:string)=>void}) {
 const [type,setType]=useState('all'),[page,setPage]=useState(0);const sources=Array.from(new Set(track.features.map(f=>f.source??'Unknown')));const sourceRows=track.features.filter(f=>source==='all'||f.source===source);const types=Array.from(new Set(sourceRows.map(f=>f.source_type??f.label??'PTM'))).sort();
 useEffect(()=>{setPage(0);},[source,type,range[0],range[1],sequence]);
 const rows=useMemo(()=>sourceRows.filter(f=>f.start>=range[0]&&f.start<=range[1]&&(type==='all'||(f.source_type??f.label)===type)).sort((a,b)=>a.start-b.start),[sourceRows,range,type]);
 const span=range[1]-range[0]+1;const width=Math.max(1,Math.ceil(span/50));const bins=Array.from({length:Math.ceil(span/width)},(_,i)=>{const start=range[0]+i*width,end=Math.min(range[1],start+width-1);const hits=rows.filter(f=>f.start>=start&&f.start<=end);return {start,end,hits,sites:new Set(hits.map(f=>f.start)).size};});const max=Math.max(1,...bins.map(b=>b.sites));
 return <div className="annotation-summary ptm-explorer" id="ptm-annotations" data-source={source}><header><strong><Table2 size={19}/> PTM annotations</strong><span>Position-first table · {source}</span></header><p>Browse exact sites and source evidence here. The sequence band shows coverage; it does not assign importance or confidence to marker shapes.</p><div className="ptm-controls"><label>PTM source<select aria-label="PTM table source" value={source} onChange={e=>{onSource(e.target.value);setType('all');}}><option value="all">All sources</option>{Array.from(new Set(['dbPTM',...sources])).map(s=><option key={s}>{s}</option>)}</select></label><label>Modification<select aria-label="PTM modification" value={type} onChange={e=>setType(e.target.value)}><option value="all">All types</option>{types.map(t=><option key={t}>{t}</option>)}</select></label><span><b>{new Set(rows.map(f=>f.start)).size}</b> sites · <b>{rows.length}</b> position/type annotations · {range[0]}–{range[1]}</span></div>
 <div className="ptm-coverage"><svg viewBox="0 0 1000 35" preserveAspectRatio="none" aria-label="PTM site coverage">{span<=100?Array.from(new Set(rows.map(f=>f.start))).map(p=><g key={p} role="button" tabIndex={0} aria-label={`PTM position ${p}`} onClick={()=>{onSelect(p);setPage(Math.floor(rows.findIndex(f=>f.start===p)/10));}} onKeyDown={e=>{if(e.key==='Enter'){onSelect(p);setPage(Math.floor(rows.findIndex(f=>f.start===p)/10));}}}><title>{p} · see table</title><ellipse cx={(p-range[0]+.5)/span*1000} cy="17" rx="4.5" ry="6" fill="#2563eb"/></g>):bins.map(b=><g key={b.start} role="button" tabIndex={0} aria-label={`PTM coverage ${b.start}–${b.end}: ${b.sites} sites`} onClick={()=>onRange([b.start,b.end])} onKeyDown={e=>{if(e.key==='Enter')onRange([b.start,b.end]);}}><title>{b.start}–{b.end} · {b.sites} annotated sites · click to zoom</title><rect x={(b.start-range[0])/span*1000} y="8" width={(b.end-b.start+1)/span*1000-1} height="18" rx="2" fill={b.sites?'#2563eb':'#edf2fa'} fillOpacity={b.sites?.15+.85*b.sites/max:1}/></g>)}</svg><div className="coverage-key">{span<=100?<span>One marker per annotated residue · details in the table</span>:<><span>Regional site coverage</span><i/>Fewer → more sites</>}</div></div><ResidueAxis sequence={sequence} range={range} onRange={onRange}/>
 {!rows.length?<p className="empty-state">No {source} PTM annotation in this range. Other sources remain available in the selector.</p>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Residue</th><th>Modification</th><th>Source</th><th className="sequence-numeric">Source records</th><th>Evidence</th></tr></thead><tbody>{rows.slice(page*10,page*10+10).map((f,i)=><tr key={`${f.id}-${i}`}><td><button className="text-button mono" onClick={()=>onSelect(f.start)}>{sequence[f.start-1]}{f.start}</button></td><td><span className="ptm-type"><i style={{background:featureStyle(f,'ptm').color}}/>{f.source_type??f.label}</span></td><td>{f.source}</td><td className="sequence-numeric">{f.record_ids?.length??1}</td><td><button className="text-button" onClick={()=>onFeature({...f,group:'ptm'})}>View annotation <ArrowRight size={14}/></button></td></tr>)}</tbody></table></div>}<div className="ptm-pagination"><span>Source records remain separate in the evidence view</span><PageJump page={page} onJump={setPage} totalPages={Math.max(1,Math.ceil(rows.length/10))} label="PTM annotation page"/><button className="button" disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><button className="button" disabled={(page+1)*10>=rows.length} onClick={()=>setPage(page+1)}>Next</button></div></div>;
}
