import { PageJump } from './ui';
import { Button } from './ui/button';
import { ModeToggleGroup } from './ui/mode-toggle-group';
import { ContentTransition, SelectionFeedback } from '@/lib/motion';
import { ClinicalIcon, FrequencyIcon, PredictionIcon } from '@/lib/icons';
import { useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode, type CSSProperties } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import type { ColumnDef } from '@tanstack/react-table';
import { ArrowUpRight, BarChart3, Check, ChevronLeft, ChevronRight, Dna, Filter, FlaskConical, Globe2, MapPin, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Layers3, Activity, X } from 'lucide-react';
import { api, display, label, number, params, type RecordData } from '../api';
import { DataTable, DetailFields, Disclosure, Fields, LinkOut, Modal, Panel, SelectFilter, Status } from './ui';
import './variant-v2.css';
import { HelpButton } from './HelpGuide';
import { DBNSFP_COLUMNS, record, records, missing, clinicalTone, clinicalLabel, consequenceCategory, CONSEQUENCE_COLOURS, type Predictor } from './variant-evidence-model';
import { ClinicalBadge, PredictionValue, ReviewStars, ConsequencePills, FrequencyValue, PopulationDetail, ClinvarEvidence, PredictionDashboard, TranscriptEvidence, StabilityEvidence } from './VariantEvidencePanels';
import './variant-evidence.css';
import { PREDICTOR_GUIDES, predictorProject } from './predictor-guides';
import { VariantDistribution, type DistributionSite } from './VariantDistribution';
import './variant-catalog-layout.css';

interface Clinical extends RecordData { classification: string | null; review_status?: string | null; source_id?: string | null }
interface Frequency extends RecordData { af?: number | null; ac?: number | null; an?: number | null; population?: string; label?: string; status?: string }
interface VariantRow extends RecordData {
  variant_id: string; annotation_id: string; ref_aa?: string | null; aa_position?: string | number | null;
  alt_aa?: string | null; protein_change?: string | null; hgvsp?: string | null; hgvsc?:string|null; consequence?: string;
  chromosome?: string; position?: number; ref?: string; alt?: string; source_names?: string[];
  canonical_positions?: RecordData[]; transcript_status?:string;canonical_raw?:string|null;feature_type?:string;assembly?:string; clinvar?: Clinical[]; cosmic?: RecordData; frequency?: Frequency; predictions?: Predictor[];
}
interface Options { sources?: string[]; consequences?: string[]; predictors?: Predictor[]; frequency_types?: {value:string;label:string}[] }
interface VariantPage { items: VariantRow[]; next_cursor: string | null; filters?: Options }
interface Group { dimension:string; key:string; label:string; count:number; unit:string; filter:Record<string,string|number> }
interface ClinicalGroup { key:string;label:string;count:number;unit:string;annotation_rows?:number;filter?:Record<string,string|number> }
interface PredictorSummary {field_count:number;tool_label_count:number;tool_count_note?:string;groups:{name:string;description:string;field_count:number;tool_label_count:number;fields:Predictor[]}[]}
interface Summary { canonical_sites:DistributionSite[]; totals:{unique_variants:number;annotation_rows:number;canonical_mapped_variants:number;canonical_unmapped_variants:number;frequency_available:number;frequency_missing:number}; groups:Group[]; clinical_groups?:ClinicalGroup[];clinical_grouping?:string;transcript_groups?:ClinicalGroup[];predictor_summary?:PredictorSummary; sequence_id:string; sequence_length?:number; mapping_scope:string; filters?:Options; notes?:string[] }
interface Selection { id:string; title:string; tab:DetailTab }
type DetailTab='overview'|'ClinVar'|'COSMIC'|'gnomAD'|'predictions'|'transcripts'|'stability';
import { DEFAULT_PREDICTORS, PredictorPicker } from './PredictionToolkit';
const DEFAULT_DEFINITIONS:Predictor[]=[{field:'AlphaMissense_score',tool:'AlphaMissense',group:'Sequence models'},{field:'SIFT_score',tool:'SIFT',group:'Amino acid substitution'},{field:'REVEL_score',tool:'REVEL',group:'Integrated effect predictions'},{field:'CADD_phred',tool:'CADD',group:'Integrated effect predictions'}];
const FILTER_KEYS=['source','consequence','search','canonical_start','canonical_end','frequency','clinvar','af_min','af_max','af_status','transcript_status'] as const;
const POPULATIONS=[{value:'overall',label:'Overall exomes'},{value:'afr',label:'African / African American'},{value:'amr',label:'Admixed American'},{value:'asj',label:'Ashkenazi Jewish'},{value:'eas',label:'East Asian'},{value:'fin',label:'Finnish'},{value:'mid',label:'Middle Eastern'},{value:'nfe',label:'Non-Finnish European'},{value:'remaining',label:'Remaining individuals'},{value:'sas',label:'South Asian'},{value:'grpmax',label:'Maximum ancestry-group AF'}];
const POPULATION_NAMES=Object.fromEntries(POPULATIONS.map(p=>[p.value,p.label]));
function shortChange(row:VariantRow){return row.protein_change||row.hgvsp?.split(':').at(-1)?.replace(/^p\./,'')||row.variant_id;}
function SourceButton({source,onClick}:{source:string;onClick:()=>void}){return <button type="button" className={`vc-source vc-source-${source.toLowerCase()}`} onClick={onClick} title={source==='dbSNP'?'Open variant details · dbSNP source membership':`Open ${source} source evidence`}>{source}<ArrowUpRight size={11}/></button>;}

function CountGroups({title,icon,groups,onFilter,tone=false}:{title:string;icon:ReactNode;groups:Group[];onFilter:(filter:Record<string,string|number>)=>void;tone?:boolean}){
  const max=Math.max(1,...groups.map(g=>g.count));
  return <div className="vc-summary-group"><h3>{icon}{title}</h3>{groups.length?<div className="vc-group-rows">{groups.map(g=><button key={`${g.dimension}:${g.key}`} className={`vc-count-row ${tone?`vc-count-${clinicalTone(g.label)}`:''}`} onClick={()=>onFilter(g.filter)} title={`Filter: ${tone?clinicalLabel(g.label):g.label} · ${g.count.toLocaleString()} unique variants`}><span className="vc-count-label">{tone?clinicalLabel(g.label):label(g.label)}</span><span className="vc-count-track"><i style={{width:`${g.count/max*100}%`}}/></span><strong>{number(g.count,0)}</strong></button>)}</div>:<p className="vc-summary-empty">No source records in this selection.</p>}</div>;
}
const CLINICAL_COLOURS:Record<string,string>={pathogenic:'#e63559',uncertain:'#e9a117',benign:'#12a772',conflicting:'#9c43cf',other:'#1689d5',unclassified:'#94a3b8'};
function VariantCategoryCharts({summary,onFilter}:{summary:Summary;onFilter:(filter:Record<string,string|number>)=>void}){
  const consequences=summary.groups.filter(g=>g.dimension==='consequence');const clinical=summary.clinical_groups??[];
  const [hover,setHover]=useState<string|null>(null),[pinned,setPinned]=useState<string|null>(null);
  const active=clinical.find(g=>g.key===(hover??pinned));const select=(key:string)=>setPinned(current=>current===key?null:key);
  const total=summary.totals.unique_variants;const denominator=Math.max(1,total);let offset=0;
  const segments=clinical.map(group=>{const start=offset;offset+=group.count;return {...group,start};});
  return <div className="vc-category-charts">
    <section className="vc-category-panel"><header><h3><Layers3 size={17}/>Variant consequences</h3><span>{consequences.length} labels</span></header><div className="vc-consequence-chart">{consequences.length?consequences.map(group=><button key={group.key} onClick={()=>onFilter(group.filter)} title={`${group.count.toLocaleString()} matching variants with ${group.key}. Click to filter.`}><span className={`vc-effect vc-effect-${consequenceCategory(group.key)}`}>{label(group.label)}</span><span className="vc-category-track"><i style={{width:`${group.count/denominator*100}%`,background:CONSEQUENCE_COLOURS[consequenceCategory(group.key)]}}/></span><strong>{number(group.count,0)}</strong></button>):<p className="vc-summary-empty">No consequence annotations in this selection.</p>}</div><p>Variants can carry several labels; these counts overlap.</p></section>
    <section className="vc-category-panel"><header><h3><ShieldCheck size={17}/>ClinVar source classifications</h3><HelpButton topic="clinical"/></header><div className="vc-clinical-chart"><div className="vc-clinical-donut"><svg viewBox="0 0 150 150" role="img" aria-label={`ClinVar source classification groups for ${total.toLocaleString()} matching variants`}><circle cx="75" cy="75" r="55" fill="none" stroke="#edf1f7" strokeWidth="18"/>{segments.filter(g=>g.count>0).map(group=><circle key={group.key} cx="75" cy="75" r="55" fill="none" stroke={CLINICAL_COLOURS[group.key]??'#94a3b8'} strokeWidth={active?.key===group.key?22:18} opacity={!active||active.key===group.key?1:.3} onPointerEnter={()=>setHover(group.key)} onPointerLeave={()=>setHover(null)} onClick={()=>select(group.key)} style={{cursor:'pointer'}} pathLength="100" strokeDasharray={`${group.count/denominator*100} ${100-group.count/denominator*100}`} strokeDashoffset={-group.start/denominator*100} transform="rotate(-90 75 75)"><title>{group.label}: {group.count.toLocaleString()} ({(group.count/denominator*100).toFixed(1)}%)</title></circle>)}</svg><div><strong>{number(active?.count??total,0)}</strong><span>{active?`${(active.count/denominator*100).toFixed(1)}% of variants`:'variants'}</span></div></div><div className="vc-clinical-key">{clinical.length?clinical.map(group=><button type="button" key={group.key} aria-pressed={pinned===group.key} className={active?.key===group.key?'is-active':''} onPointerEnter={()=>setHover(group.key)} onPointerLeave={()=>setHover(null)} onFocus={()=>setHover(group.key)} onBlur={()=>setHover(null)} onClick={()=>select(group.key)} aria-label={`${group.label}: ${group.count.toLocaleString()} variants, ${(group.count/denominator*100).toFixed(1)} percent`}><i style={{background:CLINICAL_COLOURS[group.key]??'#94a3b8'}}/><span>{group.label}</span><strong>{number(group.count,0)}</strong><small>{(group.count/denominator*100).toFixed(1)}%</small></button>):<span className="vc-missing">Classification summary unavailable.</span>}</div></div><p className="vc-ring-feedback" aria-live="polite">{active?`${active.label} · ${number(active.count,0)} variants · ${(active.count/denominator*100).toFixed(1)}%`:'Hover to inspect · click legend to pin'}</p></section>
  </div>;
}
const GROUP_GUIDES:Record<string,{description:string;icon:ReactNode;colour:string}>={
  'Amino acid substitution':{description:'Sequence and protein-context estimates of substitution effects.',icon:<Dna size={18}/>,colour:'orange'},
  'Integrated effect predictions':{description:'Method-specific and combined estimates of variant effects.',icon:<Layers3 size={18}/>,colour:'blue'},
  'Sequence models':{description:'Protein or DNA sequence models, including evolutionary context.',icon:<Sparkles size={18}/>,colour:'purple'},
  'Loss of function':{description:'ALoFT class probabilities and affected-transcript fraction.',icon:<Activity size={18}/>,colour:'rose'},
  'Conservation and background':{description:'Evolutionary conservation and background-selection measures.',icon:<Globe2 size={18}/>,colour:'teal'},
  AlphaGenome:{description:'AVI raw / PHRED fields and splicing annotations.',icon:<Dna size={18}/>,colour:'indigo'},
};
function predictorFamily(p:Predictor){return p.field.startsWith('alphagenome_')?'AlphaGenome':p.tool;}
function PredictorIntroduction({options,selected,onOpen,onAlpha,summary}:{options:Predictor[];selected:string[];onOpen:(group:string)=>void;onAlpha:()=>void;summary?:PredictorSummary}){
  const [activeGroup,setActiveGroup]=useState<string|null>(null);
  const groups=Array.from(new Set(options.map(p=>p.group||'Other predictions')));const families=new Set(options.map(predictorFamily));const alphaShown=selected.includes('AlphaMissense_score');const alpha=options.find(p=>p.field==='AlphaMissense_score');
  return <section className="vc-predictor-intro"><header><div><h3><FlaskConical size={18}/>Prediction toolkit <HelpButton topic="predictions"><details><summary>Method groups</summary><div className="help-sections">{Object.entries(GROUP_GUIDES).map(([name,guide])=><section key={name}><h3>{name}</h3><p>{guide.description}</p></section>)}</div></details><div className="help-sources"><LinkOut href={DBNSFP_COLUMNS}>Score field dictionary</LinkOut></div></HelpButton></h3><span>{summary?.field_count??options.length} selectable fields · {summary?.tool_label_count??families.size} source tool labels</span></div><Button size="sm" onClick={()=>onOpen('')}><Settings2 size={15}/>Choose predictors <b>{selected.length}</b></Button></header>
    <p className="vc-selected-predictors"><strong>Table columns</strong>{selected.length?selected.map(field=>{const project=predictorProject(field);const name=PREDICTOR_GUIDES[field]?.name??options.find(p=>p.field===field)?.tool??field;return project?<LinkOut key={field} href={project.url}><span title={project.label}>{name}</span></LinkOut>:<span key={field}>{name}</span>;}):'No predictor columns selected'}</p>
    <div className="vc-predictor-intro-grid"><article className="vc-alpha-card"><span className="vc-alpha-kicker"><Sparkles size={17}/>AlphaMissense</span><h4>Missense variant effects</h4><p>Score 0–1 · source call</p>{typeof alpha?.covered_variants==='number'&&<span className="vc-alpha-coverage">{number(alpha.covered_variants,0)} variants scored</span>}<div><Button variant="outline" size="sm" className={alphaShown?'selected':''} onClick={onAlpha}>{alphaShown?<Check size={14}/>:<SlidersHorizontal size={14}/>} {alphaShown?'Edit selection':'Add score'}</Button><LinkOut href="https://github.com/google-deepmind/alphamissense">Official repository</LinkOut><LinkOut href="https://deepmind.google/research/publications/21083/">Method</LinkOut></div></article>
    <div className="vc-predictor-group-cards">{groups.map(group=>{const members=options.filter(p=>(p.group||'Other predictions')===group);const guide=GROUP_GUIDES[group]??{description:'Original method-specific annotations and scores.',icon:<FlaskConical size={18}/>,colour:'blue'};return <button key={group} className={`vc-tool-group vc-tool-${guide.colour}${activeGroup===group?' is-previewed':''}`} onPointerEnter={()=>setActiveGroup(group)} onPointerLeave={()=>setActiveGroup(null)} onFocus={()=>setActiveGroup(group)} onBlur={()=>setActiveGroup(null)} onClick={()=>onOpen(group)}><span className="vc-tool-group-icon">{guide.icon}</span><span><strong>{group}</strong><em>{members.length} fields · {new Set(members.map(predictorFamily)).size} tool labels</em></span><ArrowUpRight size={14}/></button>;})}</div></div>
    <p className="vc-tool-preview" aria-live="polite"><span className="vc-tool-preview-dot"/>{activeGroup?<><strong>{activeGroup}</strong><span>{GROUP_GUIDES[activeGroup]?.description??'Original method-specific annotations and scores.'}</span></>:<span>Explore a method group to compare its tools. Open a group to choose columns; linked tool names open their official resources.</span>}</p>
  </section>;
}

function SourceDetails({source,data}:{source:string;data:RecordData}){
  const rows=records(data.sources).filter(r=>r.source===source);
  if(source==='ClinVar')return <ClinvarEvidence rows={rows} hasMore={data.sources_has_more===true}/>;
  return <><p className="vc-note">Original {source} records for this genomic variant. Different submissions and classifications are retained.</p>{rows.length?rows.map((row,i)=><article className="vc-source-record" key={`${row.source_id}:${i}`}><header><span className={`vc-source vc-source-${source.toLowerCase()}`}>{source}</span><strong>{row.source_id&&!['.',''].includes(String(row.source_id))?display(row.source_id):`Source record ${i+1}`}</strong><LinkOut href={row.url}>Open source</LinkOut></header><DetailFields items={row.fields}/></article>):<p className="empty-state">No {source} source annotation is available for this variant.</p>}{data.sources_has_more===true&&<p className="vc-note">The first 100 source records are available here; use the source links for additional submissions.</p>}</>;
}
function VariantDetails({accession,selection,onClose,population}:{accession:string;selection:Selection;onClose:()=>void;population:string}){
  const [tab,setTab]=useState<DetailTab>(selection.tab);const result=useQuery({queryKey:['variant-v2-detail',accession,selection.id],queryFn:({signal})=>api<RecordData>(`/variants/${encodeURIComponent(selection.id)}?${params({accession})}`,signal)});
  const d=result.data;const variant=record(d?.variant);const consequences=records(d?.consequences);
  const tabs:{id:DetailTab;label:string}[]=[{id:'overview',label:'Variant'},{id:'ClinVar',label:'Clinical'},{id:'gnomAD',label:'Frequency'},{id:'predictions',label:'Predictions'},{id:'transcripts',label:'Representative transcripts'},{id:'stability',label:'Stability'}];
  return <Modal title={selection.title} onClose={onClose}><div className="vc-detail"><ModeToggleGroup className="vc-detail-tabs" aria-label="Variant evidence sections" value={tab==='COSMIC'?'ClinVar':tab} onValueChange={setTab} options={tabs.map(t=>({value:t.id,label:t.label}))}/><Status loading={result.isPending} error={result.error}>{d&&<ContentTransition transitionKey={tab}>
    {tab==='overview'&&<><Fields items={[{label:'Genomic variant',value:variant.variant_id},{label:'GRCh38 position',value:`${variant.chromosome}:${variant.position}`},{label:'Genomic alleles',value:`${variant.ref} → ${variant.alt}`} ]}/><div className="vc-detail-entrypoints"><button onClick={()=>setTab('ClinVar')}><ClinicalIcon size={22}/><strong>Clinical source records</strong><span>Classification, review and submitted conditions</span></button><button onClick={()=>setTab('gnomAD')}><FrequencyIcon size={22}/><strong>Allele frequencies</strong><span>Original AF, allele counts and ancestry groups</span></button><button onClick={()=>setTab('predictions')}><PredictionIcon size={22}/><strong>Computational predictions</strong><span>All available tools, grouped by method</span></button></div><TranscriptEvidence consequences={consequences} compact/><HelpButton topic="variants" label="Coordinates & transcripts"/></>}
    {(tab==='ClinVar'||tab==='COSMIC')&&<>
      <ModeToggleGroup className="ve-clinical-sources" aria-label="Clinical evidence sources" value={tab} onValueChange={setTab} options={(['ClinVar','COSMIC'] as const).map(source=>({value:source,label:source}))}/>
      <p className="ve-caption">Original source evidence. COSMIC records describe somatic observations and do not by themselves establish clinical pathogenicity.</p>
      <SourceDetails source={tab} data={d}/>
    </>}
    {tab==='gnomAD'&&<><PopulationDetail frequencies={record(d.frequencies)} selectedPopulation={population}/><Disclosure title="gnomAD source annotations"><SourceDetails source="gnomAD" data={d}/></Disclosure></>}
    {tab==='predictions'&&<PredictionDashboard groups={records(d.prediction_groups)}/>}
    {tab==='transcripts'&&<TranscriptEvidence consequences={consequences}/>}
    {tab==='stability'&&<StabilityEvidence rows={records(d.ddg)} statuses={records(d.ddg_status)}/>}

  </ContentTransition>}</Status></div></Modal>;
}

export default function VariantCatalog({accession,selectedPosition,onClearSelectedPosition}:{accession:string;selectedPosition?:number|null;onClearSelectedPosition?:()=>void}){
  const [searchParams,setSearchParams]=useSearchParams();
  const rangeOrigin=searchParams.get('variants_range_origin')??'';
  const filterValues=Object.fromEntries(FILTER_KEYS.map(key=>[key,searchParams.get(`variants_${key}`)??(key==='frequency'?'overall':key==='transcript_status'?'all':'')])) as Record<typeof FILTER_KEYS[number],string>;
  const selectedRaw=searchParams.get('variants_predictors');
  const selected=selectedRaw===null?DEFAULT_PREDICTORS:selectedRaw==='-'?[]:[...new Set(selectedRaw.split(',').filter(Boolean))];
  const cursor=searchParams.get('variants_cursor')??'';
  const requestedPage=Number(searchParams.get('variants_page')??0);const pageNumber=Number.isSafeInteger(requestedPage)&&requestedPage>=0?requestedPage:0;
  const filterSignature=JSON.stringify([accession,filterValues,selected]);
  const queryParams={...filterValues,predictors:selected.length?selected.join(','):'none'};
  const list=useQuery({queryKey:['variants-v2',accession,filterSignature,cursor,pageNumber],queryFn:({signal})=>api<VariantPage>(`/proteins/${accession}/variants?${params({...queryParams,limit:15,cursor,offset:cursor?undefined:pageNumber*15})}`,signal)});
  const summary=useQuery({queryKey:['variants-v2-summary',accession,JSON.stringify(filterValues)],queryFn:({signal})=>api<Summary>(`/proteins/${accession}/variants/summary?${params(filterValues)}`,signal)});
  // Keep the whole sequence visible when a bin restricts the catalog. Other filters apply to both.
  const distributionFilters={...filterValues,canonical_start:'',canonical_end:''};
  const distribution=useQuery({queryKey:['variants-v2-summary',accession,JSON.stringify(distributionFilters)],queryFn:({signal})=>api<Summary>(`/proteins/${accession}/variants/summary?${params(distributionFilters)}`,signal)});
  const selectedRange:[number,number]|null=Number(filterValues.canonical_start)>0&&Number(filterValues.canonical_end)>=Number(filterValues.canonical_start)?[Number(filterValues.canonical_start),Number(filterValues.canonical_end)]:null;
  const [searchText,setSearchText]=useState(filterValues.search);const [searchError,setSearchError]=useState('');const [picker,setPicker]=useState<{group:string;search:string}|null>(null);const [selection,setSelection]=useState<Selection|null>(null);const detailHistory=useRef(false);
  useEffect(()=>{setSearchText(filterValues.search);},[filterValues.search]);
  const knownSequenceLength=useRef<{accession:string;length:number}|null>(null);
  const sequenceLength=summary.data?.sequence_length??distribution.data?.sequence_length??(knownSequenceLength.current?.accession===accession?knownSequenceLength.current.length:undefined);
  useEffect(()=>{if(sequenceLength)knownSequenceLength.current={accession,length:sequenceLength};},[accession,sequenceLength]);
  const [positionText,setPositionText]=useState('');
  const [positionError,setPositionError]=useState('');
  useEffect(()=>{setPositionText(filterValues.canonical_start ? filterValues.canonical_start===filterValues.canonical_end ? filterValues.canonical_start : `${filterValues.canonical_start}–${filterValues.canonical_end}` : '');setPositionError('');},[filterValues.canonical_start,filterValues.canonical_end]);
  function submitPosition(event:FormEvent){
    event.preventDefault();
    const value=positionText.trim();
    if(!value){clearRange();setPositionError('');return;}
    const match=value.match(/^(\d+)(?:\s*[-–:]\s*(\d+))?$/);
    const start=Number(match?.[1]),end=Number(match?.[2]??match?.[1]);
    if(!match||!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<1||end<start||(sequenceLength&&end>sequenceLength)){
      setPositionError(`Enter a canonical residue or range${sequenceLength?` within 1–${sequenceLength}`:''}, e.g. 858 or 700–900.`);return;
    }
    change({canonical_start:start,canonical_end:end,range_origin:'position'});setPositionError('');
  }
  useEffect(()=>{const closeFromHistory=()=>{if(detailHistory.current){detailHistory.current=false;setSelection(null);}};window.addEventListener('popstate',closeFromHistory);return()=>window.removeEventListener('popstate',closeFromHistory);},[]);
  const options=summary.data?.filters??list.data?.filters;const coverageFields=summary.data?.predictor_summary?.groups.flatMap(group=>group.fields)??[];const coverageByField=new Map(coverageFields.map(field=>[field.field,field]));const definitions=(options?.predictors??DEFAULT_DEFINITIONS).map(p=>({...p,...coverageByField.get(p.field)}));
  const predictorNames=new Map(definitions.map(d=>[d.field,d]));
  // Navigation commits before expensive scientific views finish rendering.
  function change(values:Record<string,string|number|undefined>){
    setSearchParams(()=>{const next=new URLSearchParams(window.location.search);for(const [key,value]of Object.entries(values)){if(value===undefined||value==='')next.delete(`variants_${key}`);else next.set(`variants_${key}`,String(value));}next.delete('variants_cursor');next.delete('variants_page');return next;});
  }
  function clear(){setSearchParams(previous=>{const next=new URLSearchParams(previous);for(const key of FILTER_KEYS)if(key!=='frequency')next.delete(`variants_${key}`);next.delete('variants_range_origin');next.delete('variants_cursor');next.delete('variants_page');return next;});setSearchText('');setSearchError('');}
  function clearRange(){change({canonical_start:'',canonical_end:'',range_origin:''});if(rangeOrigin==='search'){setSearchText(filterValues.search);setSearchError('');}}
  function filterGroup(filter:Record<string,string|number>){const values:Record<string,string|number|undefined>={...filter};if('af_status'in filter||'af_min'in filter||'af_max'in filter){values.af_status=filter.af_status;values.af_min=filter.af_min;values.af_max=filter.af_max;}change(values);}
  function submitSearch(event:FormEvent){event.preventDefault();const value=searchText.trim();const range=value.match(/^(\d+)\s*[-–:]\s*(\d+)$/);if(range){const start=Number(range[1]),end=Number(range[2]);if(start<1||end<start||(summary.data?.sequence_length&&end>summary.data.sequence_length)){setSearchError('Enter a valid interval on the current canonical sequence.');return;}change({search:'',canonical_start:start,canonical_end:end,range_origin:'search'});}else change({search:value,canonical_start:'',canonical_end:'',range_origin:''});setSearchError('');}
  function open(row:VariantRow,tab:DetailTab='overview'){if(!selection){window.history.pushState({...window.history.state,memvarVariantDetail:true},'',window.location.href);detailHistory.current=true;}setSelection({id:row.variant_id,title:shortChange(row),tab});}
  function closeDetail(){if(detailHistory.current)window.history.back();else setSelection(null);}
  function jumpPage(page:number){setSearchParams(current=>{const next=new URLSearchParams(current);next.delete('variants_cursor');next.set('variants_page',String(page));return next;},{replace:true});}
  function nextPage(){if(!list.data?.next_cursor)return;setSearchParams(previous=>{const next=new URLSearchParams(previous);next.set('variants_cursor',list.data!.next_cursor!);next.set('variants_page',String(pageNumber+1));return next;},{replace:true});}
  function previousPage(){jumpPage(Math.max(0,pageNumber-1));}
  const columns=useMemo<ColumnDef<VariantRow>[]>(()=>[
    {id:'genomic-variant',header:()=> <span>Genomic variant<small>GRCh38 · chromosome : position</small></span>,cell:({row})=><button className="vc-genomic" onClick={()=>open(row.original)} title={row.original.variant_id}><strong>{row.original.chromosome}:{row.original.position}</strong><span>{row.original.ref} <span aria-hidden="true">→</span> {row.original.alt}</span></button>},
    {id:'aa-position',header:'Position',cell:({row})=><button className="vc-position" onClick={()=>open(row.original)}><strong>{missing(row.original.aa_position)?'—':row.original.aa_position}</strong></button>},
    {id:'ref-aa',header:'Ref',cell:({row})=><span className="vc-aa vc-aa-ref">{missing(row.original.ref_aa)?'—':row.original.ref_aa}</span>},
    {id:'alt-aa',header:'Alt',cell:({row})=><span className="vc-aa vc-aa-alt">{missing(row.original.alt_aa)?'—':row.original.alt_aa}</span>},
    {id:'consequence',header:'Consequence / transcript',cell:({row})=><div className="vc-consequence"><ConsequencePills value={row.original.consequence}/><button className={`vc-transcript-label vc-transcript-${row.original.transcript_status??'unknown'}`} onClick={()=>open(row.original,'transcripts')} title={`VEP transcript status · raw CANONICAL: ${row.original.canonical_raw??(row.original.transcript_status==='noncanonical'?'not flagged by VEP':'not available')} · independent of UniProt sequence mapping`}>{row.original.transcript_status==='canonical'?'Ensembl canonical':row.original.transcript_status==='noncanonical'?'Noncanonical · VEP unflagged':'Transcript status unknown'}</button>{row.original.canonical_positions?.length?<small className="vc-mapped" title="Verified mapping to the current UniProt canonical sequence"><MapPin size={10}/>UniProt position {row.original.canonical_positions.map(p=>p.position).join(', ')}</small>:null}</div>},
    {id:'sources',header:'Source evidence',cell:({row})=><div className="vc-source-list">{(row.original.source_names??[]).map(source=><SourceButton source={source} key={source} onClick={()=>open(row.original,source==='ClinVar'?'ClinVar':source==='COSMIC'?'COSMIC':source==='gnomAD'?'gnomAD':'overview')}/>)}</div>},
    {id:'clinical',header:'ClinVar classification',cell:({row})=>{const entries=row.original.clinvar??[];const unique=entries.filter((r,i)=>entries.findIndex(o=>o.classification===r.classification&&o.review_status===r.review_status)===i);return unique.length?<button className="vc-clinical-button" onClick={()=>open(row.original,'ClinVar')}>{unique.slice(0,2).map((c,i)=><span key={i}><ClinicalBadge value={c.classification}/><ReviewStars value={c.review_status} compact/></span>)}{unique.length>2?<em>+{unique.length-2} classifications</em>:null}</button>:<span className="vc-missing" title="No ClinVar classification">—</span>;}},
    {id:'frequency',header:()=> <span>Allele frequency<small>{POPULATION_NAMES[filterValues.frequency]??filterValues.frequency}</small></span>,cell:({row})=><FrequencyValue value={row.original.frequency} population={filterValues.frequency} onClick={()=>open(row.original,'gnomAD')}/>},
    ...selected.map(field=>({id:`prediction-${field}`,header:()=> <button className="vc-predictor-heading" onClick={()=>setPicker({group:'',search:field})} title={`${field} · meaning and criteria`}>{PREDICTOR_GUIDES[field]?.name??predictorNames.get(field)?.tool??field}<small>{PREDICTOR_GUIDES[field]?.scale??'Source score'}</small>{PREDICTOR_GUIDES[field]?.direction&&<span className="vc-predictor-direction">{PREDICTOR_GUIDES[field].direction}</span>}</button>,cell:({row}:{row:{original:VariantRow}})=><button className="vc-score-cell" onClick={()=>open(row.original,'predictions')} aria-label={`${PREDICTOR_GUIDES[field]?.name??field} for ${shortChange(row.original)}: open prediction evidence`}><PredictionValue item={row.original.predictions?.find(p=>p.field===field)} compact/></button>} as ColumnDef<VariantRow>)),
    {id:'details',header:'',cell:({row})=><button className="vc-more" onClick={()=>open(row.original)} aria-label={`View ${shortChange(row.original)} details`}><ArrowUpRight size={16}/></button>},
  ],[filterValues.frequency,selected.join(','),definitions]);
  const active=FILTER_KEYS.filter(key=>!['frequency','canonical_start','canonical_end'].includes(key)&&filterValues[key]&&!(key==='transcript_status'&&filterValues[key]==='all'));const groups=summary.data?.groups??[];const totals=summary.data?.totals;
  return <Panel id="variants" title="Variant browser" subtitle="Variant consequences, source evidence and selectable predictions" icon={<Dna/>} color="purple" action={<span className="vc-module-tag">Genomic variants · GRCh38</span>}><div className="vc-catalog">
    {filterValues.consequence&&<nav className="vc-return-nav" aria-label="Variant consequence navigation"><span>Variant consequences</span><b>/</b><strong>{label(filterValues.consequence)}</strong><Button variant="outline" size="sm" onClick={()=>{change({consequence:''});requestAnimationFrame(()=>document.getElementById('variant-consequence-overview')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'}));}}><ChevronLeft size={14}/>Back to overview</Button></nav>}
    <SelectionFeedback visible={!!(selectedRange||selectedPosition)} className="vc-selection-context" aria-label="Catalog range and residue focus"><div><strong>Catalog range &amp; residue focus</strong><span>Range filters apply to the catalog. Residue focus does not filter the table. Clear each independently.</span></div>{selectedRange&&<Button variant="outline" size="sm" onClick={clearRange} title={rangeOrigin==='sequence'?'Range filter from sequence':rangeOrigin==='distribution'?'Range filter from distribution':rangeOrigin==='search'?'Range filter from search':'Canonical range filter'}><MapPin size={13}/>Clear range filter · {selectedRange[0]}–{selectedRange[1]} <X size={12}/></Button>}{selectedPosition&&<Button variant="outline" size="sm" onClick={onClearSelectedPosition}><Dna size={13}/>Clear residue focus · {selectedPosition} <X size={12}/></Button>}<Button variant="ghost" size="sm" className="vc-clear" title="Clear variant filters and selected residue; keep population and predictor columns" onClick={()=>{clear();onClearSelectedPosition?.();}}>Clear filters &amp; residue</Button></SelectionFeedback>
    <div className="vc-summary-heading"><h3><BarChart3 size={17}/>Matching variants</h3><span>All matching variants</span></div>
    {summary.isPending?<div className="vc-summary-loading">Loading full-catalog summaries…</div>:summary.isError?<div className="vc-summary-error" role="alert">Summary unavailable. The catalog below remains accessible. <button className="text-button" onClick={()=>summary.refetch()}>Retry</button></div>:totals&&<>
      <div className="vc-stats"><div><Dna/><span>Matching variants<strong>{number(totals.unique_variants,0)}</strong></span></div><div><Filter/><span>Transcript annotations<strong>{number(totals.annotation_rows,0)}</strong></span></div><div><MapPin/><span>Verified UniProt links<strong>{number(totals.canonical_mapped_variants,0)}</strong></span></div><div><Globe2/><span>AF available / missing<strong>{number(totals.frequency_available,0)} <em>/ {number(totals.frequency_missing,0)}</em></strong></span></div></div>
      {summary.data&&<div id="variant-consequence-overview"><VariantCategoryCharts summary={summary.data} onFilter={filterGroup}/></div>}
      <div className="vc-breakdown"><Disclosure title="Source, classification and frequency breakdown"><div className="vc-summary-groups"><CountGroups title="Sources" icon={<FlaskConical size={15}/>} groups={groups.filter(g=>g.dimension==='source')} onFilter={filterGroup}/><CountGroups title="Clinical classifications" icon={<ShieldCheck size={15}/>} groups={groups.filter(g=>g.dimension==='clinvar')} onFilter={filterGroup} tone/><CountGroups title="Allele frequency" icon={<Globe2 size={15}/>} groups={groups.filter(g=>g.dimension==='frequency')} onFilter={filterGroup}/></div>
      <p className="vc-breakdown-note">Source memberships and original classification groups can overlap; counts are unique variants within each group.</p></Disclosure></div>

    </>}
    {options?.predictors&&<PredictorIntroduction options={definitions} selected={selected} summary={summary.data?.predictor_summary} onOpen={group=>setPicker({group,search:''})} onAlpha={()=>selected.includes('AlphaMissense_score')?setPicker({group:'Sequence models',search:'AlphaMissense'}):change({predictors:['AlphaMissense_score',...selected].join(',')})}/>}
    <section className="vc-distribution vc-catalog-distribution" aria-label="Variant distribution">
      <header><div><h3><BarChart3 size={18}/>Variant distribution <HelpButton title="Variant distribution"><p>Uses the same verified canonical positions and ClinVar display groups as the Sequence browser. Counts are variant–position links, not a new pathogenicity assessment.</p><p>Other catalog filters apply; the selected residue range is highlighted without cropping this overview. Variants without a verified position remain available when the range filter is cleared.</p></HelpButton></h3><span>Current filters · full sequence</span></div></header>
      <Status loading={distribution.isPending} error={distribution.error}>{distribution.data&&!!distribution.data.sequence_length&&<><VariantDistribution sites={distribution.data.canonical_sites} length={distribution.data.sequence_length} selected={selectedRange} onClear={clearRange} onRange={([start,end])=>change({canonical_start:start,canonical_end:end,range_origin:'distribution'})}/><div className="vc-distribution-counts"><span><b>{number(distribution.data.totals.canonical_mapped_variants,0)}</b> mapped variants</span><span><b>{number(distribution.data.totals.canonical_unmapped_variants,0)}</b> without verified positions</span></div></>}{distribution.data&&!distribution.data.sequence_length&&<p className="empty-state">No canonical sequence is available for this distribution.</p>}</Status>
    </section>
    <div className="vc-catalog-heading"><h3><SlidersHorizontal size={18}/>Browse annotations <HelpButton topic="variants"/></h3><span className="vc-browse-caption">{selected.length} predictor columns</span></div>
    <div className="vc-filters"><fieldset className="vc-filter-group vc-filter-query"><legend><Filter size={16}/>Variant selection</legend><div className="vc-filter-fields"><div className="vc-search-field"><label htmlFor="variant-keyword">Variant / amino acid change</label><form className="vc-search" onSubmit={submitSearch}><Search size={16}/><input id="variant-keyword" aria-label="Search variant catalog" placeholder="AA change or variant ID" value={searchText} onChange={e=>setSearchText(e.target.value)}/><button type="submit">Search</button></form></div><div className="vc-search-field"><label htmlFor="variant-position"><MapPin size={13}/>UniProt canonical position</label><form className="vc-search vc-position-search" onSubmit={submitPosition}><input id="variant-position" aria-label="Filter by UniProt canonical position" placeholder="858 or 700–900" value={positionText} aria-invalid={!!positionError} aria-describedby={positionError?'variant-position-error':undefined} onChange={event=>setPositionText(event.target.value)}/><button type="submit">Apply</button>{selectedRange&&<button type="button" aria-label="Clear canonical position filter" onClick={clearRange}><X size={14}/></button>}</form></div><SelectFilter label="Source" value={filterValues.source} options={options?.sources} onChange={v=>change({source:v})}/><SelectFilter label="Variant type" value={filterValues.consequence} options={options?.consequences} onChange={v=>change({consequence:v})}/></div></fieldset><fieldset className="vc-filter-group vc-filter-context"><legend><Globe2 size={16}/>Transcript &amp; population</legend><div className="vc-filter-fields"><div className="vc-transcript-filter" title="Filters only currently published representative transcript consequences. A zero count does not mean the protein has no other transcripts."><SelectFilter label="Representative VEP transcript" allowAll={false} value={filterValues.transcript_status} options={[{value:'all',label:'All transcript statuses'},...['canonical','noncanonical','unknown'].map(value=>{const group=summary.data?.transcript_groups?.find(g=>g.key===value);const name=value==='canonical'?'Ensembl canonical':value==='noncanonical'?'Noncanonical · VEP unflagged':'Unknown';return {value,label:name+(group?` · ${number(group.annotation_rows??group.count,0)} rows`:'')};})]} onChange={v=>change({transcript_status:v})}/></div><SelectFilter label="gnomAD population" allowAll={false} value={filterValues.frequency} options={options?.frequency_types??POPULATIONS} onChange={v=>change({frequency:v})}/></div></fieldset></div>
    {searchError&&<p className="vc-form-error" role="alert">{searchError}</p>}{positionError&&<p id="variant-position-error" className="vc-form-error" role="alert">{positionError}</p>}
    <SelectionFeedback visible={active.length>0} className="vc-active-filters" aria-label="Active variant filters"><Filter size={13}/>{active.map(key=><button key={key} onClick={()=>change({[key]:''})}>{key.replaceAll('_',' ')}: {key==='clinvar'?clinicalLabel(filterValues[key]):label(filterValues[key])}<X size={11}/></button>)}<Button variant="ghost" size="sm" className="vc-clear" onClick={clear}>Clear filters</Button></SelectionFeedback>
    
    <p className="vc-table-reading-note">Scores retain each tool’s scale and direction. Categories appear only when supplied by the source; — means unavailable. AF is shown as a percentage.</p>
    <div className="vc-main-table vc-compact" style={{'--predictor-count':selected.length} as CSSProperties}><Status loading={list.isPending} error={list.error}><DataTable items={list.data?.items??[]} columns={columns}/>{!list.data?.items.length&&<div className="vc-empty-results"><Search size={24}/><strong>No variants match these filters</strong><span>Adjust a condition or return to the complete catalog.</span><Button variant="outline" size="sm" onClick={clear}>Clear filters</Button></div>}</Status></div>
    <div className="vc-pagination"><span>Page {pageNumber+1} · {list.data?.items.length??0} annotation rows{totals?` of ${number(totals.annotation_rows,0)} matching rows`:''}</span><div><Button variant="outline" size="sm" onClick={previousPage} disabled={pageNumber===0||list.isFetching}><ChevronLeft size={15}/>Previous</Button><Button variant="outline" size="sm" onClick={nextPage} disabled={!list.data?.next_cursor||list.isFetching}>Next<ChevronRight size={15}/></Button></div><PageJump page={pageNumber} onJump={jumpPage} totalPages={totals?Math.ceil(totals.annotation_rows/15):undefined} loading={list.isFetching} label="Go to variant page"/></div>
    
    {picker&&<PredictorPicker options={definitions} selected={selected} initialGroup={picker.group} initialSearch={picker.search} onChange={fields=>change({predictors:fields.length?fields.join(','):'-'})} onClose={()=>setPicker(null)}/>}
    {selection&&<VariantDetails key={`${selection.id}:${selection.tab}`} accession={accession} selection={selection} onClose={closeDetail} population={filterValues.frequency}/>} 
  </div></Panel>;
}
