import { useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, FlaskConical, Globe2, Search, ShieldCheck, Star } from 'lucide-react';
import { display, label, number, type RecordData } from '../api';
import { HelpButton } from './HelpGuide';
import { DetailFields, Disclosure, Fields, LinkOut } from './ui';
import { record, records, missing, clinicalTone, clinicalLabel, sourceCall, predTone, SCORE_SCALES, DBNSFP_COLUMNS, consequenceCategory, afPercent, reviewStars, frequencyStyle, scoreVisual, sourceFieldMap, decodedHGVS, type Predictor } from './variant-evidence-model';
import { PREDICTOR_GUIDES } from './predictor-guides';

export function ClinicalBadge({value}:{value:unknown}){return <span className={`vc-clinical vc-clinical-${clinicalTone(value)}`}>{clinicalLabel(value)}</span>;}
export function ReviewStars({value,compact=false}:{value:unknown;compact?:boolean}){
 const stars=reviewStars(value);if(stars===null)return <span className={`ve-review ${compact?'compact':''}`} title="Source did not provide a review status">Review status unavailable</span>;return <span className={`ve-review ${compact?'compact':''}`} title={missing(value)?'Review status unavailable':label(value)}><span className="ve-stars" role="img" aria-label={stars===null?'Review stars unavailable':`${stars} of 4 review stars`}>{stars===null?<span>Review unknown</span>:Array.from({length:4},(_,i)=><Star key={i} size={compact?12:19} fill={i<stars?'currentColor':'none'} className={i<stars?'filled':'empty'}/>)}</span>{!compact&&<span><strong>{stars===null?'Unknown review status':`${stars} / 4 review stars`}</strong><small>{missing(value)?'No source review status':label(value)}</small></span>}</span>;
}
export function PredictionValue({item,compact=false}:{item?:Predictor;compact?:boolean}){
 if(!item||missing(item.value))return <span className="vc-missing" title={label(item?.status)}>—</span>;
 const guide=PREDICTOR_GUIDES[item.field],value=Number(item.value),bar=guide?.scale==='0–1'&&Number.isFinite(value)&&value>=0&&value<=1,visual=scoreVisual(item);
 return <div className={`vc-prediction vc-prediction-${predTone(item)}`} style={{'--score-color':visual.color} as React.CSSProperties}><strong style={{color:visual.color}}>{typeof item.value==='number'?number(item.value,4):display(item.value)}</strong>{bar&&!compact&&<div className="vc-score-scale" title={`Native 0–1. ${visual.caption}`}><span>0</span><i><b style={{width:`${value*100}%`,background:visual.color}}/></i><span>1</span></div>}{item.source_pred?<span className={`vc-pred vc-pred-${predTone(item)}`} title={`Original source code: ${item.source_pred}`}>{sourceCall(item)?.label??item.source_pred_label??item.source_pred}</span>:null}</div>;
}
export function ConsequencePills({value}:{value:unknown}){const terms=String(value??'').split('&').filter(Boolean);return <div className="vc-consequence-pills">{terms.length?terms.map((term,i)=><span key={`${term}:${i}`} className={`vc-effect vc-effect-${consequenceCategory(term)}`}>{label(term)}</span>):<span className="vc-missing" title="Consequence unavailable">—</span>}</div>;}
const POPULATION_NAMES:Record<string,string>={overall:'Overall exomes',afr:'African / African American',amr:'Admixed American',asj:'Ashkenazi Jewish',eas:'East Asian',fin:'Finnish',mid:'Middle Eastern',nfe:'Non-Finnish European',remaining:'Remaining individuals',sas:'South Asian',grpmax:'Maximum ancestry-group AF'};
export function FrequencyValue({value,population,onClick}:{value?:RecordData;population:string;onClick:()=>void}){
 const style=frequencyStyle(value?.af);return <button className="vc-af-button" onClick={onClick} title="Color reflects AF magnitude, not pathogenicity. Open population details."><span className="vc-af-value"><strong style={{color:style.color}}>{afPercent(value?.af)}</strong><Globe2 size={14}/></span><span className="ve-frequency-mini"><i style={{width:style.valid&&!style.zero?`${Math.max(2,style.progress)}%`:style.zero?'2px':'0',background:style.color}}/></span>{typeof value?.population==='string'&&value.population!==population&&<small>{String(value.label??POPULATION_NAMES[String(value.population)]??value.population)}</small>}</button>;
}
function FrequencyLegend(){return <div className="ve-frequency-legend"><span>AF color scale · log₁₀</span><i/><span>≤0.0001% → 100%</span><small>Magnitude only · zero is gray · missing has no bar</small></div>;}
export function PopulationDetail({frequencies,selectedPopulation}:{frequencies:RecordData;selectedPopulation:string}){
 const populations=[{population:'overall',af:frequencies.af,ac:frequencies.ac,an:frequencies.an},...records(frequencies.populations)];
 const available=populations.filter(p=>frequencyStyle(p.af).valid),max=Math.max(0,...available.map(p=>Number(p.af)));
 return <div className="ve-population"><div className="ve-metrics"><div><span>Overall frequency</span><strong style={{color:frequencyStyle(frequencies.af).color}}>{afPercent(frequencies.af)}</strong><small>{display(frequencies.source)}</small></div><div><span>Alleles observed</span><strong>{number(frequencies.ac,0)}</strong><small>of {number(frequencies.an,0)} measured alleles</small></div><div><span>Reported ancestry groups</span><strong>{records(frequencies.populations).filter(p=>p.population!=='grpmax'&&frequencyStyle(p.af).valid).length}</strong><small>Groups with available AF</small></div></div><FrequencyLegend/><p className="ve-caption">Bar width: linear AF relative to this variant’s maximum ({available.length?afPercent(max):'not available'}). Color: fixed AF magnitude scale. Neither encodes pathogenicity.</p><div className="vc-population-chart">{populations.map((p,i)=>{const pop=String(p.population),style=frequencyStyle(p.af);return <div key={`${pop}:${i}`} className={pop===selectedPopulation?'selected':''}><span>{POPULATION_NAMES[pop]??pop}{pop==='grpmax'&&p.selected_ancestry_group?<small className="vc-population-ancestry">{display(p.selected_ancestry_group)}</small>:null}</span><div className="vc-population-track">{style.valid?<i className={style.zero?'zero':''} style={{width:`${max?Number(p.af)/max*100:0}%`,background:style.color}}/>:<em>{missing(p.af)?'No AF':'Invalid AF'}</em>}</div><span className="vc-population-number"><strong style={{color:style.color}}>{afPercent(p.af)}</strong><small>AF {missing(p.af)?'—':String(p.af)}</small></span><small>AC {number(p.ac,0)} / AN {number(p.an,0)}</small></div>;})}</div><Disclosure title="ACMG / ClinGen frequency interpretation"><p>Frequency alone does not assign a clinical classification. The general BA1 criterion uses AF &gt; 5% in a general continental population with at least 2,000 observed alleles, subject to gene- and variant-specific exceptions. BS1 and PM2 require disease- and gene-specific criteria. Overall exome AF, zero AF, or missing data do not establish that these criteria are met.</p><a href="https://www.clinicalgenome.org/docs/variant-curation-sop/" target="_blank" rel="noreferrer">ClinGen variant curation guidance ↗</a></Disclosure><Disclosure title="Frequency source and counting details"><Fields items={[{label:'Source status',value:label(frequencies.status)},{label:'Source filters',value:frequencies.filters}]}/><p className="ve-caption">True zero and missing are separate. Maximum ancestry-group AF is a source summary, not another sampled population. Percentages are the original AF × 100; positive AF below 10⁻⁶ uses the lowest display tint.</p></Disclosure></div>;
}
function IdGroup({name,description,values,url}:{name:string;description:string;values:string[];url?:(id:string)=>string}){
 const [all,setAll]=useState(false);if(!values.length)return null;return <section className={`ve-id-group ve-id-${name.toLowerCase()}`}><header><strong>{name}</strong><span>{description}</span><b>{values.length}</b></header><div>{(all?values:values.slice(0,5)).map(id=><span key={id} className="ve-id-chip">{url?<LinkOut href={url(id)}>{id}</LinkOut>:id}</span>)}{values.length>5&&<button className="text-button" onClick={()=>setAll(!all)}>{all?'Show fewer':`+ ${values.length-5} more`}</button>}</div></section>;
}
function tokens(value:unknown){return [...new Set(String(value??'').split(/[|;,]/).map(x=>x.trim()).filter(x=>x&&x!=='.'&&x!=='-'))];}
function DiseaseIdentifiers({value}:{value:unknown}){
 const groups=new Map<string,string[]>();tokens(value).forEach(raw=>{const split=raw.indexOf(':');const namespace=split<0?'Other':raw.slice(0,split);let id=split<0?raw:raw.slice(split+1);if(namespace.toUpperCase()==='MONDO')id='MONDO:'+id.replace(/^(MONDO:)+/i,'');const list=groups.get(namespace)??[];if(!list.includes(id))list.push(id);groups.set(namespace,list);});
 const urls:Record<string,(id:string)=>string>={'Human Phenotype Ontology':id=>`https://hpo.jax.org/browse/term/${encodeURIComponent(id)}`,MedGen:id=>`https://www.ncbi.nlm.nih.gov/medgen/?term=${encodeURIComponent(id)}`,MONDO:id=>`https://purl.obolibrary.org/obo/${id.replace(':','_')}`,OMIM:id=>`https://omim.org/entry/${encodeURIComponent(id)}`,Orphanet:id=>`https://www.orpha.net/en/disease/detail/${encodeURIComponent(id)}`,MeSH:id=>`https://meshb.nlm.nih.gov/record/ui?ui=${encodeURIComponent(id)}`};
 return <div className="ve-id-grid">{[...groups].map(([name,values])=><IdGroup key={name} name={name} description="Condition identifiers" values={values} url={urls[name]}/>)}</div>;
}
function ConditionNames({value}:{value:unknown}){
 const [all,setAll]=useState(false);const names=[...new Set(String(value??'').split('|').map(x=>x.trim()).filter(x=>x&&x!=='.'&&x!=='-'))];
 return <div className="ve-condition-names">{(all?names:names.slice(0,3)).map(name=><span key={name}>{name}</span>)}{!names.length&&<span>No condition reported</span>}{names.length>3&&<button className="text-button" onClick={()=>setAll(!all)}>{all?'Show fewer conditions':`+ ${names.length-3} conditions`}</button>}</div>;
}
export function ClinvarEvidence({rows,hasMore}:{rows:RecordData[];hasMore:boolean}){
 if(!rows.length)return <p className="empty-state">No ClinVar annotation for this variant.</p>;
 return <div className="ve-clinvar"><HelpButton topic="clinical" label="Classification & review"/>{rows.map((row,i)=>{const f=sourceFieldMap(row);const domains=[{name:'Germline classification',value:f.ClinicalSignificance,review:f.ReviewStatus},{name:'Oncogenicity',value:f.Oncogenicity,review:f.ReviewStatusOncogenicity},{name:'Somatic clinical impact',value:f.SomaticClinicalImpact,review:f.ReviewStatusClinicalImpact}];return <article className="ve-clinvar-record" key={`${row.source_id}:${i}`}><header><span className="vc-source vc-source-clinvar"><ShieldCheck size={15}/>ClinVar</span><strong>Variation {display(row.source_id)}</strong><LinkOut href={row.url}>Variant record ↗</LinkOut></header><div className="ve-assertions">{domains.filter((d,i)=>i===0||(!missing(d.value)&&d.value!=='-')).map(d=><section key={d.name} className={`ve-assertion ve-tone-${clinicalTone(d.value)}`}><span className="ve-eyebrow">{d.name}</span><ClinicalBadge value={d.value}/><div className="ve-review-box"><span>Aggregate review status</span><ReviewStars value={d.review}/></div></section>)}</div><div className="ve-clinical-context"><span><small>Allele origin</small><span className="ve-origin-list">{tokens(f.Origin).length?tokens(f.Origin).map(origin=><b className={`ve-origin ve-origin-${origin.toLowerCase()}`} key={origin}>{origin}</b>):<b>Not reported</b>}</span></span><span><small>Submitting organizations</small><strong>{display(f.NumberSubmitters)}</strong></span></div><section className="ve-conditions"><h3>Reported conditions</h3><ConditionNames value={f.PhenotypeList}/><DiseaseIdentifiers value={f.PhenotypeIDS}/></section><div className="ve-id-grid"><IdGroup name="RCV" description="Variant–condition records" values={tokens(f.RCVaccession)} url={id=>`https://www.ncbi.nlm.nih.gov/clinvar/${encodeURIComponent(id)}/`}/>{[['SCVsForAggregateGermlineClassification','Germline submissions'],['SCVsForAggregateSomaticClinicalImpact','Somatic impact submissions'],['SCVsForAggregateOncogenicityClassification','Oncogenicity submissions']].map(([key,description])=><IdGroup key={key} name="SCV" description={description} values={tokens(f[key])} url={id=>`https://www.ncbi.nlm.nih.gov/clinvar/?term=${encodeURIComponent(id)}`}/>)}</div><Disclosure title="Original ClinVar fields"><DetailFields items={row.fields}/><p className="ve-caption">Condition names and identifiers are source lists; no name-to-ID pairing is inferred. Review stars above describe the aggregate assertion, not each SCV.</p><LinkOut href="https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/">NCBI review status definitions</LinkOut></Disclosure></article>;})}{hasMore&&<p className="ve-caption">Up to 100 source records are shown; follow source links for additional submissions.</p>}</div>;
}

const CALL_LABELS:Record<string,string>={damaging:'Damaging / pathogenic call',tolerated:'Tolerated / benign call',uncertain:'Uncertain / ambiguous call',other:'Score without interpreted call',missing:'No score'};
const CALL_COLORS:Record<string,string>={damaging:'#e43562',tolerated:'#08996c',uncertain:'#d28b08',other:'#3879bc',missing:'#a5b1c1'};
export function PredictionDashboard({groups}:{groups:RecordData[]}){
 const [group,setGroup]=useState(''),[call,setCall]=useState(''),[search,setSearch]=useState(''),[availability,setAvailability]=useState<'scored'|'unmatched'|'missing'|'all'>('scored');
 const all=useMemo(()=>groups.flatMap(g=>records(g.items).map(p=>({...p,group:String(g.name)} as Predictor))),[groups]);
 const available=all.filter(p=>!missing(p.value)),counts=Object.fromEntries(Object.keys(CALL_LABELS).map(key=>[key,all.filter(p=>(missing(p.value)?'missing':predTone(p))===key).length]));
 const availabilityOf=(p:Predictor):'scored'|'unmatched'|'missing'=>{if(!missing(p.value))return 'scored';return /unmatched|mismatch|ambiguous|conflict/i.test(String(p.status??''))?'unmatched':'missing';};
 const filtered=all.filter(p=>(availability==='all'||availabilityOf(p)===availability)&&(!group||p.group===group)&&(!call||(missing(p.value)?'missing':predTone(p))===call)&&`${p.tool} ${p.field} ${PREDICTOR_GUIDES[p.field]?.name??''}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(['AlphaMissense_score','SIFT_score','REVEL_score','CADD_phred'].includes(a.field)?['AlphaMissense_score','SIFT_score','REVEL_score','CADD_phred'].indexOf(a.field):4)-(['AlphaMissense_score','SIFT_score','REVEL_score','CADD_phred'].includes(b.field)?['AlphaMissense_score','SIFT_score','REVEL_score','CADD_phred'].indexOf(b.field):4)||a.tool.localeCompare(b.tool));
 const total=Math.max(1,all.length);let offset=0;const segments=Object.entries(counts).map(([key,count])=>{const start=offset;offset+=count;return {key,count,start};});
 const methodGroups=[...new Set(filtered.map(p=>p.group||'Other predictions'))];
 return <div className="ve-predictions"><div className="ve-prediction-overview"><section className="ve-prediction-distribution"><h3><FlaskConical size={18}/>Prediction overview <HelpButton topic="predictions"/></h3><div className="ve-donut-row"><div className="ve-call-donut"><svg viewBox="0 0 120 120" role="img" aria-label="Distribution of available source prediction calls and missing scores"><circle cx="60" cy="60" r="45" fill="none" stroke="#edf1f7" strokeWidth="12"/>{segments.filter(s=>s.count).map(s=><circle key={s.key} cx="60" cy="60" r="45" fill="none" stroke={CALL_COLORS[s.key]} strokeWidth="12" pathLength="100" strokeDasharray={`${s.count/total*100} ${100-s.count/total*100}`} strokeDashoffset={-s.start/total*100} transform="rotate(-90 60 60)"/>)}</svg><div><strong>{available.length}</strong><small>scored outputs</small></div></div><div className="ve-call-key">{Object.entries(CALL_LABELS).map(([key,text])=><button key={key} className={call===key?'active':''} onClick={()=>{setCall(call===key?'':key);if(key==='missing')setAvailability('all');}}><i style={{background:CALL_COLORS[key]}}/><span>{text}</span><strong>{counts[key]}</strong></button>)}</div></div></section><section className="ve-group-overview"><h3><FlaskConical size={17}/>Method groups</h3>{groups.map(g=>{const items=records(g.items),n=items.filter(p=>!missing(p.value)).length;return <button key={String(g.name)} className={group===g.name?'active':''} onClick={()=>setGroup(group===g.name?'':String(g.name))}><span>{String(g.name)}</span><i><b style={{width:`${items.length?n/items.length*100:0}%`}}/></i><strong>{n}<small> / {items.length}</small></strong></button>;})}<p className="ve-caption">Available / reported outputs</p></section></div><div className="ve-score-guide"><span><i style={{background:CALL_COLORS.damaging}}/>Higher predicted effect</span><span><i style={{background:CALL_COLORS.tolerated}}/>Lower predicted effect</span><span><i style={{background:CALL_COLORS.uncertain}}/>Ambiguous source call</span></div><div className="ve-prediction-filters"><label className="vc-text-input"><Search size={15}/><input aria-label="Search variant predictions" placeholder="Find a tool or score" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Group<select aria-label="Variant prediction group" value={group} onChange={e=>setGroup(e.target.value)}><option value="">All groups</option>{groups.map(g=><option key={String(g.name)}>{String(g.name)}</option>)}</select></label><label>Availability<select aria-label="Prediction availability" value={availability} onChange={e=>setAvailability(e.target.value as typeof availability)}><option value="scored">Has score</option><option value="unmatched">No matched source call</option><option value="missing">No score / source output</option><option value="all">All states</option></select></label>{call&&<button className="button" onClick={()=>setCall('')}>Clear call filter</button>}</div>
 <div className="ve-method-groups">{methodGroups.map(method=><details key={method} open><summary><span>{method}</span><strong>{filtered.filter(p=>(p.group||'Other predictions')===method).length} outputs</strong></summary><div className="ve-score-cards">{filtered.filter(p=>(p.group||'Other predictions')===method).map((p,i)=>{const guide=PREDICTOR_GUIDES[p.field],scale=SCORE_SCALES[p.field],visual=scoreVisual(p),state=availabilityOf(p);return <article key={`${p.field}:${p.annotation_id}:${i}`} className={`ve-score-card ve-score-${state}`} style={{'--score-color':visual.color} as React.CSSProperties}><header><strong>{guide?.name??p.tool}</strong><span>{state==='scored'?'Score available':state==='unmatched'?'Context not matched':'No score'}</span></header><p>{guide?.meaning??`${p.tool} method-specific prediction output.`}</p><PredictionValue item={p}/><span className="ve-score-direction">{(guide?.direction??scale?.direction)?.startsWith('Lower')?<ArrowDown size={14}/>:(guide?.direction??scale?.direction)?.startsWith('Higher')?<ArrowUp size={14}/>:null} {guide?.direction??scale?.direction??'Read on the original source scale'} · {guide?.scale??'Original source scale'}</span>{guide?.criterion&&<p className="ve-score-criterion">{guide.criterion}</p>}<Disclosure title="Method and provenance"><Fields items={[{label:'Original field',value:p.field},{label:'Source',value:p.source},{label:'Scope',value:label(p.scope)},{label:'Transcript',value:p.transcript_id},{label:'Source status',value:label(p.status)},{label:'Category matching',value:label(p.source_pred_status)}]}/>{guide&&<><p className="ve-caption"><strong>{guide.source}</strong> · {guide.meaning}</p><LinkOut href={guide.url}>Method / source definition</LinkOut></>}{!guide&&<LinkOut href={scale?.url??DBNSFP_COLUMNS}>Source field definition</LinkOut>}</Disclosure></article>;})}</div></details>)}</div>{!filtered.length&&<p className="empty-state">No predictions match these filters.</p>}<p className="ve-caption">{filtered.length} outputs shown continuously · methods retain their native scales and are not combined into a single rank.</p></div>;
}
export function TranscriptEvidence({consequences,compact=false}:{consequences:RecordData[];compact?:boolean}){
 if(!consequences.length)return <p className="empty-state">No representative transcript consequence is available.</p>;
 return <div className="ve-transcripts">
  <div className="ve-transcript-intro">
   <strong>Representative transcript annotations</strong>
   <span>MANE Select is used first. Ensembl canonical is used only when the gene has no MANE Select. All effects and transcript-dependent scores here retain that selected transcript context.</span>
   <span>UniProt sequence matching is a separate comparison; a transcript designation or gene association does not establish an isoform match.</span>
  </div>
  {consequences.map((c,i)=>{
   const f=sourceFieldMap(c);
   const sequence=record(c.sequence_relation),exactMatches=records(sequence.exact_matches);
   const selection=c.selection_method==='mane_select'?'MANE Select':c.selection_method==='ensembl_canonical'?'Ensembl canonical · gene has no MANE Select':missing(c.selection_method)?'Selection unavailable':label(c.selection_method);
   const transcript=missing(c.transcript_id)?null:String(c.transcript_id);
   const protein=missing(c.protein_id)?null:String(c.protein_id);
   return <article className="ve-transcript-card" key={`${c.annotation_id??i}:${c.gene_id??''}`}>
    <header><span className="ve-mane">{selection}</span><span className={`ve-transcript-flag ${c.transcript_status==='canonical'?'canonical':''}`}>{c.transcript_status==='canonical'?'VEP canonical flag':c.transcript_status==='noncanonical'?'VEP canonical flag absent':'VEP canonical status unavailable'}</span></header>
    <dl className="ve-representative-ids">
     <div><dt>Transcript ID</dt><dd><LinkOut href={transcript?`https://www.ensembl.org/Homo_sapiens/Transcript/Summary?t=${encodeURIComponent(transcript)}`:null}>{transcript??'Not provided'}</LinkOut></dd></div>
     <div><dt>Protein ID</dt><dd><LinkOut href={protein?`https://www.ensembl.org/Homo_sapiens/Transcript/ProteinSummary?p=${encodeURIComponent(protein)}`:null}>{protein??'Not provided'}</LinkOut></dd></div>
     <div><dt>Gene ID</dt><dd>{missing(c.gene_id)?'Not provided':String(c.gene_id)}</dd></div>
    </dl>
    <section className="ve-sequence-relation"><strong>Full-length UniProt sequence relation</strong>
     {sequence.comparison_status==='exact_match'&&exactMatches.length>0?<><span>Exact amino acid sequence match{exactMatches.length===1?'':'es'} · {exactMatches.length} target{exactMatches.length===1?'':'s'}</span><div className="ve-sequence-targets">{exactMatches.map((match,j)=>{const target=String(match.target_sequence_id??match.target_accession);return <span key={`${target}:${j}`}><LinkOut href={`https://www.uniprot.org/uniprotkb/${encodeURIComponent(target)}`}>{String(match.target_accession)}{match.target_isoform_id?` · ${String(match.target_isoform_id)}`:' · canonical'}</LinkOut></span>;})}</div></>:
      <span>{sequence.comparison_status==='exact_unmatched'?'Exact unmatched · compared candidate UniProt sequences have no full-length match.':sequence.comparison_status==='input_sequence_missing'?'Input sequence missing · exact comparison was not possible.':sequence.comparison_status==='target_sequence_missing'?'Target UniProt sequence missing · exact comparison was not possible.':sequence.comparison_status==='representative_identity_mismatch'?'Representative identity differs between published tables; no sequence relation is asserted.':sequence.comparison_status==='not_compared'?'Not compared · a required sequence or candidate was unavailable.':'Sequence relation unavailable for this representative annotation.'}</span>}
     <small>{sequence.input_sequence_source?`${label(sequence.input_sequence_source)} input · `:''}Sequence equality does not validate this variant’s residue coordinate or clinical effect.</small>
    </section>
    <div className="ve-transcript-changes"><div><small>Protein change · representative</small><strong>{decodedHGVS(c.hgvsp)}</strong></div><div><small>Coding change · representative</small><strong>{decodedHGVS(c.hgvsc)}</strong></div><div><small>{f.EXON?'Exon':f.INTRON?'Intron':'Transcript region'}</small><strong>{display(f.EXON??f.INTRON??'—')}</strong></div></div>
    <ConsequencePills value={c.consequence}/>
    {!compact&&<Disclosure title="Source annotation details"><Fields items={[{label:'MANE RefSeq transcript',value:f.MANE_SELECT??f.MANE_PLUS_CLINICAL},{label:'Biotype',value:label(f.BIOTYPE)},{label:'VEP impact',value:f.IMPACT},{label:'Transcript support level',value:f.TSL},{label:'APPRIS',value:f.APPRIS},{label:'Original canonical flag',value:c.canonical_raw}]}/><p className="ve-caption">Identifiers retain their source versions when supplied. A missing version is not inferred from the ID alone.</p></Disclosure>}
   </article>;
  })}
 </div>;
}

export function StabilityEvidence({rows,statuses}:{rows:RecordData[];statuses:RecordData[]}){
 const max=Math.max(0,...rows.filter(r=>!missing(r.ddg_pred)&&Number.isFinite(Number(r.ddg_pred))).map(r=>Math.abs(Number(r.ddg_pred))));
 return <div className="ve-stability"><p className="ve-caption">ΔΔG retains the original model convention. Colors indicate predicted stability direction, not clinical pathogenicity.</p>{rows.length?rows.map((r,i)=>{const valid=!missing(r.ddg_pred)&&Number.isFinite(Number(r.ddg_pred)),v=Number(r.ddg_pred),known=!!r.effect_convention&&String(r.effect_convention).startsWith('Negative values predict stabilization; positive values predict destabilization.'),tone=valid&&known?(v<0?'stabilizing':v>0?'destabilizing':'unchanged'):'unknown',effect=tone==='stabilizing'?'Predicted stabilization':tone==='destabilizing'?'Predicted destabilization':tone==='unchanged'?'Zero predicted change':'Direction unavailable';return <article className={`ve-stability-card ve-stability-${tone}`} key={`${r.annotation_id}:${i}`}><header><strong>{display(r.model)}</strong><span>{display(r.ref_aa)}{display(r.position)}{display(r.alt_aa)}</span><small>{display(r.sequence_id)}</small></header><div className="ve-stability-result"><strong>{valid?`${v>0?'+':''}${number(v,4)}`:'—'}<small>{display(r.unit)}</small></strong><span>{known&&valid&&(v<0?<ArrowDown size={18}/>:v>0?<ArrowUp size={18}/>:null)}{effect}</span></div><div className="ve-ddg-axis"><i/><b style={{left:`${valid&&v<0?50-(max?Math.abs(v)/max*48:0):50}%`,width:`${valid&&max?Math.abs(v)/max*48:0}%`}}/><span>0</span></div><div className="ve-ddg-labels"><span>−{number(max,3)}</span><span>+{number(max,3)}</span></div><p className="ve-caption">Axis scaled to the largest |ΔΔG| shown here; compare signed values, not bar lengths across variants.</p>{r.effect_convention?<p className="ve-caption">{String(r.effect_convention)}</p>:null}</article>;}):<p className="empty-state">No validated ΔΔG prediction is available for this variant.</p>}{statuses.length>0&&<Disclosure title="Sequence and prediction availability">{statuses.map((r,i)=><Fields key={i} items={[{label:'Sequence',value:label(r.sequence_status)},{label:'Prediction',value:label(r.prediction_status)}]}/>)}</Disclosure>}</div>;
}
