import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import App from './App';
import './design-system.css';
import './refined-surfaces.css';
import { MotionConfig } from 'motion/react';
import { TooltipProvider } from '@/components/ui/tooltip';
const queryClient = new QueryClient({defaultOptions:{queries:{staleTime:300_000,retry:1,refetchOnWindowFocus:false}}});
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={queryClient}><MotionConfig reducedMotion="user"><TooltipProvider delayDuration={250}><BrowserRouter><App/></BrowserRouter></TooltipProvider></MotionConfig></QueryClientProvider></React.StrictMode>);
